//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FaceDetectAgentDelegate.h"
#import "FaceDetectServiceDelegate.h"

@class FaceDetectService, NSString;

@interface ABFaceLivenessService : NSObject <FaceDetectAgentDelegate, FaceDetectServiceDelegate>
{
    FaceDetectService *_faceDetectService;	// 8 = 0x8
}

+ (int)getDetectionType;	// IMP=0x00000001012b631c
@property(retain, nonatomic) FaceDetectService *faceDetectService; // @synthesize faceDetectService=_faceDetectService;
- (void).cxx_destruct;	// IMP=0x00000001012b87a8
- (void)onFrameDetected:(id)arg1 andTimeout:(float)arg2;	// IMP=0x00000001012b85bc
- (int)onDetectSuccess:(id)arg1;	// IMP=0x00000001012b8044
- (void)saveFaceInfoEx:(id)arg1 andActionInfo:(id)arg2;	// IMP=0x00000001012b78d4
- (void)saveFaceInfo:(id)arg1 andActionInfo:(id)arg2;	// IMP=0x00000001012b7264
- (struct CGRect)getFaceRangeInfo:(id)arg1;	// IMP=0x00000001012b7208
- (struct CGRect)calFaceRect:(struct CGRect)arg1 newSize:(struct CGSize)arg2;	// IMP=0x00000001012b7204
- (id)getQualityFrame:(id)arg1;	// IMP=0x00000001012b70b0
- (void)showMinesAlert:(id)arg1;	// IMP=0x00000001012b6fd4
- (void)onDetectFailed:(int)arg1;	// IMP=0x00000001012b6460
- (void)managePhase;	// IMP=0x00000001012b623c
- (void)manageFinished;	// IMP=0x00000001012b56bc
- (void)manageActionEnd;	// IMP=0x00000001012b5340
- (void)manageActionBegin;	// IMP=0x00000001012b509c
- (void)manageCaptureFaceEnd;	// IMP=0x00000001012b4dd8
- (void)manageCaptureFaceBegin;	// IMP=0x00000001012b4d0c
- (void)manageInitFace;	// IMP=0x00000001012b4c20
- (void)showPhase;	// IMP=0x00000001012b4b20
- (void)detectWithBuffer:(struct opaqueCMSampleBuffer *)arg1 orientation:(long long)arg2;	// IMP=0x00000001012b4a34
- (void)restartDetect;	// IMP=0x00000001012b45ac
- (void)startDetect;	// IMP=0x00000001012b41ac
- (void)closeDetect;	// IMP=0x00000001012b412c
- (id)init;	// IMP=0x00000001012b4048

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

