//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ACDataContext, NSArray, NSDictionary;

@protocol ACDataDelegate <NSObject>

@optional
- (void)didFetchedDataWithDataContext:(ACDataContext *)arg1;
- (NSArray *)additionalTilesWhenEmptyDataWithDataContext:(ACDataContext *)arg1;
- (NSArray *)willProcessTiles:(NSArray *)arg1 withDataContext:(ACDataContext *)arg2;
- (NSArray *)willProcessTileDTOs:(NSArray *)arg1 withDataContext:(ACDataContext *)arg2;
- (NSDictionary *)willFetchDataWithParam:(NSDictionary *)arg1 withDataContext:(ACDataContext *)arg2;
- (_Bool)needPullToRefreshForSegmentIndex:(long long)arg1;
- (_Bool)needPullToRefresh;
- (_Bool)needLocalCache;
- (NSArray *)precessBackToTopFloorsDTOs:(NSArray *)arg1 withDataContext:(ACDataContext *)arg2;
@end

