//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ACRouterEntity : NSObject
{
    NSString *_sceneId;	// 8 = 0x8
    long long _matchOption;	// 16 = 0x10
    NSString *_destinationViewController;	// 24 = 0x18
    NSString *_displayingViewController;	// 32 = 0x20
}

@property(retain, nonatomic) NSString *displayingViewController; // @synthesize displayingViewController=_displayingViewController;
@property(retain, nonatomic) NSString *destinationViewController; // @synthesize destinationViewController=_destinationViewController;
@property(nonatomic) long long matchOption; // @synthesize matchOption=_matchOption;
@property(retain, nonatomic) NSString *sceneId; // @synthesize sceneId=_sceneId;
- (void).cxx_destruct;	// IMP=0x00000001009e9008

@end

