//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFCommandService.h"

@interface AEAddToCartCommandV2 : AFCommandService
{
}

- (void)callbackWithError:(id)arg1;	// IMP=0x00000001004749c4
- (void)callbackWithParam:(id)arg1 result:(id)arg2;	// IMP=0x00000001004747f4
- (void)showAlertWithResult:(id)arg1;	// IMP=0x0000000100474180
- (void)fbTrackIfNeeded:(id)arg1;	// IMP=0x0000000100473de4
- (void)runWithParams:(id)arg1;	// IMP=0x00000001004738f8

@end

