//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AEMobileFixedDiscountWrapInfo, AEMobileSellerCouponWrapInfo, AEMobileShoppingCouponWrapInfo;

@interface AEAllCouponDTO : NSObject
{
    AEMobileSellerCouponWrapInfo *_mobileSellerCouponWrapInfo;	// 8 = 0x8
    AEMobileShoppingCouponWrapInfo *_mobileShoppingCouponWrapInfo;	// 16 = 0x10
    AEMobileFixedDiscountWrapInfo *_mobileFixedDiscountWrapInfo;	// 24 = 0x18
}

@property(retain, nonatomic) AEMobileFixedDiscountWrapInfo *mobileFixedDiscountWrapInfo; // @synthesize mobileFixedDiscountWrapInfo=_mobileFixedDiscountWrapInfo;
@property(retain, nonatomic) AEMobileShoppingCouponWrapInfo *mobileShoppingCouponWrapInfo; // @synthesize mobileShoppingCouponWrapInfo=_mobileShoppingCouponWrapInfo;
@property(retain, nonatomic) AEMobileSellerCouponWrapInfo *mobileSellerCouponWrapInfo; // @synthesize mobileSellerCouponWrapInfo=_mobileSellerCouponWrapInfo;
- (void).cxx_destruct;	// IMP=0x000000010047fcc4

@end

