//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "StackTile.h"

#import "AEStackTileEnvironment.h"

@class AEBaseStackTileStyle, NSString, UIView;

@interface AEBaseStackTile : StackTile <AEStackTileEnvironment>
{
    _Bool unfinished;	// 8 = 0x8
    UIView *_tileView;	// 16 = 0x10
    unsigned long long _border;	// 24 = 0x18
    AEBaseStackTileStyle *_aeStyle;	// 32 = 0x20
}

+ (Class)styleClass;	// IMP=0x00000001009e9934
@property(retain, nonatomic) AEBaseStackTileStyle *aeStyle; // @synthesize aeStyle=_aeStyle;
@property(nonatomic) unsigned long long border; // @synthesize border=_border;
@property(nonatomic) __weak UIView *tileView; // @synthesize tileView=_tileView;
@property(nonatomic) _Bool unfinished; // @synthesize unfinished;
- (void).cxx_destruct;	// IMP=0x00000001009e9df0
- (_Bool)hiddenInViewHierarchy;	// IMP=0x00000001009e9c48
- (id)initWithTileDTO:(id)arg1;	// IMP=0x00000001009e99e8
- (id)init;	// IMP=0x00000001009e99d8
@property(retain, nonatomic) AEBaseStackTileStyle *style; // @dynamic style;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

