//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AEBloomButton;

@protocol AEBloomButtonDelegate <NSObject>
- (void)pathButton:(AEBloomButton *)arg1 clickItemButtonAtIndex:(unsigned long long)arg2;

@optional
- (void)didDismissDCPathButtonItems:(AEBloomButton *)arg1;
- (void)willDismissDCPathButtonItems:(AEBloomButton *)arg1;
- (void)didPresentDCPathButtonItems:(AEBloomButton *)arg1;
- (void)willPresentDCPathButtonItems:(AEBloomButton *)arg1;
@end

