//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

@class AEWebView;

@interface AEBuyerProtectionViewController : AEUIViewController
{
    AEWebView *_webView;	// 8 = 0x8
}

@property(retain, nonatomic) AEWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;	// IMP=0x0000000100485f94
- (void)close:(id)arg1;	// IMP=0x0000000100485efc
- (id)pageTrackName;	// IMP=0x0000000100485ed0
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100485e9c
- (void)viewDidLoad;	// IMP=0x00000001004858fc

@end

