//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIView;

@interface AECartSelectionBaseCell : UITableViewCell
{
    _Bool _selectionEnable;	// 8 = 0x8
    _Bool _buttonSelected;	// 9 = 0x9
    _Bool _cripple;	// 10 = 0xa
    _Bool _needUpdateConstraints;	// 11 = 0xb
    UIView *_leftHelperView;	// 16 = 0x10
    UIView *_checkboxCenterYAlignView;	// 24 = 0x18
    CDUnknownBlockType _selectionBlock;	// 32 = 0x20
    UIButton *_checkboxButton;	// 40 = 0x28
}

@property(nonatomic) _Bool needUpdateConstraints; // @synthesize needUpdateConstraints=_needUpdateConstraints;
@property(retain, nonatomic) UIButton *checkboxButton; // @synthesize checkboxButton=_checkboxButton;
@property(copy, nonatomic) CDUnknownBlockType selectionBlock; // @synthesize selectionBlock=_selectionBlock;
@property(nonatomic) _Bool cripple; // @synthesize cripple=_cripple;
@property(nonatomic) _Bool buttonSelected; // @synthesize buttonSelected=_buttonSelected;
@property(nonatomic) _Bool selectionEnable; // @synthesize selectionEnable=_selectionEnable;
@property(retain, nonatomic) UIView *checkboxCenterYAlignView; // @synthesize checkboxCenterYAlignView=_checkboxCenterYAlignView;
@property(retain, nonatomic) UIView *leftHelperView; // @synthesize leftHelperView=_leftHelperView;
- (void).cxx_destruct;	// IMP=0x00000001004af5fc
- (void)onChecked:(id)arg1;	// IMP=0x00000001004af3c0
- (void)updateConstraintsForSelectionDisable;	// IMP=0x00000001004aefa8
- (void)updateConstraintsForSelectionEnable;	// IMP=0x00000001004ae8ac
- (void)updateConstraints;	// IMP=0x00000001004ae79c
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001004ae5a0

@end

