//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSString;

@interface AECategoryRefineSingleCategoryDTO : NSObject <NSCopying>
{
    _Bool isLeaf;	// 8 = 0x8
    NSString *categoryCount;	// 16 = 0x10
    NSString *categoryId;	// 24 = 0x18
    NSString *name;	// 32 = 0x20
    NSArray *subCategories;	// 40 = 0x28
    NSArray *brotherCategories;	// 48 = 0x30
}

+ (id)objectClassInArray;	// IMP=0x0000000100c4cd0c
+ (id)replacedKeyFromPropertyName;	// IMP=0x0000000100c4cca4
@property(retain, nonatomic) NSArray *brotherCategories; // @synthesize brotherCategories;
@property(retain, nonatomic) NSArray *subCategories; // @synthesize subCategories;
@property(copy, nonatomic) NSString *name; // @synthesize name;
@property(nonatomic) _Bool isLeaf; // @synthesize isLeaf;
@property(copy, nonatomic) NSString *categoryId; // @synthesize categoryId;
@property(copy, nonatomic) NSString *categoryCount; // @synthesize categoryCount;
- (void).cxx_destruct;	// IMP=0x0000000100c4d17c
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100c4cf44
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100c4cdd0

@end

