//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AEChannelSubscribeService : NSObject
{
}

- (void)updateSubscription:(id)arg1 action:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100ba0430
- (void)querySubscription:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100ba0154

@end

