//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTile.h"

@class NSArray;

@interface AECoinsTaskEntrancesFloorViewModel : AEBaseTile
{
    NSArray *_taskModels;	// 8 = 0x8
}

+ (Class)cellClass;	// IMP=0x00000001002ee488
@property(copy, nonatomic) NSArray *taskModels; // @synthesize taskModels=_taskModels;
- (void).cxx_destruct;	// IMP=0x00000001002ee354
- (id)initWithTileDTO:(id)arg1;	// IMP=0x00000001002ee0fc

@end

