//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTileComponent.h"

@class AEComponentPhotoReviewsItemBottomBarViewModel, AEImageTileComponent, NSString;

@interface AEComponentPhotoReviewsItemViewModel : AEBaseTileComponent
{
    NSString *_action;	// 8 = 0x8
    AEImageTileComponent *_productModel;	// 16 = 0x10
    AEComponentPhotoReviewsItemBottomBarViewModel *_bottomBarModel;	// 24 = 0x18
}

@property(retain, nonatomic) AEComponentPhotoReviewsItemBottomBarViewModel *bottomBarModel; // @synthesize bottomBarModel=_bottomBarModel;
@property(retain, nonatomic) AEImageTileComponent *productModel; // @synthesize productModel=_productModel;
@property(copy, nonatomic) NSString *action; // @synthesize action=_action;
- (void).cxx_destruct;	// IMP=0x00000001002fb368
- (double)heightForReferenceWidth:(double)arg1;	// IMP=0x00000001002fb0d0
- (id)infoButtonWithComponentDTO:(id)arg1 image:(id)arg2;	// IMP=0x00000001002fcd0c
- (id)initWithTileDTO:(id)arg1;	// IMP=0x00000001002fca08

@end

