//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTileComponent.h"

@class AETextTileComponent;

@interface AEComponentCoinsExchangeAlertViewModel : AEBaseTileComponent
{
    AETextTileComponent *_titleModel;	// 8 = 0x8
    AETextTileComponent *_contentModel;	// 16 = 0x10
    AETextTileComponent *_cancelModel;	// 24 = 0x18
    AETextTileComponent *_okModel;	// 32 = 0x20
}

@property(retain, nonatomic) AETextTileComponent *okModel; // @synthesize okModel=_okModel;
@property(retain, nonatomic) AETextTileComponent *cancelModel; // @synthesize cancelModel=_cancelModel;
@property(retain, nonatomic) AETextTileComponent *contentModel; // @synthesize contentModel=_contentModel;
@property(retain, nonatomic) AETextTileComponent *titleModel; // @synthesize titleModel=_titleModel;
- (void).cxx_destruct;	// IMP=0x00000001009b8c34

@end

