//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AECoinTaskCouponDTO, AECoinTaskItemDTO, UIImageView, UILabel;

@interface AECoinsInnerContentView : UIView
{
    UIImageView *_bgImageView;	// 8 = 0x8
    UILabel *_coinsLabel;	// 16 = 0x10
    UILabel *_titleLabel;	// 24 = 0x18
    UILabel *_infoLabel;	// 32 = 0x20
    UILabel *_couponTitleLabel;	// 40 = 0x28
    UIImageView *_leftBgImageView;	// 48 = 0x30
    UIImageView *_rightBgImageView;	// 56 = 0x38
    long long _type;	// 64 = 0x40
    AECoinTaskItemDTO *_dto;	// 72 = 0x48
    AECoinTaskCouponDTO *_couponDTO;	// 80 = 0x50
}

@property(retain, nonatomic) AECoinTaskCouponDTO *couponDTO; // @synthesize couponDTO=_couponDTO;
@property(retain, nonatomic) AECoinTaskItemDTO *dto; // @synthesize dto=_dto;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) UIImageView *rightBgImageView; // @synthesize rightBgImageView=_rightBgImageView;
@property(retain, nonatomic) UIImageView *leftBgImageView; // @synthesize leftBgImageView=_leftBgImageView;
@property(retain, nonatomic) UILabel *couponTitleLabel; // @synthesize couponTitleLabel=_couponTitleLabel;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *coinsLabel; // @synthesize coinsLabel=_coinsLabel;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
- (void).cxx_destruct;	// IMP=0x00000001007efdd0
- (void)buildSellerCouponUI;	// IMP=0x00000001007ef01c
- (void)buildShoppingCouponUI;	// IMP=0x00000001007edb38
- (void)buildPlatformCouponUI;	// IMP=0x00000001007ecfbc
- (void)buildCoinsUI;	// IMP=0x00000001007ec8f4
- (void)buildUI;	// IMP=0x00000001007ec124
- (id)initWithType:(long long)arg1 withDTO:(id)arg2 withCouponDTO:(id)arg3;	// IMP=0x00000001007ec050

@end

