//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol AECouponServiceProtocol <NSObject>
- (void)sentPlatFormCouponWithBusinessKey:(NSString *)arg1 completion:(void (^)(_Bool, AEWatchCouponDTO *, NSError *))arg2;
- (void)getCouponInfoWithBusinessKey:(NSString *)arg1 complete:(void (^)(_Bool, AEWatchCouponDTO *, NSError *))arg2;
- (void)loadExchangeCoupons:(NSString *)arg1 complete:(void (^)(_Bool, AECouponDTO *, NSError *))arg2;
@end

