//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AETileAdapterView.h"

@class AESmartProductComponent, UIColor, UIFont;

@interface AEComponent3Products1Row : AETileAdapterView
{
    _Bool _enableProductBorder;	// 8 = 0x8
    double _padding;	// 16 = 0x10
    AESmartProductComponent *_smartProduct1;	// 24 = 0x18
    AESmartProductComponent *_smartProduct2;	// 32 = 0x20
    AESmartProductComponent *_smartProduct3;	// 40 = 0x28
    UIFont *_prompt1Font;	// 48 = 0x30
    UIFont *_prompt2Font;	// 56 = 0x38
    UIColor *_prompt1TextColor;	// 64 = 0x40
    UIColor *_prompt2TextColor;	// 72 = 0x48
}

@property(retain, nonatomic) UIColor *prompt2TextColor; // @synthesize prompt2TextColor=_prompt2TextColor;
@property(retain, nonatomic) UIColor *prompt1TextColor; // @synthesize prompt1TextColor=_prompt1TextColor;
@property(retain, nonatomic) UIFont *prompt2Font; // @synthesize prompt2Font=_prompt2Font;
@property(retain, nonatomic) UIFont *prompt1Font; // @synthesize prompt1Font=_prompt1Font;
@property(retain, nonatomic) AESmartProductComponent *smartProduct3; // @synthesize smartProduct3=_smartProduct3;
@property(retain, nonatomic) AESmartProductComponent *smartProduct2; // @synthesize smartProduct2=_smartProduct2;
@property(retain, nonatomic) AESmartProductComponent *smartProduct1; // @synthesize smartProduct1=_smartProduct1;
@property(nonatomic) double padding; // @synthesize padding=_padding;
@property(nonatomic) _Bool enableProductBorder; // @synthesize enableProductBorder=_enableProductBorder;
- (void).cxx_destruct;	// IMP=0x0000000100a06f0c
- (_Bool)renderWithTile:(id)arg1;	// IMP=0x0000000100a062c8
- (void)prepareForReuse;	// IMP=0x0000000100a0626c
- (void)configConstraints;	// IMP=0x0000000100a05a94
- (void)configSubviews;	// IMP=0x0000000100a0594c
- (void)setBackgroundColor:(id)arg1;	// IMP=0x0000000100a058a0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100a057ec

@end

