//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AETileAdapterView.h"

@class UIImageView;

@interface AEComponentRoundPortrait : AETileAdapterView
{
    double _padding;	// 8 = 0x8
    UIImageView *_portrait;	// 16 = 0x10
}

@property(retain, nonatomic) UIImageView *portrait; // @synthesize portrait=_portrait;
@property(nonatomic) double padding; // @synthesize padding=_padding;
- (void).cxx_destruct;	// IMP=0x00000001009fff38
- (_Bool)renderWithTile:(id)arg1;	// IMP=0x00000001009ffbb8
- (void)layoutSubviews;	// IMP=0x00000001009ffa88
- (void)configConstraints;	// IMP=0x00000001009ff898
- (void)configSubviews;	// IMP=0x00000001009ff7fc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001009ff758

@end

