//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AECreditCardCellViewModel : NSObject
{
    long long _cardType;	// 8 = 0x8
    NSString *_cardNo;	// 16 = 0x10
    NSString *_cardID;	// 24 = 0x18
}

@property(retain, nonatomic) NSString *cardID; // @synthesize cardID=_cardID;
@property(retain, nonatomic) NSString *cardNo; // @synthesize cardNo=_cardNo;
@property(nonatomic) long long cardType; // @synthesize cardType=_cardType;
- (void).cxx_destruct;	// IMP=0x0000000100046bd4

@end

