//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class AECropOverlayView, CAShapeLayer, NSString, NSTimer, UIImage, UIImageView, UIPanGestureRecognizer, UIScrollView;

@interface AECropImageView : UIView <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _cropBoxResizeEnabled;	// 8 = 0x8
    _Bool _canBeReset;	// 9 = 0x9
    _Bool _simpleRenderMode;	// 10 = 0xa
    _Bool _internalLayoutDisabled;	// 11 = 0xb
    _Bool _aspectRatioLockEnabled;	// 12 = 0xc
    _Bool _resetAspectRatioEnabled;	// 13 = 0xd
    _Bool _croppingViewsHidden;	// 14 = 0xe
    _Bool _gridOverlayHidden;	// 15 = 0xf
    _Bool _applyInitialCroppedImageFrame;	// 16 = 0x10
    _Bool _editing;	// 17 = 0x11
    _Bool _disableForgroundMatching;	// 18 = 0x12
    _Bool _applyInitialRotatedAngle;	// 19 = 0x13
    _Bool _rotateAnimationInProgress;	// 20 = 0x14
    _Bool _dynamicBlurEffect;	// 21 = 0x15
    UIImage *_image;	// 24 = 0x18
    AECropOverlayView *_gridOverlayView;	// 32 = 0x20
    id <AECropImageViewDelegate> _delegate;	// 40 = 0x28
    long long _angle;	// 48 = 0x30
    UIImageView *_backgroundImageView;	// 56 = 0x38
    UIView *_backgroundContainerView;	// 64 = 0x40
    UIImageView *_foregroundImageView;	// 72 = 0x48
    UIView *_foregroundContainerView;	// 80 = 0x50
    UIScrollView *_scrollView;	// 88 = 0x58
    UIView *_overlayView;	// 96 = 0x60
    UIView *_translucencyView;	// 104 = 0x68
    id _translucencyEffect;	// 112 = 0x70
    CAShapeLayer *_circularMaskLayer;	// 120 = 0x78
    UIPanGestureRecognizer *_gridPanGestureRecognizer;	// 128 = 0x80
    long long _tappedEdge;	// 136 = 0x88
    NSTimer *_resetTimer;	// 144 = 0x90
    long long _cropBoxLastEditedAngle;	// 152 = 0x98
    double _cropBoxLastEditedZoomScale;	// 160 = 0xa0
    double _cropBoxLastEditedMinZoomScale;	// 168 = 0xa8
    long long _restoreAngle;	// 176 = 0xb0
    struct CGSize _aspectRatio;	// 184 = 0xb8
    struct CGPoint _panOriginPoint;	// 200 = 0xc8
    struct CGPoint _rotationContentOffset;	// 216 = 0xd8
    struct CGSize _rotationContentSize;	// 232 = 0xe8
    struct CGSize _rotationBoundSize;	// 248 = 0xf8
    struct CGSize _cropBoxLastEditedSize;	// 264 = 0x108
    struct CGSize _originalCropBoxSize;	// 280 = 0x118
    struct CGPoint _originalContentOffset;	// 296 = 0x128
    struct CGRect _cropBoxFrame;	// 312 = 0x138
    struct UIEdgeInsets _cropRegionInsets;	// 344 = 0x158
    struct CGRect _cropOriginFrame;	// 376 = 0x178
    struct CGRect _restoreImageCropFrame;	// 408 = 0x198
}

@property(nonatomic) struct CGRect restoreImageCropFrame; // @synthesize restoreImageCropFrame=_restoreImageCropFrame;
@property(nonatomic) long long restoreAngle; // @synthesize restoreAngle=_restoreAngle;
@property(nonatomic) _Bool dynamicBlurEffect; // @synthesize dynamicBlurEffect=_dynamicBlurEffect;
@property(nonatomic) struct CGPoint originalContentOffset; // @synthesize originalContentOffset=_originalContentOffset;
@property(nonatomic) struct CGSize originalCropBoxSize; // @synthesize originalCropBoxSize=_originalCropBoxSize;
@property(nonatomic) _Bool rotateAnimationInProgress; // @synthesize rotateAnimationInProgress=_rotateAnimationInProgress;
@property(nonatomic) double cropBoxLastEditedMinZoomScale; // @synthesize cropBoxLastEditedMinZoomScale=_cropBoxLastEditedMinZoomScale;
@property(nonatomic) double cropBoxLastEditedZoomScale; // @synthesize cropBoxLastEditedZoomScale=_cropBoxLastEditedZoomScale;
@property(nonatomic) long long cropBoxLastEditedAngle; // @synthesize cropBoxLastEditedAngle=_cropBoxLastEditedAngle;
@property(nonatomic) struct CGSize cropBoxLastEditedSize; // @synthesize cropBoxLastEditedSize=_cropBoxLastEditedSize;
@property(nonatomic) _Bool applyInitialRotatedAngle; // @synthesize applyInitialRotatedAngle=_applyInitialRotatedAngle;
@property(nonatomic) struct CGSize rotationBoundSize; // @synthesize rotationBoundSize=_rotationBoundSize;
@property(nonatomic) struct CGSize rotationContentSize; // @synthesize rotationContentSize=_rotationContentSize;
@property(nonatomic) struct CGPoint rotationContentOffset; // @synthesize rotationContentOffset=_rotationContentOffset;
@property(nonatomic) _Bool disableForgroundMatching; // @synthesize disableForgroundMatching=_disableForgroundMatching;
@property(nonatomic) _Bool editing; // @synthesize editing=_editing;
@property(retain, nonatomic) NSTimer *resetTimer; // @synthesize resetTimer=_resetTimer;
@property(nonatomic) struct CGPoint panOriginPoint; // @synthesize panOriginPoint=_panOriginPoint;
@property(nonatomic) struct CGRect cropOriginFrame; // @synthesize cropOriginFrame=_cropOriginFrame;
@property(nonatomic) long long tappedEdge; // @synthesize tappedEdge=_tappedEdge;
@property(nonatomic) _Bool applyInitialCroppedImageFrame; // @synthesize applyInitialCroppedImageFrame=_applyInitialCroppedImageFrame;
@property(retain, nonatomic) UIPanGestureRecognizer *gridPanGestureRecognizer; // @synthesize gridPanGestureRecognizer=_gridPanGestureRecognizer;
@property(retain, nonatomic) CAShapeLayer *circularMaskLayer; // @synthesize circularMaskLayer=_circularMaskLayer;
@property(retain, nonatomic) id translucencyEffect; // @synthesize translucencyEffect=_translucencyEffect;
@property(retain, nonatomic) UIView *translucencyView; // @synthesize translucencyView=_translucencyView;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *foregroundContainerView; // @synthesize foregroundContainerView=_foregroundContainerView;
@property(retain, nonatomic) UIImageView *foregroundImageView; // @synthesize foregroundImageView=_foregroundImageView;
@property(retain, nonatomic) UIView *backgroundContainerView; // @synthesize backgroundContainerView=_backgroundContainerView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) _Bool gridOverlayHidden; // @synthesize gridOverlayHidden=_gridOverlayHidden;
@property(nonatomic) _Bool croppingViewsHidden; // @synthesize croppingViewsHidden=_croppingViewsHidden;
@property(nonatomic) long long angle; // @synthesize angle=_angle;
@property(nonatomic) _Bool resetAspectRatioEnabled; // @synthesize resetAspectRatioEnabled=_resetAspectRatioEnabled;
@property(nonatomic) _Bool aspectRatioLockEnabled; // @synthesize aspectRatioLockEnabled=_aspectRatioLockEnabled;
@property(nonatomic) struct CGSize aspectRatio; // @synthesize aspectRatio=_aspectRatio;
@property(nonatomic) _Bool internalLayoutDisabled; // @synthesize internalLayoutDisabled=_internalLayoutDisabled;
@property(nonatomic) _Bool simpleRenderMode; // @synthesize simpleRenderMode=_simpleRenderMode;
@property(nonatomic) struct UIEdgeInsets cropRegionInsets; // @synthesize cropRegionInsets=_cropRegionInsets;
@property(nonatomic) struct CGRect cropBoxFrame; // @synthesize cropBoxFrame=_cropBoxFrame;
@property(nonatomic) _Bool canBeReset; // @synthesize canBeReset=_canBeReset;
@property(nonatomic) _Bool cropBoxResizeEnabled; // @synthesize cropBoxResizeEnabled=_cropBoxResizeEnabled;
@property(nonatomic) __weak id <AECropImageViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AECropOverlayView *gridOverlayView; // @synthesize gridOverlayView=_gridOverlayView;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;	// IMP=0x0000000100812204
@property(readonly, nonatomic) _Bool hasAspectRatio;
@property(readonly, nonatomic) struct CGSize imageSize;
@property(readonly, nonatomic) struct CGRect contentBounds;
- (void)checkForCanReset;	// IMP=0x00000001008115dc
- (void)captureStateForImageRotation;	// IMP=0x0000000100811518
- (void)rotateImageNinetyDegreesAnimated:(_Bool)arg1 clockwise:(_Bool)arg2;	// IMP=0x0000000100810448
- (void)rotateImageNinetyDegreesAnimated:(_Bool)arg1;	// IMP=0x0000000100810438
- (void)setAspectRatio:(struct CGSize)arg1 animated:(_Bool)arg2;	// IMP=0x000000010080ff3c
- (void)setSimpleRenderMode:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010080fe10
- (void)moveCroppedContentToCenterAnimated:(_Bool)arg1;	// IMP=0x000000010080f774
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010080f5a0
- (void)startEditing;	// IMP=0x000000010080f564
@property(readonly, nonatomic) struct CGRect imageViewFrame;
- (void)setGridOverlayHidden:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010080f138
- (void)setBackgroundImageViewHidden:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010080eeb4
- (void)setCroppingViewsHidden:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010080ec44
@property(nonatomic) struct CGRect imageCropFrame;
@property(readonly, nonatomic) _Bool cropBoxAspectRatioIsPortrait;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;	// IMP=0x000000010080e4a4
- (void)scrollViewDidZoom:(id)arg1;	// IMP=0x000000010080e418
- (void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(double)arg3;	// IMP=0x000000010080e3e4
- (void)scrollViewDidEndDecelerating:(id)arg1;	// IMP=0x000000010080e3b0
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;	// IMP=0x000000010080e378
- (void)scrollViewWillBeginDragging:(id)arg1;	// IMP=0x000000010080e340
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x000000010080e334
- (id)viewForZoomingInScrollView:(id)arg1;	// IMP=0x000000010080e328
- (long long)cropEdgeForPoint:(struct CGPoint)arg1;	// IMP=0x000000010080e0dc
- (void)cancelResetTimer;	// IMP=0x000000010080e084
- (void)timerTriggered;	// IMP=0x000000010080e014
- (void)startResetTimer;	// IMP=0x000000010080df78
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;	// IMP=0x000000010080df28
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x000000010080dd98
- (void)longPressGestureRecognized:(id)arg1;	// IMP=0x000000010080dcc8
- (void)gridPanGestureRecognized:(id)arg1;	// IMP=0x000000010080dba0
- (void)updateToImageCropFrame:(struct CGRect)arg1;	// IMP=0x000000010080d990
- (void)toggleTranslucencyViewVisible:(_Bool)arg1;	// IMP=0x000000010080d8bc
- (void)resetLayoutToDefaultAnimated:(_Bool)arg1;	// IMP=0x000000010080d3d8
- (void)updateCropBoxFrameWithGesturePoint:(struct CGPoint)arg1;	// IMP=0x000000010080c994
- (void)matchForegroundToBackground;	// IMP=0x000000010080c830
- (void)performRelayoutForRotation;	// IMP=0x000000010080c3b4
- (void)prepareforRotation;	// IMP=0x000000010080c2d4
- (void)layoutInitialImage;	// IMP=0x000000010080bdd0
- (void)didMoveToSuperview;	// IMP=0x000000010080bca8
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010080bc8c
- (void)setup;	// IMP=0x000000010080b048
- (id)initWithImage:(id)arg1;	// IMP=0x000000010080afac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

