//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AEDisputeIssueSubmitDTO : NSObject
{
    NSString *_subOrderId;	// 8 = 0x8
    NSString *_solutionType;	// 16 = 0x10
    NSString *_reasonId;	// 24 = 0x18
    NSString *_refundAmount;	// 32 = 0x20
    NSString *_requestDetail;	// 40 = 0x28
    NSString *_imageUrls;	// 48 = 0x30
    NSString *_isReceived;	// 56 = 0x38
    NSString *_videoIds;	// 64 = 0x40
    NSString *_videoCoverUrls;	// 72 = 0x48
}

@property(retain) NSString *videoCoverUrls; // @synthesize videoCoverUrls=_videoCoverUrls;
@property(retain) NSString *videoIds; // @synthesize videoIds=_videoIds;
@property(retain) NSString *isReceived; // @synthesize isReceived=_isReceived;
@property(retain) NSString *imageUrls; // @synthesize imageUrls=_imageUrls;
@property(retain) NSString *requestDetail; // @synthesize requestDetail=_requestDetail;
@property(retain) NSString *refundAmount; // @synthesize refundAmount=_refundAmount;
@property(retain) NSString *reasonId; // @synthesize reasonId=_reasonId;
@property(retain) NSString *solutionType; // @synthesize solutionType=_solutionType;
@property(retain) NSString *subOrderId; // @synthesize subOrderId=_subOrderId;
- (void).cxx_destruct;	// IMP=0x00000001000887cc

@end

