//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "AEDisputeTableViewCellProtocol.h"

@class NSString, UILabel;

@interface AEDisputeDetailNormalCell : UITableViewCell <AEDisputeTableViewCellProtocol>
{
    UILabel *_leftLabel;	// 8 = 0x8
}

@property(retain, nonatomic) UILabel *leftLabel; // @synthesize leftLabel=_leftLabel;
- (void).cxx_destruct;	// IMP=0x0000000100061a70
- (void)bindData:(id)arg1;	// IMP=0x00000001000618a8
- (void)privateLayoutSubviews;	// IMP=0x0000000100060f58
- (void)addSubViews;	// IMP=0x0000000100060ee8
- (id)initWithIdentifier:(id)arg1;	// IMP=0x0000000100060da4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

