//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

@class DisputeEditService, NSMutableArray, NSString, UIButton, UILabel, UIScrollView, UIView;

@interface AEDisputeEditBaseVC : AEUIViewController
{
    UIScrollView *_scrollView;	// 8 = 0x8
    UIView *_contentView;	// 16 = 0x10
    UILabel *_descriptionLbl;	// 24 = 0x18
    NSString *_descriptionText;	// 32 = 0x20
    NSString *_issueId;	// 40 = 0x28
    DisputeEditService *_service;	// 48 = 0x30
    UIButton *_submitButton;	// 56 = 0x38
    UIButton *_cancelButton;	// 64 = 0x40
    NSMutableArray *_components;	// 72 = 0x48
}

+ (id)findFirstResponder:(id)arg1;	// IMP=0x0000000100087e94
@property(retain, nonatomic) NSMutableArray *components; // @synthesize components=_components;
@property(retain) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain) UIButton *submitButton; // @synthesize submitButton=_submitButton;
@property(retain) DisputeEditService *service; // @synthesize service=_service;
@property(retain) NSString *issueId; // @synthesize issueId=_issueId;
@property(retain) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
- (void).cxx_destruct;	// IMP=0x00000001000880ec
- (void)postSuccNotification;	// IMP=0x0000000100087e40
- (void)onSubmit;	// IMP=0x0000000100087e3c
- (void)onCancel;	// IMP=0x0000000100087df4
- (_Bool)checkValidate;	// IMP=0x0000000100087c50
- (void)reloadComponents;	// IMP=0x0000000100087ad4
- (void)layoutActionButtons;	// IMP=0x0000000100086f24
- (void)layoutComponents;	// IMP=0x0000000100086994
- (id)getComponents;	// IMP=0x000000010008698c
- (id)showMode;	// IMP=0x0000000100086960
- (id)getPreText;	// IMP=0x0000000100086958
- (void)layoutDescriptionText;	// IMP=0x00000001000864c0
- (void)viewDidLoad;	// IMP=0x0000000100085dac
- (id)initWithIssueId:(id)arg1;	// IMP=0x0000000100085ce8

@end

