//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, UIViewController;

@interface AEDisputeHistoryVM : NSObject
{
    NSMutableArray *_disputeComponents;	// 8 = 0x8
    UIViewController *_currentViewController;	// 16 = 0x10
}

@property(nonatomic) __weak UIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(retain, nonatomic) NSMutableArray *disputeComponents; // @synthesize disputeComponents=_disputeComponents;
- (void).cxx_destruct;	// IMP=0x0000000100093bfc
- (void)registerComponentsWithComponent:(id)arg1;	// IMP=0x0000000100093abc
- (void)handlerImageClickWithImageItem:(id)arg1;	// IMP=0x0000000100093748
- (void)handlerVideoClick;	// IMP=0x00000001000935bc
- (void)requestDisputeHistoryWithDisputeId:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100093024
- (id)initDisputeHistoryVMWithViewController:(id)arg1;	// IMP=0x0000000100092f60

@end

