//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage, UIView;

@interface AEEmptyViewConfiguration : NSObject
{
    UIImage *_image;	// 8 = 0x8
    NSString *_describes;	// 16 = 0x10
    NSString *_buttonTitle;	// 24 = 0x18
    CDUnknownBlockType _action;	// 32 = 0x20
    double _yOffSet;	// 40 = 0x28
    UIView *_extraView;	// 48 = 0x30
    double _heightRatio;	// 56 = 0x38
}

@property(nonatomic) double heightRatio; // @synthesize heightRatio=_heightRatio;
@property(retain, nonatomic) UIView *extraView; // @synthesize extraView=_extraView;
@property(nonatomic) double yOffSet; // @synthesize yOffSet=_yOffSet;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
@property(retain, nonatomic) NSString *describes; // @synthesize describes=_describes;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;	// IMP=0x0000000100817d30

@end

