//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface AEExpandedButton : UIButton
{
    struct UIEdgeInsets _insets;	// 8 = 0x8
}

@property(nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x000000010081a030
- (id)initWithExpandedInsets:(struct UIEdgeInsets)arg1;	// IMP=0x000000010081a004
- (id)initWithFrame:(struct CGRect)arg1 expandedInsets:(struct UIEdgeInsets)arg2;	// IMP=0x0000000100819f98

@end

