//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

#import "AFViewHierarchyContainerProtocol.h"

@class NSString, UIViewController;

@interface AEFakeViewController : AEUIViewController <AFViewHierarchyContainerProtocol>
{
    UIViewController *_contentViewController;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100a46480
- (_Bool)isNeedDisplayTabbar;	// IMP=0x0000000100a46478
- (id)primaryContentViewController;	// IMP=0x0000000100a46468
- (id)initWithContentViewController:(id)arg1;	// IMP=0x0000000100a4608c
- (void)viewDidLoad;	// IMP=0x0000000100a46038
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100a45fc0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100a45f48

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

