//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel;

@interface AEFeedbackFinishCell : UITableViewCell
{
    _Bool _isFollowup;	// 8 = 0x8
    UIImageView *_itemImageView;	// 16 = 0x10
    UILabel *_titleLabel;	// 24 = 0x18
    UIButton *_feedbackBt;	// 32 = 0x20
}

@property(retain, nonatomic) UIButton *feedbackBt; // @synthesize feedbackBt=_feedbackBt;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *itemImageView; // @synthesize itemImageView=_itemImageView;
@property(nonatomic) _Bool isFollowup; // @synthesize isFollowup=_isFollowup;
- (void).cxx_destruct;	// IMP=0x00000001000da3e8
- (void)bindData4Followup:(id)arg1;	// IMP=0x00000001000da128
- (void)bindData:(id)arg1;	// IMP=0x00000001000d9f60
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001000d8cec

@end

