//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AETextTileComponent, NSArray;

@interface AEFlashDealsSegmentViewModel : NSObject
{
    AETextTileComponent *_titleVM;	// 8 = 0x8
    NSArray *_productVMs;	// 16 = 0x10
}

@property(retain, nonatomic) NSArray *productVMs; // @synthesize productVMs=_productVMs;
@property(retain, nonatomic) AETextTileComponent *titleVM; // @synthesize titleVM=_titleVM;
- (void).cxx_destruct;	// IMP=0x0000000100304024

@end

