//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AETileAdapterFloor.h"

@class CALayer, UILabel;

@interface AEFloorSplitTitle : AETileAdapterFloor
{
    UILabel *_titleLabel;	// 8 = 0x8
    CALayer *_leftLine;	// 16 = 0x10
    CALayer *_rightLine;	// 24 = 0x18
}

+ (Class)modelClass;	// IMP=0x0000000100377314
+ (id)additionalIdentifiers;	// IMP=0x00000001003772c8
+ (id)identifier;	// IMP=0x000000010037729c
@property(retain, nonatomic) CALayer *rightLine; // @synthesize rightLine=_rightLine;
@property(retain, nonatomic) CALayer *leftLine; // @synthesize leftLine=_leftLine;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;	// IMP=0x0000000100377d44
- (_Bool)renderWithTile:(id)arg1;	// IMP=0x0000000100377ab4
- (void)prepareForReuse;	// IMP=0x0000000100377a98
- (void)layoutSubviews;	// IMP=0x0000000100377870
- (void)setupConstraints;	// IMP=0x000000010037766c
- (id)initFloor;	// IMP=0x0000000100377328

@end

