//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AETileAdapterFloor.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface AEFloorStoreSign : AETileAdapterFloor
{
    UIImageView *_storeIV;	// 8 = 0x8
    UIView *_dummyView1;	// 16 = 0x10
    UILabel *_storeNameLbl;	// 24 = 0x18
    UIImageView *_storeLevelView;	// 32 = 0x20
    UILabel *_positiveFeedbackRateLbl;	// 40 = 0x28
    UIImageView *_topBrandsImg;	// 48 = 0x30
    UILabel *_topBrandsLabel;	// 56 = 0x38
    UIButton *_shareBtn;	// 64 = 0x40
    double _storeIVWidthHeightRatio;	// 72 = 0x48
    UIView *_bottomLine;	// 80 = 0x50
}

+ (Class)modelClass;	// IMP=0x0000000100d553c4
+ (id)identifier;	// IMP=0x0000000100d55398
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(nonatomic) double storeIVWidthHeightRatio; // @synthesize storeIVWidthHeightRatio=_storeIVWidthHeightRatio;
@property(retain, nonatomic) UIButton *shareBtn; // @synthesize shareBtn=_shareBtn;
@property(retain, nonatomic) UILabel *topBrandsLabel; // @synthesize topBrandsLabel=_topBrandsLabel;
@property(retain, nonatomic) UIImageView *topBrandsImg; // @synthesize topBrandsImg=_topBrandsImg;
@property(retain, nonatomic) UILabel *positiveFeedbackRateLbl; // @synthesize positiveFeedbackRateLbl=_positiveFeedbackRateLbl;
@property(retain, nonatomic) UIImageView *storeLevelView; // @synthesize storeLevelView=_storeLevelView;
@property(retain, nonatomic) UILabel *storeNameLbl; // @synthesize storeNameLbl=_storeNameLbl;
@property(retain, nonatomic) UIView *dummyView1; // @synthesize dummyView1=_dummyView1;
@property(retain, nonatomic) UIImageView *storeIV; // @synthesize storeIV=_storeIV;
- (void).cxx_destruct;	// IMP=0x0000000100d5b104
- (void)setContentOffset:(struct CGPoint)arg1;	// IMP=0x0000000100d5aa90
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x0000000100d5aa58
- (_Bool)needObserveCollectionViewScrollState;	// IMP=0x0000000100d5aa50
- (_Bool)renderWithTile:(id)arg1;	// IMP=0x0000000100d58678
- (void)shareEvent:(id)arg1;	// IMP=0x0000000100d583b4
- (id)captureScreen;	// IMP=0x0000000100d58288
- (void)configConstraints;	// IMP=0x0000000100d55ff8
- (void)configComponents;	// IMP=0x0000000100d55e00
- (id)initFloor;	// IMP=0x0000000100d553d8

@end

