//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AETileAdapterFloor.h"

@class UIImageView, UILabel;

@interface AEFloorTimelineSingleText : AETileAdapterFloor
{
    UILabel *_subject;	// 8 = 0x8
    UIImageView *_backgroundImage;	// 16 = 0x10
}

+ (Class)modelClass;	// IMP=0x0000000100387a64
+ (id)identifier;	// IMP=0x0000000100387a38
+ (id)floorDescription;	// IMP=0x0000000100387a0c
@property(retain, nonatomic) UIImageView *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UILabel *subject; // @synthesize subject=_subject;
- (void).cxx_destruct;	// IMP=0x0000000100388aac
- (_Bool)renderWithTile:(id)arg1;	// IMP=0x000000010038860c
- (void)updateConstraints;	// IMP=0x0000000100387d18
- (void)configComponents;	// IMP=0x0000000100387ad0
- (id)initFloor;	// IMP=0x0000000100387a78

@end

