//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTile.h"

@class AEComponent3Products1RowViewModel, AEComponentStoreViewModel, AETextTileComponent;

@interface AEFloorVenueStoreProductsViewModel : AEBaseTile
{
    AEComponentStoreViewModel *_storeModel;	// 8 = 0x8
    AEComponent3Products1RowViewModel *_productsModel;	// 16 = 0x10
    AETextTileComponent *_viewMoreModel;	// 24 = 0x18
}

+ (Class)cellClass;	// IMP=0x00000001003a9ee4
@property(retain, nonatomic) AETextTileComponent *viewMoreModel; // @synthesize viewMoreModel=_viewMoreModel;
@property(retain, nonatomic) AEComponent3Products1RowViewModel *productsModel; // @synthesize productsModel=_productsModel;
@property(retain, nonatomic) AEComponentStoreViewModel *storeModel; // @synthesize storeModel=_storeModel;
- (void).cxx_destruct;	// IMP=0x00000001003a9d70
- (id)initWithTileDTO:(id)arg1;	// IMP=0x00000001003a9f04

@end

