//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTile.h"

@class AEComponentCoinsSimpleProductViewModel;

@interface AEFloorCoinsSimpleProductViewModel : AEBaseTile
{
    AEComponentCoinsSimpleProductViewModel *_simpleProductModel;	// 8 = 0x8
}

+ (Class)cellClass;	// IMP=0x000000010032a2d8
@property(retain, nonatomic) AEComponentCoinsSimpleProductViewModel *simpleProductModel; // @synthesize simpleProductModel=_simpleProductModel;
- (void).cxx_destruct;	// IMP=0x000000010032a1a4
- (double)heightForReferenceWidth:(double)arg1;	// IMP=0x000000010032a100
- (id)initWithTileDTO:(id)arg1;	// IMP=0x0000000100329fbc

@end

