//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseStackTileView.h"

@class AETileAdapterFloor;

@interface AEFloorSlideDownMenuAdapterTail : AEBaseStackTileView
{
    AETileAdapterFloor *_adapterFloor;	// 8 = 0x8
}

@property(retain, nonatomic) AETileAdapterFloor *adapterFloor; // @synthesize adapterFloor=_adapterFloor;
- (void).cxx_destruct;	// IMP=0x0000000100376dc0
- (void)prepareForReuse;	// IMP=0x0000000100376d44
- (void)renderWithTile:(id)arg1;	// IMP=0x0000000100376c60
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100376b54

@end

