//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTile.h"

@class AEComponentTitleViewModel;

@interface AEFloorTitleArrowViewModel : AEBaseTile
{
    AEComponentTitleViewModel *_componentViewModel;	// 8 = 0x8
}

+ (Class)cellClass;	// IMP=0x000000010038df20
@property(retain, nonatomic) AEComponentTitleViewModel *componentViewModel; // @synthesize componentViewModel=_componentViewModel;
- (void).cxx_destruct;	// IMP=0x000000010038ddec
- (double)heightForReferenceWidth:(double)arg1;	// IMP=0x000000010038dd98
- (id)init;	// IMP=0x000000010038dd18

@end

