//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTile.h"

@class NSString;

@interface AEFloorStoreImageViewModel : AEBaseTile
{
    NSString *_imageURL;	// 8 = 0x8
    NSString *_action;	// 16 = 0x10
    double _widthHeightRatio;	// 24 = 0x18
}

+ (Class)cellClass;	// IMP=0x0000000100d04478
@property(nonatomic) double widthHeightRatio; // @synthesize widthHeightRatio=_widthHeightRatio;
@property(retain, nonatomic) NSString *action; // @synthesize action=_action;
@property(retain, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;	// IMP=0x0000000100d04314
- (double)heightForReferenceWidth:(double)arg1;	// IMP=0x0000000100d04280
- (double)getWidthHeightRatio:(id)arg1;	// IMP=0x0000000100d040e8
- (id)initWithTileDTO:(id)arg1;	// IMP=0x0000000100d03e24

@end

