//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTile.h"

@class AEImageTileComponent, AETextTileComponent, NSNumber, NSString;

@interface AEFloorBuyerPicksItemViewModel : AEBaseTile
{
    AEImageTileComponent *_photo;	// 8 = 0x8
    AETextTileComponent *_mainTitle;	// 16 = 0x10
    AETextTileComponent *_subTitle;	// 24 = 0x18
    NSNumber *_rating;	// 32 = 0x20
    NSString *_hintText;	// 40 = 0x28
}

+ (Class)cellClass;	// IMP=0x00000001003137ec
@property(retain, nonatomic) NSString *hintText; // @synthesize hintText=_hintText;
@property(retain, nonatomic) NSNumber *rating; // @synthesize rating=_rating;
@property(retain, nonatomic) AETextTileComponent *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) AETextTileComponent *mainTitle; // @synthesize mainTitle=_mainTitle;
@property(retain, nonatomic) AEImageTileComponent *photo; // @synthesize photo=_photo;
- (void).cxx_destruct;	// IMP=0x0000000100313650
- (id)initWithTileDTO:(id)arg1;	// IMP=0x00000001003130a4

@end

