//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AETileAdapterFloor.h"

@class UIImageView, UILabel;

@interface AEFloorVenueTopBrand : AETileAdapterFloor
{
    UIImageView *_imageView;	// 8 = 0x8
    UIImageView *_logoIV;	// 16 = 0x10
    UILabel *_titleLbl;	// 24 = 0x18
}

+ (Class)modelClass;	// IMP=0x00000001003ad794
+ (id)identifier;	// IMP=0x00000001003ad768
- (void).cxx_destruct;	// IMP=0x00000001003ae574
- (_Bool)renderWithTile:(id)arg1;	// IMP=0x00000001003ae42c
- (void)prepareForReuse;	// IMP=0x00000001003ae410
- (void)configConstraints;	// IMP=0x00000001003adbd4
- (void)configComponents;	// IMP=0x00000001003ad9ac
- (id)initFloor;	// IMP=0x00000001003ad7a8

@end

