//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFNotificationTask.h"

@interface AEInitFBSDK : AFNotificationTask
{
}

+ (void)runWithNotification:(id)arg1;	// IMP=0x0000000100a62fa0
+ (unsigned long long)triggerEvent;	// IMP=0x0000000100a62f98
+ (unsigned long long)priority;	// IMP=0x0000000100a62f90
+ (void)load;	// IMP=0x0000000100a62f68

@end

