//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "TTTAttributedLabelDelegate.h"

@class AELogisticsInnerPackage, LogisticPackage, NSString, TTTAttributedLabel, UIButton, UILabel;

@interface AELogisticsPackageStatusCell : UITableViewCell <TTTAttributedLabelDelegate>
{
    AELogisticsInnerPackage *_innerPackage;	// 8 = 0x8
    UILabel *_packageStatusLabel;	// 16 = 0x10
    TTTAttributedLabel *_carierInfoLabel;	// 24 = 0x18
    UILabel *_trackingNumberLabel;	// 32 = 0x20
    UIButton *_copyBtn;	// 40 = 0x28
    LogisticPackage *_package;	// 48 = 0x30
}

@property(retain, nonatomic) LogisticPackage *package; // @synthesize package=_package;
@property(retain, nonatomic) UIButton *copyBtn; // @synthesize copyBtn=_copyBtn;
@property(retain, nonatomic) UILabel *trackingNumberLabel; // @synthesize trackingNumberLabel=_trackingNumberLabel;
@property(retain, nonatomic) TTTAttributedLabel *carierInfoLabel; // @synthesize carierInfoLabel=_carierInfoLabel;
@property(retain, nonatomic) UILabel *packageStatusLabel; // @synthesize packageStatusLabel=_packageStatusLabel;
@property(retain, nonatomic) AELogisticsInnerPackage *innerPackage; // @synthesize innerPackage=_innerPackage;
- (void).cxx_destruct;	// IMP=0x0000000100132604
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;	// IMP=0x0000000100132434
- (void)bindData:(id)arg1;	// IMP=0x0000000100131cec
- (void)prepareForReuse;	// IMP=0x0000000100131c08
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100131bd4
- (void)awakeFromNib;	// IMP=0x0000000100131ba0
- (void)copyAction:(id)arg1;	// IMP=0x0000000100131a04
- (void)copy:(id)arg1;	// IMP=0x00000001001319f8
- (_Bool)canBecomeFirstResponder;	// IMP=0x00000001001319f0
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;	// IMP=0x00000001001319dc
- (void)longPressTrackingNumber:(id)arg1;	// IMP=0x00000001001318a8
- (void)setupConstraints;	// IMP=0x0000000100130408
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x000000010012fc64

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

