//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class AEStandardMailingAddressView, UILabel;

@interface AELogisticsShipCell : UITableViewCell
{
    UILabel *_shipLabel;	// 8 = 0x8
    AEStandardMailingAddressView *_addressView;	// 16 = 0x10
}

@property(retain, nonatomic) AEStandardMailingAddressView *addressView; // @synthesize addressView=_addressView;
@property(retain, nonatomic) UILabel *shipLabel; // @synthesize shipLabel=_shipLabel;
- (void).cxx_destruct;	// IMP=0x0000000100135964
- (void)bindData:(id)arg1;	// IMP=0x0000000100134f58
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100134f24
- (void)awakeFromNib;	// IMP=0x0000000100134ef0
- (void)setupConstraints;	// IMP=0x0000000100134a58
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100134768

@end

