//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AEMemberLevelItemListItemM : NSObject
{
    NSString *_levelContent;	// 8 = 0x8
    NSString *_levelPointMcmsKey;	// 16 = 0x10
    NSString *_levelContentMcmsKey;	// 24 = 0x18
    NSString *_levelIconUrl;	// 32 = 0x20
    NSString *_levelPoint;	// 40 = 0x28
    NSString *_levelIconUrlMcmsKey;	// 48 = 0x30
}

@property(copy, nonatomic) NSString *levelIconUrlMcmsKey; // @synthesize levelIconUrlMcmsKey=_levelIconUrlMcmsKey;
@property(copy, nonatomic) NSString *levelPoint; // @synthesize levelPoint=_levelPoint;
@property(copy, nonatomic) NSString *levelIconUrl; // @synthesize levelIconUrl=_levelIconUrl;
@property(copy, nonatomic) NSString *levelContentMcmsKey; // @synthesize levelContentMcmsKey=_levelContentMcmsKey;
@property(copy, nonatomic) NSString *levelPointMcmsKey; // @synthesize levelPointMcmsKey=_levelPointMcmsKey;
@property(copy, nonatomic) NSString *levelContent; // @synthesize levelContent=_levelContent;
- (void).cxx_destruct;	// IMP=0x00000001001b4e78

@end

