//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AEMemberCenterHandler : NSObject
{
}

+ (_Bool)isMyAEShowMemberCenter;	// IMP=0x000000010013e48c
+ (_Bool)isShowNewMemberCenter;	// IMP=0x000000010013e3f0
+ (id)getEntranceArray;	// IMP=0x000000010013e29c

@end

