//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AEMessageCountService : NSObject
{
    id <AEMessageCountDelegate> _delegate;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010015acf0
- (void)requestUnreadMsg:(CDUnknownBlockType)arg1;	// IMP=0x000000010015a9d8
- (void)getUnreadMsgCount;	// IMP=0x000000010015a6bc
- (id)initWithDelegate:(id)arg1;	// IMP=0x000000010015a644

@end

