//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UIView;

@interface AEModuleTreeRankViewMoreCell : UITableViewCell
{
    UIView *_viewCellBg;	// 8 = 0x8
    UIView *_viewBg;	// 16 = 0x10
    UILabel *_labelMore;	// 24 = 0x18
}

@property(retain, nonatomic) UILabel *labelMore; // @synthesize labelMore=_labelMore;
@property(retain, nonatomic) UIView *viewBg; // @synthesize viewBg=_viewBg;
@property(retain, nonatomic) UIView *viewCellBg; // @synthesize viewCellBg=_viewCellBg;
- (void).cxx_destruct;	// IMP=0x0000000100b1ad2c
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100b1a8d4
- (void)awakeFromNib;	// IMP=0x0000000100b1a8a0
- (void)initView;	// IMP=0x0000000100b1a0e4
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100b1a08c

@end

