//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AFModule.h"

@class NSString;

@interface AEModuleUGCPostDetail : NSObject <AFModule>
{
}

- (void)reboot;	// IMP=0x00000001006ce464
- (void)boot;	// IMP=0x00000001006ce1cc
- (id)version;	// IMP=0x00000001006ce1a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

