//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEMyRewardPointsBaseSectionHeaderVM.h"

@class NSString;

@interface AEMyRewardPointsLevelSectionHeaderVM : AEMyRewardPointsBaseSectionHeaderVM
{
    NSString *_title;	// 8 = 0x8
    NSString *_level;	// 16 = 0x10
    NSString *_points;	// 24 = 0x18
}

+ (id)viewModelWithModel:(id)arg1;	// IMP=0x00000001001bdab0
@property(copy, nonatomic) NSString *points; // @synthesize points=_points;
@property(copy, nonatomic) NSString *level; // @synthesize level=_level;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;	// IMP=0x00000001001bdc70

@end

