//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

#import "AEHDDialogPopoverDelegate.h"
#import "AEShippingInfoViewControllerCallback.h"
#import "AESkuChooseViewDelegate.h"
#import "AESkuPriceViewDelegate.h"

@class AEProductDetailOrderButtonPanel, AESKUQuantityView, AEShippingInfoViewController, AESkuChooseView, AESkuInfoParameter, AESkuPriceView, AESkuService, AESkuSingleLableView, NSDictionary, NSString, UIScrollView;

@interface AENewSkuViewController : AEUIViewController <AESkuPriceViewDelegate, AEHDDialogPopoverDelegate, AESkuChooseViewDelegate, AEShippingInfoViewControllerCallback>
{
    CDUnknownBlockType _completion;	// 8 = 0x8
    CDUnknownBlockType _customOrderBlock;	// 16 = 0x10
    AESkuInfoParameter *_skuInfoParameter;	// 24 = 0x18
    CDUnknownBlockType _resultBlock;	// 32 = 0x20
    UIScrollView *_contentScrollView;	// 40 = 0x28
    AESkuPriceView *_skuPriceView;	// 48 = 0x30
    AESkuChooseView *_skuChooseView;	// 56 = 0x38
    AESkuSingleLableView *_afterSaleServiceView;	// 64 = 0x40
    AESKUQuantityView *_skuQuantityView;	// 72 = 0x48
    AESkuSingleLableView *_shippingView;	// 80 = 0x50
    AEProductDetailOrderButtonPanel *_actionView;	// 88 = 0x58
    NSString *_skuString;	// 96 = 0x60
    long long _quantity;	// 104 = 0x68
    NSString *_countryCode;	// 112 = 0x70
    NSDictionary *_skuMap;	// 120 = 0x78
    AESkuService *_skuService;	// 128 = 0x80
    AEShippingInfoViewController *_shippingInfoVC;	// 136 = 0x88
    double _pushUp;	// 144 = 0x90
    NSDictionary *_shellParams;	// 152 = 0x98
}

@property(retain, nonatomic) NSDictionary *shellParams; // @synthesize shellParams=_shellParams;
@property(nonatomic) double pushUp; // @synthesize pushUp=_pushUp;
@property(retain, nonatomic) AEShippingInfoViewController *shippingInfoVC; // @synthesize shippingInfoVC=_shippingInfoVC;
@property(retain, nonatomic) AESkuService *skuService; // @synthesize skuService=_skuService;
@property(retain, nonatomic) NSDictionary *skuMap; // @synthesize skuMap=_skuMap;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(nonatomic) long long quantity; // @synthesize quantity=_quantity;
@property(retain, nonatomic) NSString *skuString; // @synthesize skuString=_skuString;
@property(retain, nonatomic) AEProductDetailOrderButtonPanel *actionView; // @synthesize actionView=_actionView;
@property(retain, nonatomic) AESkuSingleLableView *shippingView; // @synthesize shippingView=_shippingView;
@property(retain, nonatomic) AESKUQuantityView *skuQuantityView; // @synthesize skuQuantityView=_skuQuantityView;
@property(retain, nonatomic) AESkuSingleLableView *afterSaleServiceView; // @synthesize afterSaleServiceView=_afterSaleServiceView;
@property(retain, nonatomic) AESkuChooseView *skuChooseView; // @synthesize skuChooseView=_skuChooseView;
@property(retain, nonatomic) AESkuPriceView *skuPriceView; // @synthesize skuPriceView=_skuPriceView;
@property(retain, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
@property(copy, nonatomic) CDUnknownBlockType resultBlock; // @synthesize resultBlock=_resultBlock;
@property(retain, nonatomic) AESkuInfoParameter *skuInfoParameter; // @synthesize skuInfoParameter=_skuInfoParameter;
@property(copy, nonatomic) CDUnknownBlockType customOrderBlock; // @synthesize customOrderBlock=_customOrderBlock;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;	// IMP=0x000000010054c3dc
- (void)afterDismissInPopOverWhenTapOut;	// IMP=0x000000010054bf94
- (id)getShippingInfoVCWithEveryRequestCallBack:(_Bool)arg1;	// IMP=0x000000010054be30
- (_Bool)prepareData4Action;	// IMP=0x000000010054b894
- (void)shippingInfoViewControllerCallbackWithParameter:(id)arg1;	// IMP=0x000000010054b6d0
- (void)refreshDisplayImage:(id)arg1;	// IMP=0x000000010054b664
- (void)countrySelect:(id)arg1;	// IMP=0x000000010054b418
- (void)productDetailSkuView:(id)arg1 skuPropertyChoosed:(id)arg2;	// IMP=0x000000010054b304
- (void)productImageClicked;	// IMP=0x000000010054b0a8
- (void)reload;	// IMP=0x000000010054adc0
- (void)trackSkuInfo;	// IMP=0x000000010054adbc
- (void)cartAction;	// IMP=0x000000010054aa84
- (void)orderAction;	// IMP=0x0000000100549ff4
- (void)adjustProductDetailOrderButtonPanelVM:(id)arg1;	// IMP=0x0000000100549a14
- (void)refreshActionView;	// IMP=0x0000000100549974
- (void)buildActionView;	// IMP=0x00000001005498e4
- (void)refreshShippingView;	// IMP=0x00000001005496ec
- (void)buildShippingView;	// IMP=0x0000000100549490
- (void)refreshQuantityView;	// IMP=0x0000000100549328
- (void)buildQuantityView;	// IMP=0x0000000100548ef8
- (void)buildSKUChooseView;	// IMP=0x0000000100548db8
- (void)refreshPriceView;	// IMP=0x0000000100548d0c
- (void)buildPriceView;	// IMP=0x0000000100548c1c
- (void)buildScrollView;	// IMP=0x0000000100548b34
- (void)buildNavigationItem;	// IMP=0x0000000100548940
- (void)bindData;	// IMP=0x000000010054876c
- (void)buildLayout;	// IMP=0x00000001005476e4
- (void)buildUI;	// IMP=0x000000010054758c
- (void)requestShippingInfo;	// IMP=0x0000000100547548
- (void)requestRequiredData;	// IMP=0x0000000100547254
- (void)requestSkuPriceList;	// IMP=0x0000000100546e24
- (id)pageTrackName;	// IMP=0x0000000100546df8
- (void)dealloc;	// IMP=0x0000000100546d7c
- (void)dismissWithSkuInfoComplete;	// IMP=0x0000000100546c30
- (void)done;	// IMP=0x0000000100546b60
- (void)cancel;	// IMP=0x0000000100546b18
- (void)getSkuData;	// IMP=0x0000000100546ae4
- (void)viewDidLoad;	// IMP=0x00000001005469bc
- (void)buildSkuInfoParameterAfterProductDetailReceived:(id)arg1;	// IMP=0x000000010054631c
- (id)initWithShellParmas:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100545f58
- (id)initWithSkuInfoParameter:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100545e20

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

