//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AENewProductDetailViewModel, AEProductDetailHeaderViewModel, AEProductDetailOrderButtonPanelVM, AIFExposureManager, NSArray, NSError, NSString, NSURL;

@protocol AENewProductDetailViewModelDelegate <NSObject>
- (AIFExposureManager *)exposureManagerForModel:(AENewProductDetailViewModel *)arg1;
- (id <AFUIPresenter>)presenterForModel:(AENewProductDetailViewModel *)arg1;
- (void)productDetailViewModel:(AENewProductDetailViewModel *)arg1 productAddedToCart:(_Bool)arg2;
- (void)productDetailViewModel:(AENewProductDetailViewModel *)arg1 activeHandoff:(NSURL *)arg2;
- (void)productDetailViewModel:(AENewProductDetailViewModel *)arg1 sectionViewModelError:(NSError *)arg2;
- (void)productDetailViewModel:(AENewProductDetailViewModel *)arg1 sectionViewModel404:(NSArray *)arg2 forReason:(NSString *)arg3;
- (void)productDetailViewModel:(AENewProductDetailViewModel *)arg1 sectionViewModel403:(NSArray *)arg2 headerViewModel:(AEProductDetailHeaderViewModel *)arg3;
- (void)productDetailViewModel:(AENewProductDetailViewModel *)arg1 sectionViewModelDidChange:(NSArray *)arg2 ipadLeftSectionViewModel:(NSArray *)arg3 headerViewModel:(AEProductDetailHeaderViewModel *)arg4 bottomOrderPanelViewModel:(AEProductDetailOrderButtonPanelVM *)arg5;
@end

