//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AEOrderStatusNum : NSObject
{
    NSString *_aeWaitPaymentOrders;	// 8 = 0x8
    NSString *_aeWaitSellerSendGoodsOrders;	// 16 = 0x10
    NSString *_aeWaitBuyerAcceptGoodsOrders;	// 24 = 0x18
    NSString *_aeWaitBuyerFeedbackOrders;	// 32 = 0x20
    NSString *_aeUnconfirmedPaymentOrders;	// 40 = 0x28
    NSString *_aeFrozenOrders;	// 48 = 0x30
    NSString *_aeVerifyingOrders;	// 56 = 0x38
    NSString *_aeInCancelOrders;	// 64 = 0x40
    NSString *_aePartSendGoodsOrders;	// 72 = 0x48
    NSString *_aeIssueOrders;	// 80 = 0x50
    NSString *_aeCompletedOrders;	// 88 = 0x58
    NSString *_aeGroupOrders;	// 96 = 0x60
}

@property(copy, nonatomic) NSString *aeGroupOrders; // @synthesize aeGroupOrders=_aeGroupOrders;
@property(copy, nonatomic) NSString *aeCompletedOrders; // @synthesize aeCompletedOrders=_aeCompletedOrders;
@property(copy, nonatomic) NSString *aeIssueOrders; // @synthesize aeIssueOrders=_aeIssueOrders;
@property(copy, nonatomic) NSString *aePartSendGoodsOrders; // @synthesize aePartSendGoodsOrders=_aePartSendGoodsOrders;
@property(copy, nonatomic) NSString *aeInCancelOrders; // @synthesize aeInCancelOrders=_aeInCancelOrders;
@property(copy, nonatomic) NSString *aeVerifyingOrders; // @synthesize aeVerifyingOrders=_aeVerifyingOrders;
@property(copy, nonatomic) NSString *aeFrozenOrders; // @synthesize aeFrozenOrders=_aeFrozenOrders;
@property(copy, nonatomic) NSString *aeUnconfirmedPaymentOrders; // @synthesize aeUnconfirmedPaymentOrders=_aeUnconfirmedPaymentOrders;
@property(copy, nonatomic) NSString *aeWaitBuyerFeedbackOrders; // @synthesize aeWaitBuyerFeedbackOrders=_aeWaitBuyerFeedbackOrders;
@property(copy, nonatomic) NSString *aeWaitBuyerAcceptGoodsOrders; // @synthesize aeWaitBuyerAcceptGoodsOrders=_aeWaitBuyerAcceptGoodsOrders;
@property(copy, nonatomic) NSString *aeWaitSellerSendGoodsOrders; // @synthesize aeWaitSellerSendGoodsOrders=_aeWaitSellerSendGoodsOrders;
@property(copy, nonatomic) NSString *aeWaitPaymentOrders; // @synthesize aeWaitPaymentOrders=_aeWaitPaymentOrders;
- (void).cxx_destruct;	// IMP=0x00000001001f8a24
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001f8590
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001001f8274
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001f7f88

@end

