//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AEOrderListModel, NSMutableArray, NSString, UITableView;

@interface AEOrderFilterVC : AEUIViewController <UITableViewDelegate, UITableViewDataSource>
{
    int _orderFilterType;	// 8 = 0x8
    UITableView *__tableView;	// 16 = 0x10
    NSMutableArray *_dataSource;	// 24 = 0x18
    AEOrderListModel *_orderListModel;	// 32 = 0x20
    id _delegate;	// 40 = 0x28
    NSString *_orderStatus;	// 48 = 0x30
    NSString *_timeFilterStatus;	// 56 = 0x38
}

@property(copy, nonatomic) NSString *timeFilterStatus; // @synthesize timeFilterStatus=_timeFilterStatus;
@property(copy, nonatomic) NSString *orderStatus; // @synthesize orderStatus=_orderStatus;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AEOrderListModel *orderListModel; // @synthesize orderListModel=_orderListModel;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) int orderFilterType; // @synthesize orderFilterType=_orderFilterType;
@property(retain, nonatomic) UITableView *_tableView; // @synthesize _tableView=__tableView;
- (void).cxx_destruct;	// IMP=0x00000001001ec880
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x00000001001ec66c
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00000001001ec474
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001001eb8c8
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001001eb87c
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001001eb800
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;	// IMP=0x00000001001eb7ec
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;	// IMP=0x00000001001eb768
- (id)getNormalFilterDataSource;	// IMP=0x00000001001eb550
- (id)getCouponOrderFilterDataSource;	// IMP=0x00000001001eb3a8
- (id)getMobileRechargeOrderFilterDataSource;	// IMP=0x00000001001eb210
- (id)setupataSourceWithFilterOrderType:(int)arg1;	// IMP=0x00000001001eb1a4
- (void)privateLayoutTableView;	// IMP=0x00000001001ea8b4
- (void)setupUI;	// IMP=0x00000001001ea800
- (void)didReceiveMemoryWarning;	// IMP=0x00000001001ea7cc
- (void)viewDidLoad;	// IMP=0x00000001001ea77c
- (id)initWithOrderFileterType:(int)arg1;	// IMP=0x00000001001ea698
- (id)initWithOrderFileterType:(int)arg1 delegate:(id)arg2 orderStatus:(id)arg3 timeFilterStatus:(id)arg4;	// IMP=0x00000001001ea524

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

