//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AEOrderListSubListSkuDTO : NSObject
{
    int _pId;	// 8 = 0x8
    int _pValueId;	// 12 = 0xc
    int _order;	// 16 = 0x10
    NSString *_pName;	// 24 = 0x18
    NSString *_pValue;	// 32 = 0x20
    NSString *_selfDefineValue;	// 40 = 0x28
}

@property(nonatomic) int order; // @synthesize order=_order;
@property(copy, nonatomic) NSString *selfDefineValue; // @synthesize selfDefineValue=_selfDefineValue;
@property(copy, nonatomic) NSString *pValue; // @synthesize pValue=_pValue;
@property(nonatomic) int pValueId; // @synthesize pValueId=_pValueId;
@property(copy, nonatomic) NSString *pName; // @synthesize pName=_pName;
@property(nonatomic) int pId; // @synthesize pId=_pId;
- (void).cxx_destruct;	// IMP=0x00000001001f5110

@end

