//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface AEOrderCancelReasonTableViewCell : UITableViewCell
{
    UILabel *_reasonLabel;	// 8 = 0x8
    UIImageView *_checkedImageView;	// 16 = 0x10
    UIView *_splitView;	// 24 = 0x18
}

@property(retain, nonatomic) UIView *splitView; // @synthesize splitView=_splitView;
@property(retain, nonatomic) UIImageView *checkedImageView; // @synthesize checkedImageView=_checkedImageView;
@property(retain, nonatomic) UILabel *reasonLabel; // @synthesize reasonLabel=_reasonLabel;
- (void).cxx_destruct;	// IMP=0x00000001001d06d4
- (void)setSelected:(_Bool)arg1;	// IMP=0x00000001001d05e0
- (void)bindReason:(id)arg1 checked:(_Bool)arg2;	// IMP=0x00000001001d0590
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001001d0180

@end

