//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AFCommandClass.h"

@class NSString;

@interface AEPayMethodUtils : NSObject <AFCommandClass>
{
}

+ (void)gotoWaitPaymentOrderList;	// IMP=0x00000001005898f4
+ (void)handleAlipayResult:(id)arg1 onViewController:(id)arg2 toOrderListWhenCacel:(_Bool)arg3;	// IMP=0x0000000100588b38
+ (void)alipayResult:(id)arg1;	// IMP=0x0000000100588a3c
+ (void)execute:(id)arg1;	// IMP=0x0000000100588a30

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

