//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBuyBaseCell.h"

@class AECreditCardInfoDTO, UILabel, UIView;

@interface AEPaymentTitleAndSubTitleCell : AEBuyBaseCell
{
    CDUnknownBlockType _editCardBlock;	// 8 = 0x8
    UILabel *_titleLabel;	// 16 = 0x10
    UILabel *_subTitleLabel;	// 24 = 0x18
    UILabel *_editLabel;	// 32 = 0x20
    UIView *_disableMaskView;	// 40 = 0x28
    AECreditCardInfoDTO *_editableCreditcard;	// 48 = 0x30
    CDUnknownBlockType _selectedAction;	// 56 = 0x38
}

@property(copy, nonatomic) CDUnknownBlockType selectedAction; // @synthesize selectedAction=_selectedAction;
@property(retain, nonatomic) AECreditCardInfoDTO *editableCreditcard; // @synthesize editableCreditcard=_editableCreditcard;
@property(retain, nonatomic) UIView *disableMaskView; // @synthesize disableMaskView=_disableMaskView;
@property(retain, nonatomic) UILabel *editLabel; // @synthesize editLabel=_editLabel;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType editCardBlock; // @synthesize editCardBlock=_editCardBlock;
- (void).cxx_destruct;	// IMP=0x0000000100583b18
- (void)bindModel:(id)arg1;	// IMP=0x0000000100582f8c
- (void)configConstraints;	// IMP=0x00000001005827f0
- (void)setupLabels;	// IMP=0x0000000100582364
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100582164

@end

