//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEPaymentCellVMCommon.h"

@class NSArray, NSAttributedString;

@interface AEPaymentTitleAndIconsCellVM : AEPaymentCellVMCommon
{
    NSAttributedString *_attributedTitle;	// 8 = 0x8
    NSArray *_icons;	// 16 = 0x10
}

+ (id)imageNamesFromTypes:(id)arg1;	// IMP=0x0000000100581dec
+ (id)makeTitleAndIconsCellVMForOtherPayment:(id)arg1;	// IMP=0x0000000100581ae4
+ (id)makeTitleAndIconsCellVMForNewCreditcard:(id)arg1;	// IMP=0x0000000100581864
@property(retain, nonatomic) NSArray *icons; // @synthesize icons=_icons;
@property(retain, nonatomic) NSAttributedString *attributedTitle; // @synthesize attributedTitle=_attributedTitle;
- (void).cxx_destruct;	// IMP=0x0000000100582118
- (id)viewClassName;	// IMP=0x0000000100581838
- (id)init;	// IMP=0x0000000100581798

@end

