//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AEMiddlePaymentService, AEPaymentCheckoutDTO, AEPaymentRouteResultDTO, NSString, UIActivityIndicatorView, UIButton, UITableView;

@interface AEPaymentConfirmationViewController : AEUIViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;	// 8 = 0x8
    UIButton *_confirmButton;	// 16 = 0x10
    NSString *_orderIds;	// 24 = 0x18
    AEPaymentCheckoutDTO *_paymentCheckoutDTO;	// 32 = 0x20
    AEPaymentRouteResultDTO *_paymentRouteResultDTO;	// 40 = 0x28
    AEMiddlePaymentService *_service;	// 48 = 0x30
    UIActivityIndicatorView *_activityIndicatorView;	// 56 = 0x38
    unsigned long long _paymentPageFrom;	// 64 = 0x40
}

@property(nonatomic) unsigned long long paymentPageFrom; // @synthesize paymentPageFrom=_paymentPageFrom;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) AEMiddlePaymentService *service; // @synthesize service=_service;
@property(retain, nonatomic) AEPaymentRouteResultDTO *paymentRouteResultDTO; // @synthesize paymentRouteResultDTO=_paymentRouteResultDTO;
@property(retain, nonatomic) AEPaymentCheckoutDTO *paymentCheckoutDTO; // @synthesize paymentCheckoutDTO=_paymentCheckoutDTO;
@property(retain, nonatomic) NSString *orderIds; // @synthesize orderIds=_orderIds;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;	// IMP=0x000000010056c824
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010056c298
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x000000010056c20c
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x000000010056c204
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x000000010056c0e0
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x000000010056bf88
- (void)showPaymentMethodView;	// IMP=0x000000010056bac4
- (void)handleHoldRouteResult;	// IMP=0x000000010056b5d0
- (void)doPay:(_Bool)arg1;	// IMP=0x000000010056b2f8
- (void)confirmPay:(id)arg1;	// IMP=0x000000010056a8b0
- (void)updatePaymentCheckoutData:(id)arg1;	// IMP=0x000000010056a5d4
- (void)updatePaymentCheckout;	// IMP=0x000000010056a1f8
- (void)didSelectPayMethod:(id)arg1;	// IMP=0x0000000100569dd8
- (void)hideLoading;	// IMP=0x0000000100569dc0
- (void)showLoading;	// IMP=0x0000000100569a24
- (void)close;	// IMP=0x0000000100569a0c
- (void)configConfirmButton;	// IMP=0x0000000100568b94
- (void)configTableView;	// IMP=0x000000010056833c
- (void)setupLeftButton;	// IMP=0x00000001005681d8
- (void)viewDidLoad;	// IMP=0x00000001005680d8
- (id)pageTrackParams;	// IMP=0x0000000100567fb8
- (id)pageTrackName;	// IMP=0x0000000100567f8c
- (id)initWithParam:(id)arg1;	// IMP=0x0000000100567e30

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

