//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AEPaymentDataConvertor : NSObject
{
}

+ (id)convertToAEPaymentResultDTO:(id)arg1;	// IMP=0x000000010056c8d4

@end

