//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

#import "AEImageRowTableViewCellDelegate.h"
#import "AEOverlayViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ALAssetsGroup, ALAssetsLibrary, NSArray, NSDictionary, NSMutableArray, NSString, UIButton, UILabel, UITableView, UIView;

@interface AEPhotoPickerVC : AEUIViewController <AEImageRowTableViewCellDelegate, UITableViewDataSource, UITableViewDelegate, AEOverlayViewDelegate>
{
    ALAssetsLibrary *_assetLibrary;	// 8 = 0x8
    UITableView *_tableView;	// 16 = 0x10
    UILabel *_chooseCountLbl;	// 24 = 0x18
    UIButton *_confirmBtn;	// 32 = 0x20
    NSMutableArray *_assetsInGroup;	// 40 = 0x28
    _Bool _isNeedScrollToBottom;	// 48 = 0x30
    long long _lockToIndex;	// 56 = 0x38
    NSArray *_lockSelectedImageInfos;	// 64 = 0x40
    _Bool _showCaptureEntrance;	// 72 = 0x48
    _Bool _allowPreview;	// 73 = 0x49
    _Bool _needOriginalImage;	// 74 = 0x4a
    id <AEPhotoPickerDelegate> delegate;	// 80 = 0x50
    long long _columnPerRow;	// 88 = 0x58
    long long _maxSelectNum;	// 96 = 0x60
    long long _minSelectNum;	// 104 = 0x68
    UIView *_overlayView;	// 112 = 0x70
    NSMutableArray *_selectedImageInfos;	// 120 = 0x78
    NSDictionary *_parameters;	// 128 = 0x80
    ALAssetsGroup *_assetsGroup;	// 136 = 0x88
}

+ (void)takePhotoFromViewController:(id)arg1 andView:(id)arg2;	// IMP=0x000000010083c020
+ (void)takePhotoFromViewController:(id)arg1;	// IMP=0x000000010083bdb8
@property(retain, nonatomic) ALAssetsGroup *assetsGroup; // @synthesize assetsGroup=_assetsGroup;
@property(retain, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(nonatomic) _Bool needOriginalImage; // @synthesize needOriginalImage=_needOriginalImage;
@property(nonatomic) _Bool allowPreview; // @synthesize allowPreview=_allowPreview;
@property(nonatomic) _Bool showCaptureEntrance; // @synthesize showCaptureEntrance=_showCaptureEntrance;
@property(retain, nonatomic) NSMutableArray *selectedImageInfos; // @synthesize selectedImageInfos=_selectedImageInfos;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(nonatomic) long long minSelectNum; // @synthesize minSelectNum=_minSelectNum;
@property(nonatomic) long long maxSelectNum; // @synthesize maxSelectNum=_maxSelectNum;
@property(nonatomic) long long columnPerRow; // @synthesize columnPerRow=_columnPerRow;
@property(nonatomic) __weak id <AEPhotoPickerDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;	// IMP=0x000000010083c448
- (void)aeRemovePhoto:(id)arg1;	// IMP=0x000000010083bc3c
- (void)enterCapture;	// IMP=0x000000010083ba94
- (void)updateOverlayView;	// IMP=0x000000010083b9d8
- (void)updateChooselbl;	// IMP=0x000000010083b88c
- (void)_clearOtherSelectStatus:(id)arg1;	// IMP=0x000000010083b458
- (void)asset:(id)arg1 selectedChanged:(_Bool)arg2;	// IMP=0x000000010083afa0
- (_Bool)asset:(id)arg1 shouldChangeSelectedStatus:(_Bool)arg2;	// IMP=0x000000010083abe4
- (void)asset:(id)arg1 enterPreview:(long long)arg2;	// IMP=0x000000010083aa6c
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x000000010083a588
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x000000010083a504
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x000000010083a4fc
- (void)loadAssetsGroup;	// IMP=0x000000010083a1b4
- (void)replaceAlAssets:(id)arg1;	// IMP=0x000000010083a144
- (void)loadAssetsLibrary;	// IMP=0x0000000100839d1c
- (void)shareAndEnterCameraAction:(id)arg1;	// IMP=0x0000000100839a5c
- (void)shareAction:(id)arg1;	// IMP=0x000000010083956c
- (void)cancelShareAction:(id)arg1;	// IMP=0x00000001008392f8
- (void)refreshUI;	// IMP=0x000000010083912c
- (void)setSelectedImageInfos:(id)arg1 lockToIndex:(long long)arg2;	// IMP=0x0000000100838fa8
- (void)scrollToBottom;	// IMP=0x0000000100838ccc
- (void)setupBottomView;	// IMP=0x0000000100837e60
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100837b40
- (_Bool)shouldAutorotate;	// IMP=0x0000000100837b38
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x0000000100837b30
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100837afc
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x000000010083792c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001008378dc
- (void)viewDidLoad;	// IMP=0x0000000100837294
- (id)showMode;	// IMP=0x0000000100837268
- (void)dealloc;	// IMP=0x00000001008371bc
- (id)initWithParam:(id)arg1;	// IMP=0x0000000100836fe8
- (id)init;	// IMP=0x0000000100836fd8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

