//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface AEPhotoSearchRegion : NSObject <NSCopying>
{
    double _x;	// 8 = 0x8
    double _y;	// 16 = 0x10
    double _width;	// 24 = 0x18
    double _height;	// 32 = 0x20
}

+ (id)replacedKeyFromPropertyName;	// IMP=0x0000000100c60c54
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
@property(nonatomic) double y; // @synthesize y=_y;
@property(nonatomic) double x; // @synthesize x=_x;
- (void)keyValuesDidFinishConvertingToObject;	// IMP=0x0000000100c60d1c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100c60b90

@end

