//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AESessionUserChangeTask.h"
#import "AIFServerOPConsumer.h"

@class AIFServerOP, NSMutableDictionary, NSString;

@interface AEPopLayerConfigCenter : NSObject <AIFServerOPConsumer, AESessionUserChangeTask>
{
    NSMutableDictionary *_configDict;	// 8 = 0x8
    AIFServerOP *_poplayerOP;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x0000000100b9c904
@property(retain, nonatomic) AIFServerOP *poplayerOP; // @synthesize poplayerOP=_poplayerOP;
- (void).cxx_destruct;	// IMP=0x0000000100b9d18c
- (void)dealloc;	// IMP=0x0000000100b9d0ec
- (void)updatePoplayerRuleFromRemote;	// IMP=0x0000000100b9d0d8
- (void)execute:(unsigned long long)arg1;	// IMP=0x0000000100b9d0c4
- (id)getConfigByKey:(id)arg1;	// IMP=0x0000000100b9ce74
- (void)updatePoplayerRule;	// IMP=0x0000000100b9cca8
- (void)consume:(id)arg1;	// IMP=0x0000000100b9cb70
- (id)init;	// IMP=0x0000000100b9c9b8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

