//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

#import "AEProductListTableViewDelegate.h"
#import "AESearchBarTipsContainerViewDelegate.h"
#import "AESearchDefaultPanelDelegate.h"
#import "AESearchFilterViewControllerDelegate.h"
#import "AESearchResultVCDelegate.h"
#import "AFCommandTest.h"
#import "AFViewHierarchyContainerProtocol.h"
#import "AIFExposureProtocol.h"

@class AECategoryRefineDTO, AEProductListTableView, AEProductListVCModel, AESearchBarController, AESearchBarTipsContainerView, AESearchDefaultPanelVC, AESearchFilterViewController, AESearchResultVC, AIFCountry, NSString, UIButton, UINavigationController, UIView;

@interface AEProductListVC : AEUIViewController <AFCommandTest, AEProductListTableViewDelegate, AIFExposureProtocol, AESearchFilterViewControllerDelegate, AESearchBarTipsContainerViewDelegate, AESearchResultVCDelegate, AESearchDefaultPanelDelegate, AFViewHierarchyContainerProtocol>
{
    AEProductListTableView *_tableView;	// 8 = 0x8
    AEProductListVCModel *_productListVCModel;	// 16 = 0x10
    AECategoryRefineDTO *_currentCategoryRefineDto;	// 24 = 0x18
    AESearchFilterViewController *_refineViewVC;	// 32 = 0x20
    UINavigationController *_refineNavigationController;	// 40 = 0x28
    UIView *_refineBackgroundView;	// 48 = 0x30
    NSString *_streamId;	// 56 = 0x38
    AIFCountry *_originShipToCountry;	// 64 = 0x40
    NSString *_replacedKeyword;	// 72 = 0x48
    AESearchBarController *_searchBarController;	// 80 = 0x50
    AESearchResultVC *_searchResultVC;	// 88 = 0x58
    AESearchBarTipsContainerView *_leftView;	// 96 = 0x60
    AESearchDefaultPanelVC *_panelVC;	// 104 = 0x68
}

+ (id)paramsToTest;	// IMP=0x0000000100c37ba8
@property(retain, nonatomic) AESearchDefaultPanelVC *panelVC; // @synthesize panelVC=_panelVC;
@property(retain, nonatomic) AESearchBarTipsContainerView *leftView; // @synthesize leftView=_leftView;
@property(retain, nonatomic) AESearchResultVC *searchResultVC; // @synthesize searchResultVC=_searchResultVC;
@property(retain, nonatomic) AESearchBarController *searchBarController; // @synthesize searchBarController=_searchBarController;
@property(copy, nonatomic) NSString *replacedKeyword; // @synthesize replacedKeyword=_replacedKeyword;
@property(copy, nonatomic) AIFCountry *originShipToCountry; // @synthesize originShipToCountry=_originShipToCountry;
@property(retain, nonatomic) NSString *streamId; // @synthesize streamId=_streamId;
@property(retain, nonatomic) UIView *refineBackgroundView; // @synthesize refineBackgroundView=_refineBackgroundView;
@property(retain, nonatomic) UINavigationController *refineNavigationController; // @synthesize refineNavigationController=_refineNavigationController;
@property(retain, nonatomic) AESearchFilterViewController *refineViewVC; // @synthesize refineViewVC=_refineViewVC;
@property(retain, nonatomic) AECategoryRefineDTO *currentCategoryRefineDto; // @synthesize currentCategoryRefineDto=_currentCategoryRefineDto;
@property(retain, nonatomic) AEProductListVCModel *productListVCModel; // @synthesize productListVCModel=_productListVCModel;
@property(retain, nonatomic) AEProductListTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;	// IMP=0x0000000100c37a8c
- (id)sortViewTitleArray;	// IMP=0x0000000100c37538
- (Class)VCModelClass;	// IMP=0x0000000100c37524
- (_Bool)searchQueryIsModified;	// IMP=0x0000000100c36934
- (id)primaryContentViewController;	// IMP=0x0000000100c3685c
- (void)filterBtnTapped;	// IMP=0x0000000100c367d0
@property(readonly, nonatomic) UIButton *filterBtn;
- (id)pageTrackParams;	// IMP=0x0000000100c36144
- (id)pageTrackName;	// IMP=0x0000000100c36118
- (id)sceneId;	// IMP=0x0000000100c360dc
- (id)exposureType;	// IMP=0x0000000100c360c4
- (id)additionalParaForExposure;	// IMP=0x0000000100c3524c
- (void)showRefine;	// IMP=0x0000000100c33e70
- (void)closeRefine;	// IMP=0x0000000100c33474
- (void)updatePageTrackWithAB:(id)arg1;	// IMP=0x0000000100c333a0
- (void)startSearching;	// IMP=0x0000000100c326ac
- (void)handlerPoplayer;	// IMP=0x0000000100c326a8
- (void)updateReplacedKeyWordWithResultDTO:(id)arg1;	// IMP=0x0000000100c32228
- (void)updateBizWithData:(id)arg1 dataDictionary:(id)arg2;	// IMP=0x0000000100c31b34
- (void)showQrwResultWithData:(id)arg1;	// IMP=0x0000000100c316b4
- (void)showSwipeAnimate;	// IMP=0x0000000100c315cc
- (void)realShowEmptyPage:(id)arg1;	// IMP=0x0000000100c30c60
- (void)showEmptyPage:(id)arg1;	// IMP=0x0000000100c30b00
- (void)updateRefineView;	// IMP=0x0000000100c307b8
- (void)showSearchFunction:(id)arg1;	// IMP=0x0000000100c30424
- (void)showErrorPageWithError:(id)arg1;	// IMP=0x0000000100c2fe7c
- (void)updateRefineWithResultDTO:(id)arg1;	// IMP=0x0000000100c2fbd8
- (void)updateSpellingCheckWithIgnoreSpellingCheck:(_Bool)arg1;	// IMP=0x0000000100c2fb90
- (void)resetTipsByKeyword:(id)arg1;	// IMP=0x0000000100c2f9c0
- (void)doSortMode:(long long)arg1;	// IMP=0x0000000100c2f760
- (void)doBigSale:(_Bool)arg1;	// IMP=0x0000000100c2f5b4
- (void)requestLogoWallWithData:(id)arg1 isReset:(_Bool)arg2;	// IMP=0x0000000100c2f530
- (_Bool)shouldCareForSearchPlaceholder;	// IMP=0x0000000100c2f48c
- (void)shortcutButtonAction:(id)arg1;	// IMP=0x0000000100c2f400
- (void)searchFilterViewControllerCloseWithSearchQuery:(id)arg1;	// IMP=0x0000000100c2f3f4
- (void)searchFilterViewControllerUpdateWithSearchQuery:(id)arg1;	// IMP=0x0000000100c2ea84
- (id)extraParamsForAction:(id)arg1;	// IMP=0x0000000100c2e8bc
- (void)searchWithKeyword:(id)arg1 cateroryId:(id)arg2;	// IMP=0x0000000100c2e5b0
- (_Bool)stringArray:(id)arg1 containsString:(id)arg2;	// IMP=0x0000000100c2e400
- (id)getSearchAttributeTipsString;	// IMP=0x0000000100c2dfc8
- (id)getSearchTagTipsString;	// IMP=0x0000000100c2dce4
- (void)onSearchTagAdded:(id)arg1;	// IMP=0x0000000100c2da74
- (void)deleteAttributeId:(id)arg1 attributeValues:(id)arg2;	// IMP=0x0000000100c2d8c8
- (void)selectAttributeId:(id)arg1 attributeValues:(id)arg2;	// IMP=0x0000000100c2d71c
- (id)existSearchTags;	// IMP=0x0000000100c2d6bc
- (void)didSelectedTipView:(id)arg1 searchTag:(id)arg2;	// IMP=0x0000000100c2cdc0
- (void)loadNextPage;	// IMP=0x0000000100c2cbb4
- (void)refreshService;	// IMP=0x0000000100c2cb60
- (void)cellDidEndDisplayCell:(id)arg1 index:(long long)arg2 productId:(id)arg3 item:(id)arg4;	// IMP=0x0000000100c2c7a0
- (void)cellWillDisplayCell:(id)arg1 index:(long long)arg2 productId:(id)arg3 item:(id)arg4;	// IMP=0x0000000100c2c3e0
- (void)tipClickedCallback:(id)arg1;	// IMP=0x0000000100c2c358
- (void)setupUI;	// IMP=0x0000000100c2bd48
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100c2bcf8
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100c2ba94
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100c2b774
- (_Bool)is83;	// IMP=0x0000000100c2b6dc
- (void)popViewControllerAnimated:(id)arg1;	// IMP=0x0000000100c2b6d8
- (void)setupSearchBar;	// IMP=0x0000000100c2aee8
- (void)doBack;	// IMP=0x0000000100c2ae98
- (void)setupUILeftItem;	// IMP=0x0000000100c2acd8
- (void)viewDidLoad;	// IMP=0x0000000100c2a694
- (id)initForRouter;	// IMP=0x0000000100c2a688
- (unsigned long long)displayMode;	// IMP=0x0000000100c2a680
- (id)initByQuery:(id)arg1 title:(id)arg2;	// IMP=0x0000000100c2a598
- (id)initWithParam:(id)arg1;	// IMP=0x0000000100c2a4f4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

