//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AEProductListBannerVM, UIButton, UIImageView;

@interface AEProductListBannerView : UIView
{
    id <AEProductListViewsProtocol> _delegate;	// 8 = 0x8
    AEProductListBannerVM *_listBannerVM;	// 16 = 0x10
    UIButton *_banner;	// 24 = 0x18
    UIImageView *_backImgV;	// 32 = 0x20
}

@property(retain, nonatomic) UIImageView *backImgV; // @synthesize backImgV=_backImgV;
@property(retain, nonatomic) UIButton *banner; // @synthesize banner=_banner;
@property(retain, nonatomic) AEProductListBannerVM *listBannerVM; // @synthesize listBannerVM=_listBannerVM;
@property(nonatomic) __weak id <AEProductListViewsProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100c42308
- (void)doBanner;	// IMP=0x0000000100c42104
- (double)viewHeight;	// IMP=0x0000000100c420a4
- (void)bindVMData:(id)arg1;	// IMP=0x0000000100c41fc4
- (void)setupUI;	// IMP=0x0000000100c41100
- (id)init;	// IMP=0x0000000100c410a8
- (id)initWithDelegate:(id)arg1;	// IMP=0x0000000100c41020

@end

