//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTileCell.h"

@class UIButton, UILabel;

@interface AEPreferenceTileCell : AEBaseTileCell
{
    UILabel *_title;	// 8 = 0x8
    UILabel *_subTitle;	// 16 = 0x10
    UIButton *_setPreference;	// 24 = 0x18
    UIButton *_dismiss;	// 32 = 0x20
}

@property(retain, nonatomic) UIButton *dismiss; // @synthesize dismiss=_dismiss;
@property(retain, nonatomic) UIButton *setPreference; // @synthesize setPreference=_setPreference;
@property(retain, nonatomic) UILabel *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
- (void).cxx_destruct;	// IMP=0x00000001003fcbc4
- (void)prepareForReuse;	// IMP=0x00000001003fc9fc
- (void)renderWithTile:(id)arg1;	// IMP=0x00000001003fc738
- (void)setupUI;	// IMP=0x00000001003fb134
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001003fb0dc

@end

