//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIButton, UILabel;

@interface AEPreferenceHeaderNavView : UIView
{
    _Bool _constraitsInited;	// 8 = 0x8
    long long _navType;	// 16 = 0x10
    NSString *_titleText;	// 24 = 0x18
    NSString *_controlText;	// 32 = 0x20
    CDUnknownBlockType _navAction;	// 40 = 0x28
    UILabel *_titleLabel;	// 48 = 0x30
    UIButton *_controlBtn;	// 56 = 0x38
}

@property(retain, nonatomic) UIButton *controlBtn; // @synthesize controlBtn=_controlBtn;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType navAction; // @synthesize navAction=_navAction;
@property(copy, nonatomic) NSString *controlText; // @synthesize controlText=_controlText;
@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(nonatomic) long long navType; // @synthesize navType=_navType;
- (void).cxx_destruct;	// IMP=0x000000010022312c
- (void)navAction:(id)arg1;	// IMP=0x0000000100222758
- (struct CGSize)intrinsicContentSize;	// IMP=0x00000001002226bc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100222370

@end

