//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

#import "AEFeedbackPanelDelegate.h"
#import "AFCommandTest.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AEFeedbackFilterPanel, AEFeedbackTranslationSwitch, AEProductDetailService, AEProductFeedbackRatingView, AEProductReviewsBasicDTO, AESpinnerTableView, NSMutableArray, NSMutableDictionary, NSString, UITableView, UIView;

@interface AEProductFeedbackController : AEUIViewController <AFCommandTest, UITableViewDataSource, UITableViewDelegate, AEFeedbackPanelDelegate>
{
    _Bool _needScrollToTopAfterDataLoaded;	// 8 = 0x8
    _Bool _emptyResult;	// 9 = 0x9
    _Bool _loading;	// 10 = 0xa
    _Bool _hasNextPage;	// 11 = 0xb
    _Bool _didShowTranslation;	// 12 = 0xc
    AEProductFeedbackRatingView *_ratingView;	// 16 = 0x10
    AEFeedbackTranslationSwitch *_translationSwitch;	// 24 = 0x18
    AEFeedbackFilterPanel *_filterPanel;	// 32 = 0x20
    AEFeedbackFilterPanel *_floatingFilterPanel;	// 40 = 0x28
    AESpinnerTableView *_sortedSpinner;	// 48 = 0x30
    UITableView *_tableView;	// 56 = 0x38
    UIView *_tableLoadingFooter;	// 64 = 0x40
    NSMutableDictionary *_estimatedHeightCache;	// 72 = 0x48
    AEProductDetailService *_service;	// 80 = 0x50
    AEProductReviewsBasicDTO *_reviewsDTO;	// 88 = 0x58
    NSMutableArray *_productImageReviewsDTO;	// 96 = 0x60
    NSMutableArray *_productReviewImages;	// 104 = 0x68
    NSString *_productId;	// 112 = 0x70
    NSString *_sellerAdminSeq;	// 120 = 0x78
    unsigned long long _sortedType;	// 128 = 0x80
    long long _filterType;	// 136 = 0x88
    long long _page;	// 144 = 0x90
}

+ (id)paramsToTest;	// IMP=0x00000001005d8b88
@property(nonatomic) long long page; // @synthesize page=_page;
@property(nonatomic) long long filterType; // @synthesize filterType=_filterType;
@property(nonatomic) unsigned long long sortedType; // @synthesize sortedType=_sortedType;
@property(retain, nonatomic) NSString *sellerAdminSeq; // @synthesize sellerAdminSeq=_sellerAdminSeq;
@property(retain, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(nonatomic) _Bool didShowTranslation; // @synthesize didShowTranslation=_didShowTranslation;
@property(nonatomic) _Bool hasNextPage; // @synthesize hasNextPage=_hasNextPage;
@property(nonatomic) _Bool loading; // @synthesize loading=_loading;
@property(nonatomic) _Bool emptyResult; // @synthesize emptyResult=_emptyResult;
@property(nonatomic) _Bool needScrollToTopAfterDataLoaded; // @synthesize needScrollToTopAfterDataLoaded=_needScrollToTopAfterDataLoaded;
@property(retain, nonatomic) NSMutableArray *productReviewImages; // @synthesize productReviewImages=_productReviewImages;
@property(retain, nonatomic) NSMutableArray *productImageReviewsDTO; // @synthesize productImageReviewsDTO=_productImageReviewsDTO;
@property(retain, nonatomic) AEProductReviewsBasicDTO *reviewsDTO; // @synthesize reviewsDTO=_reviewsDTO;
@property(retain, nonatomic) AEProductDetailService *service; // @synthesize service=_service;
@property(retain, nonatomic) NSMutableDictionary *estimatedHeightCache; // @synthesize estimatedHeightCache=_estimatedHeightCache;
@property(retain, nonatomic) UIView *tableLoadingFooter; // @synthesize tableLoadingFooter=_tableLoadingFooter;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) AESpinnerTableView *sortedSpinner; // @synthesize sortedSpinner=_sortedSpinner;
@property(retain, nonatomic) AEFeedbackFilterPanel *floatingFilterPanel; // @synthesize floatingFilterPanel=_floatingFilterPanel;
@property(retain, nonatomic) AEFeedbackFilterPanel *filterPanel; // @synthesize filterPanel=_filterPanel;
@property(retain, nonatomic) AEFeedbackTranslationSwitch *translationSwitch; // @synthesize translationSwitch=_translationSwitch;
@property(retain, nonatomic) AEProductFeedbackRatingView *ratingView; // @synthesize ratingView=_ratingView;
- (void).cxx_destruct;	// IMP=0x00000001005d87c4
- (void)feedbackPanel:(id)arg1 willSelectFilter:(long long)arg2;	// IMP=0x00000001005d80b8
- (void)close:(id)arg1;	// IMP=0x00000001005d8070
- (void)hideFloatingFilterPanel:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001005d7e5c
- (_Bool)viewIsVisibleNow:(id)arg1;	// IMP=0x00000001005d7cf4
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x00000001005d7c70
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;	// IMP=0x00000001005d7b78
- (id)cellVMFromDTO:(id)arg1 atIndex:(long long)arg2;	// IMP=0x00000001005d793c
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001005d7508
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00000001005d73b0
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;	// IMP=0x00000001005d72d4
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x00000001005d71cc
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001005d71c4
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001005d7130
- (CDUnknownBlockType)productReviewCellViewImageBlock;	// IMP=0x00000001005d6c98
- (id)extractImagesFromImageReviewDTO:(id)arg1 translated:(_Bool)arg2;	// IMP=0x00000001005d67ec
- (CDUnknownBlockType)productReviewLoadMoreBlock:(id)arg1;	// IMP=0x00000001005d5fb4
- (void)generateReviewImages;	// IMP=0x00000001005d5cd0
- (void)refreshDateSourceForTranslation;	// IMP=0x00000001005d5b5c
- (void)switchTranslation;	// IMP=0x00000001005d59a0
- (void)sortedChanged;	// IMP=0x00000001005d5878
- (void)scrollToTopIfNeeded;	// IMP=0x00000001005d575c
- (void)updateTableViewFooter;	// IMP=0x00000001005d56b4
- (void)updateFilterPanel;	// IMP=0x00000001005d54d0
- (void)updateFeedbackRatingView;	// IMP=0x00000001005d5408
- (void)getProductReviews:(long long)arg1 filter:(long long)arg2;	// IMP=0x00000001005d4f14
- (void)loadNextPage;	// IMP=0x00000001005d4c30
- (void)refreshData;	// IMP=0x00000001005d4b28
- (void)layoutTableHeader;	// IMP=0x00000001005d46c8
- (void)setupTableViewFooter;	// IMP=0x00000001005d43dc
- (void)setupTableViewHeader;	// IMP=0x00000001005d37d4
- (void)setupViews;	// IMP=0x00000001005d2f38
- (id)pageTrackName;	// IMP=0x00000001005d2f0c
- (void)dealloc;	// IMP=0x00000001005d2e5c
- (void)viewDidLoad;	// IMP=0x00000001005d2cc0
- (id)initWithParam:(id)arg1;	// IMP=0x00000001005d2b44

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

