//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "AEProductListViewsProtocol.h"

@class AEProductListStoreBannerVM, NSString, UIImageView, UILabel;

@interface AEProductListStoreBannerView : UIView <AEProductListViewsProtocol>
{
    UIView *_storeLogoContainer;	// 8 = 0x8
    UIImageView *_storeLogo;	// 16 = 0x10
    UILabel *_storeContent;	// 24 = 0x18
    UILabel *_storeLogoName;	// 32 = 0x20
    UIImageView *_accessory;	// 40 = 0x28
    id <AEProductListViewsProtocol> _delegate;	// 48 = 0x30
    AEProductListStoreBannerVM *_storeBannerVM;	// 56 = 0x38
}

@property(retain, nonatomic) AEProductListStoreBannerVM *storeBannerVM; // @synthesize storeBannerVM=_storeBannerVM;
@property(nonatomic) __weak id <AEProductListViewsProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *accessory; // @synthesize accessory=_accessory;
@property(retain, nonatomic) UILabel *storeLogoName; // @synthesize storeLogoName=_storeLogoName;
@property(retain, nonatomic) UILabel *storeContent; // @synthesize storeContent=_storeContent;
@property(retain, nonatomic) UIImageView *storeLogo; // @synthesize storeLogo=_storeLogo;
@property(retain, nonatomic) UIView *storeLogoContainer; // @synthesize storeLogoContainer=_storeLogoContainer;
- (void).cxx_destruct;	// IMP=0x0000000100bc6174
- (double)viewHeight;	// IMP=0x0000000100bc5f84
- (void)doAction;	// IMP=0x0000000100bc5d58
- (void)bindVM:(id)arg1;	// IMP=0x0000000100bc5228
- (void)setupUI;	// IMP=0x0000000100bc36c8
- (id)initWithDelegate:(id)arg1;	// IMP=0x0000000100bc3640

// Remaining properties
@property(retain, nonatomic) NSString *action;
@property(nonatomic) __weak Class clz;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSString *param;
@property(readonly) Class superclass;

@end

