//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AEProductListTableViewHeaderCMProtocol.h"

@class NSDictionary, NSString;

@interface AEProductListBannerVM : NSObject <AEProductListTableViewHeaderCMProtocol>
{
    NSString *action;	// 8 = 0x8
    NSDictionary *actionParam;	// 16 = 0x10
    NSString *_bannerUrl;	// 24 = 0x18
}

@property(retain, nonatomic) NSString *bannerUrl; // @synthesize bannerUrl=_bannerUrl;
@property(retain, nonatomic) NSDictionary *actionParam; // @synthesize actionParam;
@property(copy, nonatomic) NSString *action; // @synthesize action;
- (void).cxx_destruct;	// IMP=0x0000000100c663bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

