//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface AEQandAQuestionList : NSObject
{
    _Bool _hasNext;	// 8 = 0x8
    long long _currentPage;	// 16 = 0x10
    long long _totalCount;	// 24 = 0x18
    NSArray *_questionList;	// 32 = 0x20
    NSArray *_recommendList;	// 40 = 0x28
    NSMutableArray *_questionMutableArray;	// 48 = 0x30
    NSMutableArray *_recommendMutableArray;	// 56 = 0x38
}

+ (id)format:(id)arg1;	// IMP=0x0000000100240880
@property(retain, nonatomic) NSMutableArray *recommendMutableArray; // @synthesize recommendMutableArray=_recommendMutableArray;
@property(retain, nonatomic) NSMutableArray *questionMutableArray; // @synthesize questionMutableArray=_questionMutableArray;
@property(copy, nonatomic) NSArray *recommendList; // @synthesize recommendList=_recommendList;
@property(copy, nonatomic) NSArray *questionList; // @synthesize questionList=_questionList;
@property(nonatomic) long long totalCount; // @synthesize totalCount=_totalCount;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) _Bool hasNext; // @synthesize hasNext=_hasNext;
- (void).cxx_destruct;	// IMP=0x0000000100240d60
- (void)addRecommend:(id)arg1;	// IMP=0x0000000100240810
- (void)addQuestion:(id)arg1;	// IMP=0x00000001002407a0
- (id)init;	// IMP=0x0000000100240664

@end

