//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface AERefundInfoReminderCell : UITableViewCell
{
    UILabel *_reminderTitle;	// 8 = 0x8
    UILabel *_reminder;	// 16 = 0x10
}

+ (double)cellHeight;	// IMP=0x000000010025c678
@property(retain, nonatomic) UILabel *reminder; // @synthesize reminder=_reminder;
@property(retain, nonatomic) UILabel *reminderTitle; // @synthesize reminderTitle=_reminderTitle;
- (void).cxx_destruct;	// IMP=0x000000010025c7fc
- (void)bindData:(id)arg1 reminder:(id)arg2;	// IMP=0x000000010025c4c4
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x000000010025bb34
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x000000010025bb00
- (void)awakeFromNib;	// IMP=0x000000010025bacc

@end

