//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ActivityChannelViewController.h"

@class AETileDTO, UIButton;

@interface AERUStoreChannelVC : ActivityChannelViewController
{
    UIButton *_searchBtn;	// 8 = 0x8
    AETileDTO *_searchFloor;	// 16 = 0x10
    UIButton *_messageBtn;	// 24 = 0x18
    AETileDTO *_messageFloor;	// 32 = 0x20
    UIButton *_chatBtn;	// 40 = 0x28
    AETileDTO *_chatFloor;	// 48 = 0x30
}

@property(retain, nonatomic) AETileDTO *chatFloor; // @synthesize chatFloor=_chatFloor;
@property(retain, nonatomic) UIButton *chatBtn; // @synthesize chatBtn=_chatBtn;
@property(retain, nonatomic) AETileDTO *messageFloor; // @synthesize messageFloor=_messageFloor;
@property(retain, nonatomic) UIButton *messageBtn; // @synthesize messageBtn=_messageBtn;
@property(retain, nonatomic) AETileDTO *searchFloor; // @synthesize searchFloor=_searchFloor;
@property(retain, nonatomic) UIButton *searchBtn; // @synthesize searchBtn=_searchBtn;
- (void).cxx_destruct;	// IMP=0x0000000100408940
- (void)didReceiveSessionLoginNotification;	// IMP=0x00000001004086ac
- (id)willProcessTileDTOs:(id)arg1 withDataContext:(id)arg2;	// IMP=0x00000001004081c8
- (void)saveData;	// IMP=0x00000001004081b4
- (void)onChatBarButtonTapped:(id)arg1;	// IMP=0x0000000100407eb8
- (void)onMessageBarButtonTapped:(id)arg1;	// IMP=0x0000000100407d74
- (void)onSearchBarButtonTapped:(id)arg1;	// IMP=0x0000000100407bb0
- (void)setupNavigationBar;	// IMP=0x00000001004076a8
- (void)dealloc;	// IMP=0x0000000100407640
- (void)viewDidLoad;	// IMP=0x000000010040759c

@end

