//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFEventTask.h"

@interface AESaveLocaleForMXTask : AFEventTask
{
}

+ (void)run;	// IMP=0x0000000100a6014c
+ (unsigned long long)triggerEvent;	// IMP=0x0000000100a60144
+ (unsigned long long)priority;	// IMP=0x0000000100a6013c
+ (void)load;	// IMP=0x0000000100a60120

@end

