//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AESearchListRefineAttributeModel, NSArray;

@interface AESearchListRefineAttributeDataController : NSObject
{
    _Bool _slidingDown;	// 8 = 0x8
    _Bool _showContainerView;	// 9 = 0x9
    AESearchListRefineAttributeModel *_model;	// 16 = 0x10
    double _headerViewHeight;	// 24 = 0x18
    NSArray *_attributes;	// 32 = 0x20
}

@property(retain, nonatomic) NSArray *attributes; // @synthesize attributes=_attributes;
@property(nonatomic) double headerViewHeight; // @synthesize headerViewHeight=_headerViewHeight;
@property(nonatomic, getter=isShowContainerView) _Bool showContainerView; // @synthesize showContainerView=_showContainerView;
@property(nonatomic, getter=isSlidingDown) _Bool slidingDown; // @synthesize slidingDown=_slidingDown;
@property(retain, nonatomic) AESearchListRefineAttributeModel *model; // @synthesize model=_model;
- (void).cxx_destruct;	// IMP=0x0000000100c7b698
- (id)getUnSelectedCellModelWithSelectedCellModel:(id)arg1;	// IMP=0x0000000100c7b4cc
- (id)getUnSelectedCellModelWithUnSelectedCellModel:(id)arg1;	// IMP=0x0000000100c7b3f0
- (id)getHighlightedCellModelWithUnSelectedCellModel:(id)arg1;	// IMP=0x0000000100c7b314
- (void)updateModelWithNewAttributes;	// IMP=0x0000000100c7adf0
- (void)initModel;	// IMP=0x0000000100c7ad98
- (void)initData;	// IMP=0x0000000100c7ad5c
- (void)updateWithResetHighlightAttribute;	// IMP=0x0000000100c7ac74
- (void)updateWithSelectedAttributeId:(id)arg1;	// IMP=0x0000000100c7a224
- (void)updateWithDeleteAttributeId:(id)arg1;	// IMP=0x0000000100c79de8
- (void)updateWithAttributes:(id)arg1;	// IMP=0x0000000100c79db4
- (id)initWithAttributes:(id)arg1 headerVieweight:(double)arg2;	// IMP=0x0000000100c79cd8

@end

