//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UILabel, UIView;

@interface AESearchFilterMultTextBaseCell : UITableViewCell
{
    UILabel *_titleLabel;	// 8 = 0x8
    UILabel *_detailLabel;	// 16 = 0x10
    UIView *_borderView;	// 24 = 0x18
    UIButton *_deleteBtn;	// 32 = 0x20
}

+ (double)heightWithViewModel:(id)arg1 displayWidth:(double)arg2;	// IMP=0x0000000100c9beb8
@property(retain, nonatomic) UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) UIView *borderView; // @synthesize borderView=_borderView;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;	// IMP=0x0000000100c9d6a0
- (void)deleteBtnTapped;	// IMP=0x0000000100c9d5bc
- (void)bindDataWithTitle:(id)arg1 detail:(id)arg2;	// IMP=0x0000000100c9d024
- (void)bindDataWithViewModel:(id)arg1;	// IMP=0x0000000100c9d020
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100c9bec4

@end

