//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class AVAsset, NSString, NSURL, UIImage;

@interface AESelectedImageInfo : NSObject <NSCopying>
{
    UIImage *thumbImage;	// 8 = 0x8
    UIImage *bigImage;	// 16 = 0x10
    NSURL *assetURL;	// 24 = 0x18
    NSString *photoTime;	// 32 = 0x20
}

+ (id)checkAndFixSelectInfoWithoutAssetURL:(id)arg1;	// IMP=0x000000010085171c
@property(retain, nonatomic) NSString *photoTime; // @synthesize photoTime;
@property(retain, nonatomic) NSURL *assetURL; // @synthesize assetURL;
@property(retain, nonatomic) UIImage *bigImage; // @synthesize bigImage;
@property(retain, nonatomic) UIImage *thumbImage; // @synthesize thumbImage;
- (void).cxx_destruct;	// IMP=0x0000000100851954
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001008515e8
@property(nonatomic) _Bool isProcessing; // @dynamic isProcessing;
@property(retain, nonatomic) AVAsset *asset; // @dynamic asset;
@property(nonatomic) _Bool isVideo; // @dynamic isVideo;
@property(copy, nonatomic) NSString *videoURL; // @dynamic videoURL;
@property(copy, nonatomic) NSString *coverVideoURL; // @dynamic coverVideoURL;
@property(copy, nonatomic) NSString *fileId; // @dynamic fileId;

@end

