//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AESearchProductItemTag, AESearchProductTrace, NSString, evaluationItemDTO, logisticsItemDTO, marketingPriceItemDTO, priceItemDTO, tradeItemDTO;

@interface AESearchProductItemDTO : NSObject
{
    _Bool _isBigSaleItem;	// 8 = 0x8
    evaluationItemDTO *_evaluation;	// 16 = 0x10
    NSString *_imgUrl;	// 24 = 0x18
    logisticsItemDTO *_logistics;	// 32 = 0x20
    marketingPriceItemDTO *_marketingPrice;	// 40 = 0x28
    priceItemDTO *_price;	// 48 = 0x30
    NSString *_productId;	// 56 = 0x38
    NSString *_status;	// 64 = 0x40
    NSString *_subject;	// 72 = 0x48
    tradeItemDTO *_trade;	// 80 = 0x50
    NSString *_type;	// 88 = 0x58
    AESearchProductItemTag *_tag;	// 96 = 0x60
    AESearchProductTrace *_trace;	// 104 = 0x68
}

@property(retain, nonatomic) AESearchProductTrace *trace; // @synthesize trace=_trace;
@property(retain, nonatomic) AESearchProductItemTag *tag; // @synthesize tag=_tag;
@property(nonatomic) _Bool isBigSaleItem; // @synthesize isBigSaleItem=_isBigSaleItem;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) tradeItemDTO *trade; // @synthesize trade=_trade;
@property(copy, nonatomic) NSString *subject; // @synthesize subject=_subject;
@property(copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(retain, nonatomic) priceItemDTO *price; // @synthesize price=_price;
@property(retain, nonatomic) marketingPriceItemDTO *marketingPrice; // @synthesize marketingPrice=_marketingPrice;
@property(retain, nonatomic) logisticsItemDTO *logistics; // @synthesize logistics=_logistics;
@property(copy, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
@property(retain, nonatomic) evaluationItemDTO *evaluation; // @synthesize evaluation=_evaluation;
- (void).cxx_destruct;	// IMP=0x0000000100c96dd8

@end

