//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFMoney, NSString;

@interface AEShippingInfoFreightDTO : NSObject
{
    _Bool _tracking;	// 8 = 0x8
    long long _commitDay;	// 16 = 0x10
    NSString *_company;	// 24 = 0x18
    NSString *_currency;	// 32 = 0x20
    unsigned long long _discount;	// 40 = 0x28
    AFMoney *_freightAmount;	// 48 = 0x30
    AFMoney *_previewFreightAmount;	// 56 = 0x38
    NSString *_sendGoodsCountry;	// 64 = 0x40
    NSString *_sendGoodsCountryFullName;	// 72 = 0x48
    NSString *_serviceName;	// 80 = 0x50
    NSString *_time;	// 88 = 0x58
    NSString *_domesticFreight;	// 96 = 0x60
}

@property(retain, nonatomic) NSString *domesticFreight; // @synthesize domesticFreight=_domesticFreight;
@property(nonatomic) _Bool tracking; // @synthesize tracking=_tracking;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;
@property(retain, nonatomic) NSString *sendGoodsCountryFullName; // @synthesize sendGoodsCountryFullName=_sendGoodsCountryFullName;
@property(retain, nonatomic) NSString *sendGoodsCountry; // @synthesize sendGoodsCountry=_sendGoodsCountry;
@property(retain, nonatomic) AFMoney *previewFreightAmount; // @synthesize previewFreightAmount=_previewFreightAmount;
@property(retain, nonatomic) AFMoney *freightAmount; // @synthesize freightAmount=_freightAmount;
@property(nonatomic) unsigned long long discount; // @synthesize discount=_discount;
@property(retain, nonatomic) NSString *currency; // @synthesize currency=_currency;
@property(retain, nonatomic) NSString *company; // @synthesize company=_company;
@property(nonatomic) long long commitDay; // @synthesize commitDay=_commitDay;
- (void).cxx_destruct;	// IMP=0x00000001005fcdc0
@property(readonly, nonatomic) _Bool isFreeShipping;

@end

