//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AESkuService : NSObject
{
}

- (void)getProductSKUListByProductId:(id)arg1 promotionId:(id)arg2 bundleId:(id)arg3 completeBlock:(CDUnknownBlockType)arg4;	// IMP=0x000000010061379c

@end

