//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface AESpellCheck : NSObject
{
    _Bool _spellCheckFlag;	// 8 = 0x8
    NSString *_origQueryString;	// 16 = 0x10
    NSString *_spellCheckQuery;	// 24 = 0x18
    NSArray *_spellCheckResult;	// 32 = 0x20
}

@property(retain, nonatomic) NSArray *spellCheckResult; // @synthesize spellCheckResult=_spellCheckResult;
@property(copy, nonatomic) NSString *spellCheckQuery; // @synthesize spellCheckQuery=_spellCheckQuery;
@property(nonatomic) _Bool spellCheckFlag; // @synthesize spellCheckFlag=_spellCheckFlag;
@property(copy, nonatomic) NSString *origQueryString; // @synthesize origQueryString=_origQueryString;
- (void).cxx_destruct;	// IMP=0x0000000100cdaab4

@end

