//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEStoreSectionViewModel.h"

@class NSArray;

@interface AEStoreBannerSectionViewModel : AEStoreSectionViewModel
{
    NSArray *_imageItems;	// 8 = 0x8
    double _widthHeightRatio;	// 16 = 0x10
    double _edgeMargin;	// 24 = 0x18
}

+ (void)registerCellsForTableView:(id)arg1;	// IMP=0x0000000100d70d2c
@property(nonatomic) double edgeMargin; // @synthesize edgeMargin=_edgeMargin;
@property(nonatomic) double widthHeightRatio; // @synthesize widthHeightRatio=_widthHeightRatio;
@property(retain, nonatomic) NSArray *imageItems; // @synthesize imageItems=_imageItems;
- (void).cxx_destruct;	// IMP=0x0000000100d717fc
- (void)configMarginCell:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100d7173c
- (void)configCell:(id)arg1 whoseReusableIdIs:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100d71630
- (id)cellReusableIdentifier:(id)arg1;	// IMP=0x0000000100d71578
- (long long)cellCount;	// IMP=0x0000000100d71524
- (void)inflateWithItems:(id)arg1;	// IMP=0x0000000100d71294
- (void)inflateWithFields:(id)arg1;	// IMP=0x0000000100d70ed8

@end

