//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AEStoreCollectionCategory : NSObject
{
    NSString *_categoryId;	// 8 = 0x8
    NSString *_categoryName;	// 16 = 0x10
    NSString *_streamId;	// 24 = 0x18
}

@property(retain, nonatomic) NSString *streamId; // @synthesize streamId=_streamId;
@property(retain, nonatomic) NSString *categoryName; // @synthesize categoryName=_categoryName;
@property(retain, nonatomic) NSString *categoryId; // @synthesize categoryId=_categoryId;
- (void).cxx_destruct;	// IMP=0x0000000100402240

@end

