//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFCommandService.h"

@class AEStoreService;

@interface AEStoreRemoveWishlistCommand : AFCommandService
{
    AEStoreService *storeService;	// 8 = 0x8
}

+ (id)paramsDescription;	// IMP=0x0000000100d39278
- (void).cxx_destruct;	// IMP=0x0000000100d39590
- (void)runWithParams:(id)arg1;	// IMP=0x0000000100d392f0

@end

