//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSONModel.h"

@class NSString;

@interface AEStoreCellStyleDTO : JSONModel
{
    NSString *_bottomGap;	// 8 = 0x8
}

+ (_Bool)propertyIsOptional:(id)arg1;	// IMP=0x0000000100d4f688
@property(retain, nonatomic) NSString *bottomGap; // @synthesize bottomGap=_bottomGap;
- (void).cxx_destruct;	// IMP=0x0000000100d4f6b4

@end

