//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTile.h"

@class AEImageTileComponent, AETextTileComponent, NSString;

@interface AEStoreProductComponentViewModel : AEBaseTile
{
    AEImageTileComponent *_imageModel;	// 8 = 0x8
    AETextTileComponent *_nameModel;	// 16 = 0x10
    AETextTileComponent *_priceModel;	// 24 = 0x18
    NSString *_priceTextColor;	// 32 = 0x20
    AETextTileComponent *_originalPriceModel;	// 40 = 0x28
    AETextTileComponent *_discountModel;	// 48 = 0x30
    AEImageTileComponent *_icoModel;	// 56 = 0x38
    AETextTileComponent *_ordersCountModel;	// 64 = 0x40
}

@property(retain, nonatomic) AETextTileComponent *ordersCountModel; // @synthesize ordersCountModel=_ordersCountModel;
@property(retain, nonatomic) AEImageTileComponent *icoModel; // @synthesize icoModel=_icoModel;
@property(retain, nonatomic) AETextTileComponent *discountModel; // @synthesize discountModel=_discountModel;
@property(retain, nonatomic) AETextTileComponent *originalPriceModel; // @synthesize originalPriceModel=_originalPriceModel;
@property(copy, nonatomic) NSString *priceTextColor; // @synthesize priceTextColor=_priceTextColor;
@property(retain, nonatomic) AETextTileComponent *priceModel; // @synthesize priceModel=_priceModel;
@property(retain, nonatomic) AETextTileComponent *nameModel; // @synthesize nameModel=_nameModel;
@property(retain, nonatomic) AEImageTileComponent *imageModel; // @synthesize imageModel=_imageModel;
- (void).cxx_destruct;	// IMP=0x0000000100d033e4

@end

