//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEBaseTileCell.h"

@class AEAutolayoutImageView, AEAutolayoutLabel, AECountDownView;

@interface AETitleTileCell : AEBaseTileCell
{
    AEAutolayoutLabel *_title;	// 8 = 0x8
    AECountDownView *_countDown;	// 16 = 0x10
    AEAutolayoutImageView *_arrow;	// 24 = 0x18
}

@property(retain, nonatomic) AEAutolayoutImageView *arrow; // @synthesize arrow=_arrow;
@property(retain, nonatomic) AECountDownView *countDown; // @synthesize countDown=_countDown;
@property(retain, nonatomic) AEAutolayoutLabel *title; // @synthesize title=_title;
- (void).cxx_destruct;	// IMP=0x00000001004266ac
- (void)prepareForReuse;	// IMP=0x000000010042652c
- (void)renderWithTile:(id)arg1;	// IMP=0x0000000100425b1c
- (void)setupUI;	// IMP=0x0000000100424e28
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100424d68

@end

