//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUGCStyle.h"

@interface AEUGCProfileStyle : AEUGCStyle
{
}

+ (id)appLightFontWithSize:(double)arg1;	// IMP=0x0000000100e9a3f0
+ (id)appBoldFontWithSize:(double)arg1;	// IMP=0x0000000100e9a3d4
+ (id)appSemiboldFontWithSize:(double)arg1;	// IMP=0x0000000100e9a3b8
+ (id)appRegularFontWithSize:(double)arg1;	// IMP=0x0000000100e9a39c
+ (id)colorWithTextTipColor;	// IMP=0x0000000100e9a380
+ (id)colorWithRandomFeedBackground;	// IMP=0x0000000100e9a088
+ (id)colorWithMainText;	// IMP=0x0000000100e9a06c
+ (id)colorWithBuyReward;	// IMP=0x0000000100e9a050
+ (id)colorWithHightlight;	// IMP=0x0000000100e9a034
+ (id)colorWithMainBackground;	// IMP=0x0000000100e9a018

@end

