//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class NSString, UILabel, UIView;

@interface AEUGCShopNewsPostDetailSectionHeaderView : UICollectionReusableView
{
    UIView *_lineView;	// 8 = 0x8
    UILabel *_titleLabel;	// 16 = 0x10
    UILabel *_descriptionLabel;	// 24 = 0x18
    UILabel *_countDownTimeLabel;	// 32 = 0x20
    _Bool _startCountDown;	// 40 = 0x28
    _Bool _hasCountDown;	// 41 = 0x29
    NSString *_title;	// 48 = 0x30
    NSString *_descriptionText;	// 56 = 0x38
    double _countDownStartTimeStamp;	// 64 = 0x40
    double _countDownEndTimeStamp;	// 72 = 0x48
    UIView *_topLine;	// 80 = 0x50
    double _edgeBottom;	// 88 = 0x58
}

+ (struct CGSize)autoLayoutCalculateSizeWithTitle:(id)arg1 description:(id)arg2 hasCountDown:(_Bool)arg3 edgeBottom:(double)arg4 preferredMaxLayoutWidth:(double)arg5;	// IMP=0x0000000100f183b0
@property(nonatomic) double edgeBottom; // @synthesize edgeBottom=_edgeBottom;
@property(retain, nonatomic) UIView *topLine; // @synthesize topLine=_topLine;
@property(nonatomic) double countDownEndTimeStamp; // @synthesize countDownEndTimeStamp=_countDownEndTimeStamp;
@property(nonatomic) double countDownStartTimeStamp; // @synthesize countDownStartTimeStamp=_countDownStartTimeStamp;
@property(nonatomic) _Bool hasCountDown; // @synthesize hasCountDown=_hasCountDown;
@property(copy, nonatomic) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;	// IMP=0x0000000100f185a8
- (void)updateTimeLabel:(id)arg1 time:(double)arg2;	// IMP=0x0000000100f16d24
- (void)updateTimeLabel;	// IMP=0x0000000100f168cc
- (void)stopCountDownTimer;	// IMP=0x0000000100f1685c
- (void)launchCountDownTimer;	// IMP=0x0000000100f167d0
- (void)updateCountDownLabel;	// IMP=0x0000000100f1670c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100f153dc
- (void)dealloc;	// IMP=0x0000000100f1538c

@end

