//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AEUGCPostBannerMaterialDTO : NSObject
{
    NSString *_ID;	// 8 = 0x8
    NSString *_pictureUrl;	// 16 = 0x10
    NSString *_pictureName;	// 24 = 0x18
    unsigned long long _categoryId;	// 32 = 0x20
    NSString *_importDate;	// 40 = 0x28
    unsigned long long _widht;	// 48 = 0x30
    unsigned long long _height;	// 56 = 0x38
}

@property(nonatomic) unsigned long long height; // @synthesize height=_height;
@property(nonatomic) unsigned long long widht; // @synthesize widht=_widht;
@property(copy, nonatomic) NSString *importDate; // @synthesize importDate=_importDate;
@property(nonatomic) unsigned long long categoryId; // @synthesize categoryId=_categoryId;
@property(copy, nonatomic) NSString *pictureName; // @synthesize pictureName=_pictureName;
@property(copy, nonatomic) NSString *pictureUrl; // @synthesize pictureUrl=_pictureUrl;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;	// IMP=0x0000000100e51c28
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100e51994

@end

