//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIButton, UILabel;

@interface AEUGCFZSignInCell : UICollectionViewCell
{
    UIButton *_signInButton;	// 8 = 0x8
    UILabel *_noLoginTitleLabel;	// 16 = 0x10
    UILabel *_noLoginDescLabel;	// 24 = 0x18
}

@property(retain, nonatomic) UILabel *noLoginDescLabel; // @synthesize noLoginDescLabel=_noLoginDescLabel;
@property(retain, nonatomic) UILabel *noLoginTitleLabel; // @synthesize noLoginTitleLabel=_noLoginTitleLabel;
@property(retain, nonatomic) UIButton *signInButton; // @synthesize signInButton=_signInButton;
- (void).cxx_destruct;	// IMP=0x00000001006a2e14
- (void)awakeFromNib;	// IMP=0x00000001006a2a1c

@end

