//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSArray, NSString, UICollectionView, UIColor;

@interface AEUGCBrandsContainer : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    NSArray *_dataSource;	// 8 = 0x8
    id <AEUGCBrandsContainerDelegate> _delegate;	// 16 = 0x10
    UIColor *_collectionViewBackgroundColor;	// 24 = 0x18
    UICollectionView *_collectionView;	// 32 = 0x20
}

@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UIColor *collectionViewBackgroundColor; // @synthesize collectionViewBackgroundColor=_collectionViewBackgroundColor;
@property(nonatomic) __weak id <AEUGCBrandsContainerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;	// IMP=0x00000001007338e8
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100733560
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x00000001007334d8
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x00000001007333d4
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100733388
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100733380
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100733168

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

