//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AEUGCPostPicTextIntroEditView, NSString;

@protocol AEUGCPostPicTextIntroEditViewDelegate <NSObject>

@optional
- (void)introEditView:(AEUGCPostPicTextIntroEditView *)arg1 didChangeHeight:(double)arg2;
- (_Bool)introEditViewGuidanceShouldReturn:(AEUGCPostPicTextIntroEditView *)arg1;
- (void)introEditView:(AEUGCPostPicTextIntroEditView *)arg1 didChangeGuidance:(NSString *)arg2;
- (void)introEditViewDidEndGuidanceEditing:(AEUGCPostPicTextIntroEditView *)arg1;
- (void)introEditViewDidBeginGuidanceEditing:(AEUGCPostPicTextIntroEditView *)arg1;
- (void)introEditView:(AEUGCPostPicTextIntroEditView *)arg1 didChangeTitle:(NSString *)arg2;
- (void)introEditViewDidEndTitleEditing:(AEUGCPostPicTextIntroEditView *)arg1;
- (void)introEditViewDidBeginTitleEditing:(AEUGCPostPicTextIntroEditView *)arg1;
@end

