//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AIFCountry, NSString;

@interface AEUGCCommentViewModel : NSObject
{
    _Bool _isDelete;	// 8 = 0x8
    _Bool _deleted;	// 9 = 0x9
    NSString *_commentId;	// 16 = 0x10
    NSString *_commenterMemberSeq;	// 24 = 0x18
    NSString *_content;	// 32 = 0x20
    NSString *_translateContent;	// 40 = 0x28
    NSString *_postId;	// 48 = 0x30
    NSString *_replyCommentId;	// 56 = 0x38
    long long _replyTime;	// 64 = 0x40
    NSString *_replyTimeFromNow;	// 72 = 0x48
    NSString *_userAvatar;	// 80 = 0x50
    NSString *_userName;	// 88 = 0x58
    NSString *_replyName;	// 96 = 0x60
    NSString *_replyProfileUrl;	// 104 = 0x68
    AIFCountry *_userCountry;	// 112 = 0x70
    long long _commentIndex;	// 120 = 0x78
}

@property(nonatomic) long long commentIndex; // @synthesize commentIndex=_commentIndex;
@property(nonatomic) _Bool deleted; // @synthesize deleted=_deleted;
@property(retain, nonatomic) AIFCountry *userCountry; // @synthesize userCountry=_userCountry;
@property(copy, nonatomic) NSString *replyProfileUrl; // @synthesize replyProfileUrl=_replyProfileUrl;
@property(copy, nonatomic) NSString *replyName; // @synthesize replyName=_replyName;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *userAvatar; // @synthesize userAvatar=_userAvatar;
@property(copy, nonatomic) NSString *replyTimeFromNow; // @synthesize replyTimeFromNow=_replyTimeFromNow;
@property(nonatomic) long long replyTime; // @synthesize replyTime=_replyTime;
@property(copy, nonatomic) NSString *replyCommentId; // @synthesize replyCommentId=_replyCommentId;
@property(copy, nonatomic) NSString *postId; // @synthesize postId=_postId;
@property(nonatomic) _Bool isDelete; // @synthesize isDelete=_isDelete;
@property(copy, nonatomic) NSString *translateContent; // @synthesize translateContent=_translateContent;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *commenterMemberSeq; // @synthesize commenterMemberSeq=_commenterMemberSeq;
@property(copy, nonatomic) NSString *commentId; // @synthesize commentId=_commentId;
- (void).cxx_destruct;	// IMP=0x0000000100750038

@end

