//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel;

@interface AEUGCShopNewsNoItemCell : UICollectionViewCell
{
    UIImageView *_iconImageView;	// 8 = 0x8
    UILabel *_messageLabel;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100f1a864
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100f1a03c

@end

