//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AEUGCVideoLiveReplyInfoDTO : NSObject
{
    NSString *_memberSeq;	// 8 = 0x8
    NSString *_avatarUrl;	// 16 = 0x10
    NSString *_nickname;	// 24 = 0x18
    long long _createTime;	// 32 = 0x20
    NSString *_content;	// 40 = 0x28
    NSString *_picName;	// 48 = 0x30
    NSString *_linkUrl;	// 56 = 0x38
    NSString *_productId;	// 64 = 0x40
    NSString *_proMainPicUrl;	// 72 = 0x48
    NSString *_proTitle;	// 80 = 0x50
    NSString *_displayPrice;	// 88 = 0x58
}

@property(copy, nonatomic) NSString *displayPrice; // @synthesize displayPrice=_displayPrice;
@property(copy, nonatomic) NSString *proTitle; // @synthesize proTitle=_proTitle;
@property(copy, nonatomic) NSString *proMainPicUrl; // @synthesize proMainPicUrl=_proMainPicUrl;
@property(copy, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(copy, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(copy, nonatomic) NSString *picName; // @synthesize picName=_picName;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) long long createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(copy, nonatomic) NSString *avatarUrl; // @synthesize avatarUrl=_avatarUrl;
@property(copy, nonatomic) NSString *memberSeq; // @synthesize memberSeq=_memberSeq;
- (void).cxx_destruct;	// IMP=0x0000000100fc7cbc

@end

