//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUGCComponentViewModel.h"

@class NSDictionary, NSString;

@protocol AEUGCSlideBlockItemViewModel <AEUGCComponentViewModel>
@property(readonly, nonatomic) NSString *desc;
@property(readonly, nonatomic) NSDictionary *extendInfo;
@property(readonly, nonatomic) NSString *cmdUrl;
@property(readonly, nonatomic) NSString *content;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) NSString *imgUrl;

@optional
@property(nonatomic) _Bool selected;
@end

