//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "AEUGCComponentProxy.h"

@class AEUGCAvatarView, AEUGCCommentButton, AEUGCLikeActionButton, AEUGCTranslatedButton, NSString, UIImageView, UILabel;

@interface AEUGCRecommendPostCardTableViewCell : UITableViewCell <AEUGCComponentProxy>
{
    AEUGCAvatarView *_avatarView;	// 8 = 0x8
    UILabel *_nickNameLabel;	// 16 = 0x10
    UILabel *_timeLabel;	// 24 = 0x18
    UIImageView *_contentImageView;	// 32 = 0x20
    UILabel *_titleLabel;	// 40 = 0x28
    UILabel *_sumaryLabel;	// 48 = 0x30
    AEUGCTranslatedButton *_translateButton;	// 56 = 0x38
    AEUGCLikeActionButton *_likeActionButton;	// 64 = 0x40
    AEUGCCommentButton *_commentButton;	// 72 = 0x48
    UILabel *_topTitleLabel;	// 80 = 0x50
}

@property(retain, nonatomic) UILabel *topTitleLabel; // @synthesize topTitleLabel=_topTitleLabel;
@property(retain, nonatomic) AEUGCCommentButton *commentButton; // @synthesize commentButton=_commentButton;
@property(retain, nonatomic) AEUGCLikeActionButton *likeActionButton; // @synthesize likeActionButton=_likeActionButton;
@property(retain, nonatomic) AEUGCTranslatedButton *translateButton; // @synthesize translateButton=_translateButton;
@property(retain, nonatomic) UILabel *sumaryLabel; // @synthesize sumaryLabel=_sumaryLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *contentImageView; // @synthesize contentImageView=_contentImageView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *nickNameLabel; // @synthesize nickNameLabel=_nickNameLabel;
@property(retain, nonatomic) AEUGCAvatarView *avatarView; // @synthesize avatarView=_avatarView;
- (void).cxx_destruct;	// IMP=0x0000000100700814
- (void)bindModel:(id)arg1;	// IMP=0x0000000100700110
- (void)awakeFromNib;	// IMP=0x0000000100700040

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

