//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AEUGCSlideBlockItemViewModel.h"

@class AEUGCDaRenShowBannerDTO, NSDictionary, NSString;

@interface AEUGCDaRenShowBannerItemViewModel : NSObject <AEUGCSlideBlockItemViewModel>
{
    AEUGCDaRenShowBannerDTO *_dto;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100645934
@property(readonly, nonatomic) NSString *imgUrl;
@property(readonly, nonatomic) NSString *content;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) NSString *cmdUrl;
- (id)initWithDic:(id)arg1;	// IMP=0x0000000100645838

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) NSString *desc;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSDictionary *extendInfo;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool selected;
@property(readonly) Class superclass;

@end

