//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUGCAdapterViewController.h"

#import "AEUGCProductListCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AEUGCProductListPresenter, AEUGCSearchResultFloattingBar, NSArray, NSMutableArray, NSString, UITableView;

@interface AEUGCSearchResultViewController : AEUGCAdapterViewController <UITableViewDelegate, UITableViewDataSource, AEUGCProductListCellDelegate>
{
    _Bool _isLoading;	// 8 = 0x8
    id <AEUGCPostProductAddtionDelegate> _delegate;	// 16 = 0x10
    NSArray *_currentAddedProductItems;	// 24 = 0x18
    NSString *_searchKey;	// 32 = 0x20
    UITableView *_tableView;	// 40 = 0x28
    NSMutableArray *_searchResults;	// 48 = 0x30
    AEUGCProductListPresenter *_searchPresenter;	// 56 = 0x38
    AEUGCSearchResultFloattingBar *_floattingBar;	// 64 = 0x40
    NSMutableArray *_currentSelectedItems;	// 72 = 0x48
}

@property(retain, nonatomic) NSMutableArray *currentSelectedItems; // @synthesize currentSelectedItems=_currentSelectedItems;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) AEUGCSearchResultFloattingBar *floattingBar; // @synthesize floattingBar=_floattingBar;
@property(retain, nonatomic) AEUGCProductListPresenter *searchPresenter; // @synthesize searchPresenter=_searchPresenter;
@property(retain, nonatomic) NSMutableArray *searchResults; // @synthesize searchResults=_searchResults;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSString *searchKey; // @synthesize searchKey=_searchKey;
@property(retain, nonatomic) NSArray *currentAddedProductItems; // @synthesize currentAddedProductItems=_currentAddedProductItems;
@property(nonatomic) __weak id <AEUGCPostProductAddtionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x0000000100e31108
- (id)spmB;	// IMP=0x0000000100e30f18
- (id)pageTrackName;	// IMP=0x0000000100e30eec
- (void)backAction:(id)arg1;	// IMP=0x0000000100e30e9c
- (void)nextAction:(id)arg1;	// IMP=0x0000000100e30c48
- (void)updateSelectionStatus:(id)arg1;	// IMP=0x0000000100e309dc
- (void)didDeselectProductItem:(id)arg1;	// IMP=0x0000000100e30338
- (void)didSelectProductItem:(id)arg1;	// IMP=0x0000000100e2ff00
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x0000000100e2fb70
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x0000000100e2fa5c
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x0000000100e2fa10
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100e2f9dc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100e2f9a8
- (void)viewDidLoad;	// IMP=0x0000000100e2ee9c
- (id)initWithSearchKey:(id)arg1;	// IMP=0x0000000100e2ee24
- (id)initWithParam:(id)arg1;	// IMP=0x0000000100e2ecac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

