//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AEUGCHomeViewModelFactory : NSObject
{
}

+ (id)viewModelByParam:(id)arg1;	// IMP=0x0000000100dc0320

@end

