//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSMutableArray, UIImageView, UILabel, UIView;

@interface AEUGCCollectionLikeViewCell : UICollectionViewCell
{
    _Bool _didSetupConstraints;	// 8 = 0x8
    long long _likeCount;	// 16 = 0x10
    UIView *_topLineView;	// 24 = 0x18
    UIView *_bottomLineView;	// 32 = 0x20
    UIImageView *_likeview;	// 40 = 0x28
    UILabel *_likeLabel;	// 48 = 0x30
    UIImageView *_headerview;	// 56 = 0x38
    UIView *_indicatorview;	// 64 = 0x40
    NSMutableArray *_likeViewArr;	// 72 = 0x48
    UILabel *_allLabel;	// 80 = 0x50
}

@property(nonatomic) _Bool didSetupConstraints; // @synthesize didSetupConstraints=_didSetupConstraints;
@property(retain, nonatomic) UILabel *allLabel; // @synthesize allLabel=_allLabel;
@property(retain, nonatomic) NSMutableArray *likeViewArr; // @synthesize likeViewArr=_likeViewArr;
@property(retain, nonatomic) UIView *indicatorview; // @synthesize indicatorview=_indicatorview;
@property(retain, nonatomic) UIImageView *headerview; // @synthesize headerview=_headerview;
@property(retain, nonatomic) UILabel *likeLabel; // @synthesize likeLabel=_likeLabel;
@property(retain, nonatomic) UIImageView *likeview; // @synthesize likeview=_likeview;
@property(retain, nonatomic) UIView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(retain, nonatomic) UIView *topLineView; // @synthesize topLineView=_topLineView;
@property(nonatomic) long long likeCount; // @synthesize likeCount=_likeCount;
- (void).cxx_destruct;	// IMP=0x0000000100743e8c
- (void)updateConstraints;	// IMP=0x00000001007430f8
- (void)bindData:(id)arg1;	// IMP=0x00000001007428a4
- (void)layoutSubviews;	// IMP=0x0000000100742870
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001007425ec

@end

