//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface AEUGCTipsView : UIView
{
    UIView *_bgView;	// 8 = 0x8
    UIImageView *_arrowImageView;	// 16 = 0x10
    UIView *_splitLine;	// 24 = 0x18
    struct UIEdgeInsets _edgeInsets;	// 32 = 0x20
    UILabel *_tipsLabel;	// 64 = 0x40
    UIButton *_confirmButton;	// 72 = 0x48
}

+ (id)TipsInputViewWithTips:(id)arg1;	// IMP=0x00000001007cac78
@property(readonly, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(readonly, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
- (void).cxx_destruct;	// IMP=0x00000001007cc03c
- (void)configAutoLayout;	// IMP=0x00000001007cb208
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001007cad1c
- (void)dealloc;	// IMP=0x00000001007cac44

@end

