//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "AEUGCComponentProxy.h"

@class AEUGCCouponView, NSString, UILabel;

@interface AEUGCCollectionCouponViewCell : UICollectionViewCell <AEUGCComponentProxy>
{
    AEUGCCouponView *_couponView;	// 8 = 0x8
    UILabel *_titleLabel;	// 16 = 0x10
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) AEUGCCouponView *couponView; // @synthesize couponView=_couponView;
- (void).cxx_destruct;	// IMP=0x0000000100671c2c
- (void)bindModel:(id)arg1;	// IMP=0x0000000100671790
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100670df0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

