//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

#import "AEUGCDecorationFlowLayoutDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class AEUGCFormalVenueViewModel, NSArray, NSString, UICollectionView, UIImage, UIRefreshControl;

@interface AEUGCFormalVenueViewController : AEUIViewController <UICollectionViewDelegate, UICollectionViewDataSource, AEUGCDecorationFlowLayoutDelegate>
{
    _Bool _navigationBarCanUpdateAppearance;	// 8 = 0x8
    UICollectionView *_collectionView;	// 16 = 0x10
    NSArray *_sections;	// 24 = 0x18
    AEUGCFormalVenueViewModel *_viewModel;	// 32 = 0x20
    UIRefreshControl *_refreshControl;	// 40 = 0x28
    double _navigationBarAlpha;	// 48 = 0x30
    UIImage *_navigationBarBackgroundImage;	// 56 = 0x38
}

@property(nonatomic) _Bool navigationBarCanUpdateAppearance; // @synthesize navigationBarCanUpdateAppearance=_navigationBarCanUpdateAppearance;
@property(retain, nonatomic) UIImage *navigationBarBackgroundImage; // @synthesize navigationBarBackgroundImage=_navigationBarBackgroundImage;
@property(nonatomic) double navigationBarAlpha; // @synthesize navigationBarAlpha=_navigationBarAlpha;
@property(retain, nonatomic) UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property(retain, nonatomic) AEUGCFormalVenueViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;	// IMP=0x0000000100699dd8
- (id)pageTrackName;	// IMP=0x0000000100699c24
- (void)shopAction:(id)arg1;	// IMP=0x00000001006997e4
- (void)searchAction:(id)arg1;	// IMP=0x0000000100699794
- (void)refresh;	// IMP=0x000000010069943c
- (id)collectionView:(id)arg1 backgroundColorForDecorationInSection:(long long)arg2;	// IMP=0x000000010069940c
- (id)collectionView:(id)arg1 backgroundImageForDecorationInSection:(long long)arg2;	// IMP=0x0000000100699404
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForBackgroundInSection:(long long)arg3;	// IMP=0x00000001006992e0
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x000000010069900c
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100698d54
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;	// IMP=0x0000000100698c14
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;	// IMP=0x0000000100698b44
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x000000010069876c
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x00000001006982f8
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x000000010069807c
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100698030
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x000000010069797c
- (id)curNaviItem;	// IMP=0x00000001006978b8
- (id)curNaviCtr;	// IMP=0x00000001006977f4
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001006976f8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001006973a8
- (void)viewDidLoad;	// IMP=0x0000000100696fb0
- (id)initWithParam:(id)arg1;	// IMP=0x0000000100696e80

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

