//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUGCAdapterViewController.h"

#import "AEUGCPopoverListViewDelegate.h"
#import "AEUGCSelectTypeCollectionViewCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class AEUGCPopoverListView, AEUGCSelectTypeCollectionViewCell, AEUGCShowYourIdeaBannersViewModel, AEUGCShowYourIdeaCardListViewModel, HMSegmentedControl, NSDictionary, NSMutableArray, NSString, UIActivityIndicatorView, UIButton, UICollectionView;

@interface AEUGCShowYourIdeaViewController : AEUGCAdapterViewController <UICollectionViewDelegateFlowLayout, UICollectionViewDelegate, UICollectionViewDataSource, AEUGCPopoverListViewDelegate, AEUGCSelectTypeCollectionViewCellDelegate>
{
    NSDictionary *_params;	// 8 = 0x8
    UIButton *_postButton;	// 16 = 0x10
    NSString *_commentListVcActionUUID;	// 24 = 0x18
    NSString *_postDoneNotificationUUID;	// 32 = 0x20
    _Bool _hideSegment;	// 40 = 0x28
    HMSegmentedControl *_segmentedControl;	// 48 = 0x30
    UICollectionView *_collectionView;	// 56 = 0x38
    AEUGCShowYourIdeaBannersViewModel *_bannersViewModel;	// 64 = 0x40
    NSMutableArray *_popoverItems;	// 72 = 0x48
    AEUGCShowYourIdeaCardListViewModel *_cardlistViewModel;	// 80 = 0x50
    AEUGCSelectTypeCollectionViewCell *_selectionCell;	// 88 = 0x58
    AEUGCPopoverListView *_popoverListView;	// 96 = 0x60
    UIActivityIndicatorView *_indicatorView;	// 104 = 0x68
}

+ (_Bool)canCreatePicTextPost;	// IMP=0x0000000100d98d0c
@property(nonatomic) _Bool hideSegment; // @synthesize hideSegment=_hideSegment;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) AEUGCPopoverListView *popoverListView; // @synthesize popoverListView=_popoverListView;
@property(retain, nonatomic) AEUGCSelectTypeCollectionViewCell *selectionCell; // @synthesize selectionCell=_selectionCell;
@property(retain, nonatomic) AEUGCShowYourIdeaCardListViewModel *cardlistViewModel; // @synthesize cardlistViewModel=_cardlistViewModel;
@property(copy, nonatomic) NSMutableArray *popoverItems; // @synthesize popoverItems=_popoverItems;
@property(retain, nonatomic) AEUGCShowYourIdeaBannersViewModel *bannersViewModel; // @synthesize bannersViewModel=_bannersViewModel;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) HMSegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
- (void).cxx_destruct;	// IMP=0x0000000100d9af98
- (id)pageTrackName;	// IMP=0x0000000100d9ad38
- (id)showMode;	// IMP=0x0000000100d9ad0c
- (void)postDoneNotification:(id)arg1;	// IMP=0x0000000100d9a9c0
- (void)updateCommentStatus:(id)arg1;	// IMP=0x0000000100d9a8d8
- (void)newPostAction:(id)arg1;	// IMP=0x0000000100d9a8cc
- (void)excuteNewPostAction;	// IMP=0x0000000100d9a348
- (void)popListViewDismissAction:(id)arg1;	// IMP=0x0000000100d9a330
- (void)popListView:(id)arg1 DidSelectItemAtIndex:(unsigned long long)arg2;	// IMP=0x0000000100d99dd4
- (void)typeButtonPressed:(id)arg1;	// IMP=0x0000000100d99adc
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x0000000100d998b8
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x0000000100d996fc
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100d995a4
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100d990a8
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100d99034
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100d9902c
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;	// IMP=0x0000000100d98f90
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x0000000100d98e24
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;	// IMP=0x0000000100d98df4
- (id)cardCell:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100d97a88
- (void)prepareLoadListData:(CDUnknownBlockType)arg1;	// IMP=0x0000000100d9780c
- (void)loadData;	// IMP=0x0000000100d9723c
- (void)configAutoLayout;	// IMP=0x0000000100d962b8
- (void)configUI;	// IMP=0x0000000100d96218
- (void)viewDidLoad;	// IMP=0x0000000100d95544
- (id)initWithParam:(id)arg1;	// IMP=0x0000000100d94fbc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

