//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "AEUGCComponentProxy.h"
#import "AEUGCSliderDelegate.h"

@class AEUGCSlider, NSString, UILabel;

@interface AEUGCRecommendPostScrollTableViewCell : UITableViewCell <AEUGCSliderDelegate, AEUGCComponentProxy>
{
    id <AEUGCRecommendPostScrollTableViewModel> _viewModel;	// 8 = 0x8
    AEUGCSlider *_slider;	// 16 = 0x10
    UILabel *_topTitleLabel;	// 24 = 0x18
}

@property(retain, nonatomic) UILabel *topTitleLabel; // @synthesize topTitleLabel=_topTitleLabel;
@property(retain, nonatomic) AEUGCSlider *slider; // @synthesize slider=_slider;
- (void).cxx_destruct;	// IMP=0x0000000100700d64
- (void)onSliderElementTapped:(id)arg1 withIndex:(long long)arg2;	// IMP=0x0000000100700cd0
- (id)createSliderElement:(id)arg1;	// IMP=0x0000000100700bc8
- (void)bindModel:(id)arg1;	// IMP=0x0000000100700ae0
- (void)awakeFromNib;	// IMP=0x0000000100700900

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

