//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class AEUGCLabel, UILabel;

@interface AEUGCPostDeleteCommentCell : UITableViewCell
{
    UILabel *_titleLabel;	// 8 = 0x8
    AEUGCLabel *_floorLabel;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100e1cd34
- (void)setFloorIndex:(long long)arg1;	// IMP=0x0000000100e1ccc8
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100e1c31c

@end

