//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AEUIViewController.h"

#import "AEUGCVideoLPLiveCellDelegate.h"
#import "AFCommandViewController.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class AEUGCLiveRoomErrorView, AEUGCPostFollowService, AEUGCVideoService, NSMutableArray, NSMutableDictionary, NSString, UICollectionView;

@interface AEUGCVideoStoreLiveViewController : AEUIViewController <UICollectionViewDelegate, UICollectionViewDataSource, AEUGCVideoLPLiveCellDelegate, AFCommandViewController>
{
    _Bool _bottomLoading;	// 8 = 0x8
    _Bool _loadLiveListDone;	// 9 = 0x9
    _Bool _loadLiveListError;	// 10 = 0xa
    _Bool _hasNext;	// 11 = 0xb
    UICollectionView *_collectionView;	// 16 = 0x10
    AEUGCLiveRoomErrorView *_errorView;	// 24 = 0x18
    CDUnknownBlockType _errorRefreshBtnClickedBlock;	// 32 = 0x20
    NSMutableArray *_liveSceneArr;	// 40 = 0x28
    AEUGCVideoService *_videoService;	// 48 = 0x30
    NSString *_loadLiveListErrorMsg;	// 56 = 0x38
    NSString *_nextStartRowKey;	// 64 = 0x40
    NSString *_currentLanguage;	// 72 = 0x48
    NSMutableDictionary *_cellHeightCache;	// 80 = 0x50
    NSString *_lpId;	// 88 = 0x58
    AEUGCPostFollowService *_followService;	// 96 = 0x60
}

@property(retain, nonatomic) AEUGCPostFollowService *followService; // @synthesize followService=_followService;
@property(copy, nonatomic) NSString *lpId; // @synthesize lpId=_lpId;
@property(retain, nonatomic) NSMutableDictionary *cellHeightCache; // @synthesize cellHeightCache=_cellHeightCache;
@property(nonatomic) _Bool hasNext; // @synthesize hasNext=_hasNext;
@property(copy, nonatomic) NSString *currentLanguage; // @synthesize currentLanguage=_currentLanguage;
@property(copy, nonatomic) NSString *nextStartRowKey; // @synthesize nextStartRowKey=_nextStartRowKey;
@property(copy, nonatomic) NSString *loadLiveListErrorMsg; // @synthesize loadLiveListErrorMsg=_loadLiveListErrorMsg;
@property(nonatomic) _Bool loadLiveListError; // @synthesize loadLiveListError=_loadLiveListError;
@property(nonatomic) _Bool loadLiveListDone; // @synthesize loadLiveListDone=_loadLiveListDone;
@property(retain, nonatomic) AEUGCVideoService *videoService; // @synthesize videoService=_videoService;
@property(nonatomic) _Bool bottomLoading; // @synthesize bottomLoading=_bottomLoading;
@property(retain, nonatomic) NSMutableArray *liveSceneArr; // @synthesize liveSceneArr=_liveSceneArr;
@property(copy, nonatomic) CDUnknownBlockType errorRefreshBtnClickedBlock; // @synthesize errorRefreshBtnClickedBlock=_errorRefreshBtnClickedBlock;
@property(retain, nonatomic) AEUGCLiveRoomErrorView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;	// IMP=0x0000000100fc791c
- (void)removeSectionTitle:(id)arg1;	// IMP=0x0000000100fc6ed0
- (id)parseLiveSceneList:(id)arg1 deltaList:(id)arg2;	// IMP=0x0000000100fc6b98
- (void)onTopRefreshControlChanged:(id)arg1;	// IMP=0x0000000100fc6b88
- (void)onBottomRefreshControlChanged:(id)arg1;	// IMP=0x0000000100fc6af4
- (_Bool)containesLiveScene:(id)arg1;	// IMP=0x0000000100fc6880
- (void)hideErrorMsg;	// IMP=0x0000000100fc683c
- (void)showErrorMsg:(id)arg1 refreshAction:(CDUnknownBlockType)arg2;	// IMP=0x0000000100fc6734
- (void)loadLiveListFromNetwork:(id)arg1;	// IMP=0x0000000100fc5e3c
- (id)pageTrackParams;	// IMP=0x0000000100fc5d74
- (id)pageTrackName;	// IMP=0x0000000100fc5d48
- (void)setupConstraints;	// IMP=0x0000000100fc5908
- (void)followButtonTapped:(id)arg1;	// IMP=0x0000000100fc4d6c
- (void)remindMeButtonTapped:(id)arg1;	// IMP=0x0000000100fc4710
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100fc4484
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100fc4438
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100fc4430
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0000000100fc4184
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;	// IMP=0x0000000100fc417c
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;	// IMP=0x0000000100fc4174
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0000000100fc3f98
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;	// IMP=0x0000000100fc3ef4
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;	// IMP=0x0000000100fc3ee8
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x0000000100fc3d60
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;	// IMP=0x0000000100fc3d4c
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x0000000100fc3958
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100fc3924
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100fc3874
- (void)viewDidLoad;	// IMP=0x0000000100fc35c4
- (id)initWithParam:(id)arg1;	// IMP=0x0000000100fc34cc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

