//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AEUGCVideoLPCollectionViewController, NSArray, NSString, UIScrollView;

@protocol AEUGCVideoLPCollectionViewControllerDelegate <NSObject>
- (void)collectionTopRefresh;
- (void)collectionViewDidAppear;
- (void)collectionViewFetchError;
- (void)collectionViewFetchBannerDone:(AEUGCVideoLPCollectionViewController *)arg1;
- (void)collectionViewFetchLanguageListDone:(AEUGCVideoLPCollectionViewController *)arg1 withLanguageList:(NSArray *)arg2 withTitle:(NSString *)arg3;
- (void)collectionViewDidScroll:(UIScrollView *)arg1;
@end

