//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView;

@interface AEUGCShopNewsBannerCell : UICollectionViewCell
{
    UIImageView *_imageView;	// 8 = 0x8
}

@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;	// IMP=0x0000000100eef83c
- (void)loadImageWithURL:(id)arg1 placeholderImage:(id)arg2;	// IMP=0x0000000100eef438
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100eeef60

@end

