//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AITMemberDTO, NSString;

@protocol AEUGCMemberCellClickDelegate <NSObject>
- (void)clickyyFeaturelabel:(AITMemberDTO *)arg1 feature:(NSString *)arg2;
- (void)clickportraitView:(AITMemberDTO *)arg1;
@end

