//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AFCommandExecutor.h"

@class NSString;

@interface AEViewControllerExecutor : NSObject <AFCommandExecutor>
{
}

+ (unsigned long long)execute:(id)arg1 withParam:(id)arg2;	// IMP=0x0000000100a42bd0
+ (id)displayModeForViewController:(id)arg1 params:(id)arg2;	// IMP=0x0000000100a429b4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

