//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSSet;

@interface AFSecurityPolicy : NSObject <NSSecureCoding, NSCopying>
{
    _Bool _allowInvalidCertificates;	// 8 = 0x8
    _Bool _validatesDomainName;	// 9 = 0x9
    unsigned long long _SSLPinningMode;	// 16 = 0x10
    NSSet *_pinnedCertificates;	// 24 = 0x18
    NSSet *_pinnedPublicKeys;	// 32 = 0x20
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001008a6234
+ (id)keyPathsForValuesAffectingPinnedPublicKeys;	// IMP=0x00000001008a6218
+ (id)policyWithPinningMode:(unsigned long long)arg1 withPinnedCertificates:(id)arg2;	// IMP=0x00000001008a5594
+ (id)policyWithPinningMode:(unsigned long long)arg1;	// IMP=0x00000001008a5524
+ (id)defaultPolicy;	// IMP=0x00000001008a54dc
+ (id)defaultPinnedCertificates;	// IMP=0x00000001008a53dc
+ (id)certificatesInBundle:(id)arg1;	// IMP=0x00000001008a51f0
@property(retain, nonatomic) NSSet *pinnedPublicKeys; // @synthesize pinnedPublicKeys=_pinnedPublicKeys;
@property(nonatomic) _Bool validatesDomainName; // @synthesize validatesDomainName=_validatesDomainName;
@property(nonatomic) _Bool allowInvalidCertificates; // @synthesize allowInvalidCertificates=_allowInvalidCertificates;
@property(retain, nonatomic) NSSet *pinnedCertificates; // @synthesize pinnedCertificates=_pinnedCertificates;
@property(nonatomic) unsigned long long SSLPinningMode; // @synthesize SSLPinningMode=_SSLPinningMode;
- (void).cxx_destruct;	// IMP=0x00000001008a67c4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001008a65f4
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001008a6440
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001008a623c
- (_Bool)evaluateServerTrust:(struct __SecTrust *)arg1 forDomain:(id)arg2;	// IMP=0x00000001008a59a4
- (id)init;	// IMP=0x00000001008a561c

@end

