//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AIFAPIResponse, NSDictionary, NSString;

@interface AIFAPIRequestContext : NSObject
{
    _Bool _isAsyc;	// 8 = 0x8
    int _method;	// 12 = 0xc
    int _protocol;	// 16 = 0x10
    NSString *_endPoint;	// 24 = 0x18
    NSString *_host;	// 32 = 0x20
    NSDictionary *_requestParams;	// 40 = 0x28
    NSDictionary *_origRequestParams;	// 48 = 0x30
    NSDictionary *_requestHeaders;	// 56 = 0x38
    NSString *_requestId;	// 64 = 0x40
    CDUnknownBlockType _aif_api_callback;	// 72 = 0x48
    AIFAPIResponse *_response;	// 80 = 0x50
}

@property(retain, nonatomic) AIFAPIResponse *response; // @synthesize response=_response;
@property(copy, nonatomic) CDUnknownBlockType aif_api_callback; // @synthesize aif_api_callback=_aif_api_callback;
@property(copy, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
@property(copy, nonatomic) NSDictionary *requestHeaders; // @synthesize requestHeaders=_requestHeaders;
@property(copy, nonatomic) NSDictionary *origRequestParams; // @synthesize origRequestParams=_origRequestParams;
@property(copy, nonatomic) NSDictionary *requestParams; // @synthesize requestParams=_requestParams;
@property(nonatomic) int protocol; // @synthesize protocol=_protocol;
@property(nonatomic) int method; // @synthesize method=_method;
@property(nonatomic) _Bool isAsyc; // @synthesize isAsyc=_isAsyc;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
@property(copy, nonatomic) NSString *endPoint; // @synthesize endPoint=_endPoint;
- (void).cxx_destruct;	// IMP=0x000000010101d1ac
- (id)init;	// IMP=0x000000010101cfdc

@end

