//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface AIFNetworkTraceroute : NSObject
{
    unsigned long long _ttl;	// 8 = 0x8
    double _timeout;	// 16 = 0x10
    _Bool _isRunning;	// 24 = 0x18
    int _sendSocket;	// 28 = 0x1c
    int _recvSocket;	// 32 = 0x20
    NSString *_host;	// 40 = 0x28
    unsigned long long _ttlMax;	// 48 = 0x30
    unsigned long long _maxAttempts;	// 56 = 0x38
    NSData *_hostAddress;	// 64 = 0x40
}

@property(retain, nonatomic) NSData *hostAddress; // @synthesize hostAddress=_hostAddress;
@property int recvSocket; // @synthesize recvSocket=_recvSocket;
@property int sendSocket; // @synthesize sendSocket=_sendSocket;
@property _Bool isRunning; // @synthesize isRunning=_isRunning;
@property unsigned long long maxAttempts; // @synthesize maxAttempts=_maxAttempts;
@property unsigned long long ttlMax; // @synthesize ttlMax=_ttlMax;
@property(copy, nonatomic) NSString *host; // @synthesize host=_host;
- (void).cxx_destruct;	// IMP=0x0000000101050ac8
- (void)dealloc;	// IMP=0x00000001010508e0
- (id)getErrorByCode:(long long)arg1 reason:(id)arg2;	// IMP=0x00000001010507f0
- (struct sockaddr)formatAddrP2N:(id)arg1 isIPv6:(_Bool *)arg2;	// IMP=0x000000010105063c
- (id)formatAddrN2P:(struct sockaddr)arg1;	// IMP=0x0000000101050534
- (void)stopTrace;	// IMP=0x0000000101050524
- (void)startTraceroute:(CDUnknownBlockType)arg1;	// IMP=0x000000010104f8ec
- (unsigned long long)ttl;	// IMP=0x000000010104f8a0
- (void)setTtl:(unsigned long long)arg1;	// IMP=0x000000010104f800
@property double timeout;

@end

