//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AITBaseViewController.h"

#import "UITextViewDelegate.h"

@class AITFeed, AITRepostView, NSString, UILabel, UITextView, UIView;

@interface AITCreateRepostViewController : AITBaseViewController <UITextViewDelegate>
{
    _Bool _didSetupConstraints;	// 8 = 0x8
    _Bool _bModify;	// 9 = 0x9
    _Bool _bCanPress;	// 10 = 0xa
    UITextView *_textViewRepost;	// 16 = 0x10
    UIView *_viewBgText;	// 24 = 0x18
    UIView *_viewBgRepost;	// 32 = 0x20
    UILabel *_labelPlaceText;	// 40 = 0x28
    UILabel *_labelContentLength;	// 48 = 0x30
    AITRepostView *_viewRepost;	// 56 = 0x38
    AITFeed *_dataFeed;	// 64 = 0x40
    CDUnknownBlockType _blockRepostFinish;	// 72 = 0x48
    AITFeed *_dataOriginFeed;	// 80 = 0x50
}

@property(nonatomic) _Bool bCanPress; // @synthesize bCanPress=_bCanPress;
@property(nonatomic) _Bool bModify; // @synthesize bModify=_bModify;
@property(retain, nonatomic) AITFeed *dataOriginFeed; // @synthesize dataOriginFeed=_dataOriginFeed;
@property(copy, nonatomic) CDUnknownBlockType blockRepostFinish; // @synthesize blockRepostFinish=_blockRepostFinish;
@property(retain, nonatomic) AITFeed *dataFeed; // @synthesize dataFeed=_dataFeed;
@property(retain, nonatomic) AITRepostView *viewRepost; // @synthesize viewRepost=_viewRepost;
@property(retain, nonatomic) UILabel *labelContentLength; // @synthesize labelContentLength=_labelContentLength;
@property(retain, nonatomic) UILabel *labelPlaceText; // @synthesize labelPlaceText=_labelPlaceText;
@property(retain, nonatomic) UIView *viewBgRepost; // @synthesize viewBgRepost=_viewBgRepost;
@property(retain, nonatomic) UIView *viewBgText; // @synthesize viewBgText=_viewBgText;
@property(nonatomic) _Bool didSetupConstraints; // @synthesize didSetupConstraints=_didSetupConstraints;
@property(retain, nonatomic) UITextView *textViewRepost; // @synthesize textViewRepost=_textViewRepost;
- (void).cxx_destruct;	// IMP=0x0000000100e001b0
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100dfff20
- (void)textViewDidChange:(id)arg1;	// IMP=0x0000000100dff4f8
- (void)repostFinish:(CDUnknownBlockType)arg1;	// IMP=0x0000000100dff4ec
- (void)updateViewConstraints;	// IMP=0x0000000100dff178
- (void)viewDidLoad;	// IMP=0x0000000100dfe0dc
- (id)showMode;	// IMP=0x0000000100dfe0b0
- (id)initWithParam:(id)arg1;	// IMP=0x0000000100dfdf74
- (id)initWithModifyData:(id)arg1;	// IMP=0x0000000100dfde6c
- (id)initWithData:(id)arg1;	// IMP=0x0000000100dfdd8c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

