//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALBBWantuConfiguration, ALBBWantuUploadServiceAdapter;

@interface ALBBWantu : NSObject
{
    ALBBWantuConfiguration *_configuration;	// 8 = 0x8
    ALBBWantuUploadServiceAdapter *_uploadServiceAdapter;	// 16 = 0x10
}

+ (void)removeWantuForKey:(id)arg1;	// IMP=0x000000010108cf28
+ (id)wantuForKey:(id)arg1;	// IMP=0x000000010108cf14
+ (void)registerWantuWithConfiguration:(id)arg1 forKey:(id)arg2;	// IMP=0x000000010108ce20
+ (id)defaultWantu;	// IMP=0x000000010108cd64
@property(retain, nonatomic) ALBBWantuUploadServiceAdapter *uploadServiceAdapter; // @synthesize uploadServiceAdapter=_uploadServiceAdapter;
@property(retain, nonatomic) ALBBWantuConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;	// IMP=0x000000010108e078
- (void)cancelMultipartUpload:(id)arg1 completeHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010108df70
- (void)completeMultipartUpload:(id)arg1 completeHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010108dee8
- (void)uploadPart:(id)arg1 completeHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010108de60
- (void)initMultipartUpload:(id)arg1 completeHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010108ddd8
- (void)setDebug:(_Bool)arg1;	// IMP=0x000000010108dd78
- (id)session2WTResponse:(id)arg1;	// IMP=0x000000010108d83c
- (void)upload:(id)arg1 completeHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010108cfac
- (id)initWithConfiguration:(id)arg1;	// IMP=0x000000010108cc5c
- (id)init;	// IMP=0x000000010108cbd4

@end

