//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALBBWTUploadResponse.h"

@class NSString;

@interface ALBBWTCompleteMultipartUploadResponse : ALBBWTUploadResponse
{
    NSString *_id;	// 128 = 0x80
    NSString *_uploadId;	// 136 = 0x88
}

+ (id)JSONKeyPathsByPropertyKey;	// IMP=0x00000001010c54d8
@property(retain, nonatomic) NSString *uploadId; // @synthesize uploadId=_uploadId;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;	// IMP=0x00000001010c5618

@end

