//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface APIPCommand : NSObject
{
    NSString *_js;	// 8 = 0x8
    NSDictionary *_paramsDic;	// 16 = 0x10
    id <APIPCommandDelegate> _delegate;	// 24 = 0x18
    NSDictionary *_extraParams;	// 32 = 0x20
}

@property(retain, nonatomic) NSDictionary *extraParams; // @synthesize extraParams=_extraParams;
@property(nonatomic) __weak id <APIPCommandDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSDictionary *paramsDic; // @synthesize paramsDic=_paramsDic;
@property(copy, nonatomic) NSString *js; // @synthesize js=_js;
- (void).cxx_destruct;	// IMP=0x00000001010d4174

@end

