//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface APIPNetworkInfo : NSObject
{
    _Bool _is2GNetwork;	// 8 = 0x8
    _Bool _isLogUpdateenabled;	// 9 = 0x9
    _Bool _isInterceptUrl;	// 10 = 0xa
    _Bool _isAutoRetry;	// 11 = 0xb
    NSString *_networkType;	// 16 = 0x10
    NSString *_wifissid;	// 24 = 0x18
    NSString *_wifimac;	// 32 = 0x20
    NSString *_strBizDftUrl;	// 40 = 0x28
    NSString *_strBizCustomizedUrl;	// 48 = 0x30
    NSArray *_arrBizDnsUrl;	// 56 = 0x38
    NSString *_nerString;	// 64 = 0x40
    NSString *_serString;	// 72 = 0x48
    NSString *_loadString;	// 80 = 0x50
    NSString *_confirmString;	// 88 = 0x58
    NSString *_retryString;	// 96 = 0x60
    NSString *_cancelString;	// 104 = 0x68
    NSString *_payRequestId;	// 112 = 0x70
    NSString *_alipayIntlSessionId;	// 120 = 0x78
    NSDictionary *_cmdInfo;	// 128 = 0x80
    NSArray *_urlArray;	// 136 = 0x88
}

@property(retain, nonatomic) NSArray *urlArray; // @synthesize urlArray=_urlArray;
@property(retain, nonatomic) NSDictionary *cmdInfo; // @synthesize cmdInfo=_cmdInfo;
@property(copy, nonatomic) NSString *alipayIntlSessionId; // @synthesize alipayIntlSessionId=_alipayIntlSessionId;
@property(copy, nonatomic) NSString *payRequestId; // @synthesize payRequestId=_payRequestId;
@property(nonatomic) _Bool isAutoRetry; // @synthesize isAutoRetry=_isAutoRetry;
@property(copy, nonatomic) NSString *cancelString; // @synthesize cancelString=_cancelString;
@property(copy, nonatomic) NSString *retryString; // @synthesize retryString=_retryString;
@property(copy, nonatomic) NSString *confirmString; // @synthesize confirmString=_confirmString;
@property(copy, nonatomic) NSString *loadString; // @synthesize loadString=_loadString;
@property(copy, nonatomic) NSString *serString; // @synthesize serString=_serString;
@property(copy, nonatomic) NSString *nerString; // @synthesize nerString=_nerString;
@property(copy, nonatomic) NSArray *arrBizDnsUrl; // @synthesize arrBizDnsUrl=_arrBizDnsUrl;
@property(copy, nonatomic) NSString *strBizCustomizedUrl; // @synthesize strBizCustomizedUrl=_strBizCustomizedUrl;
@property(copy, nonatomic) NSString *strBizDftUrl; // @synthesize strBizDftUrl=_strBizDftUrl;
@property(copy, nonatomic) NSString *wifimac; // @synthesize wifimac=_wifimac;
@property(copy, nonatomic) NSString *wifissid; // @synthesize wifissid=_wifissid;
@property(copy, nonatomic) NSString *networkType; // @synthesize networkType=_networkType;
@property(nonatomic) _Bool isInterceptUrl; // @synthesize isInterceptUrl=_isInterceptUrl;
@property(nonatomic) _Bool isLogUpdateenabled; // @synthesize isLogUpdateenabled=_isLogUpdateenabled;
@property(nonatomic) _Bool is2GNetwork; // @synthesize is2GNetwork=_is2GNetwork;
- (void).cxx_destruct;	// IMP=0x000000010113856c
- (id)requestURLWithUsingHttps:(_Bool)arg1 originURL:(id)arg2;	// IMP=0x00000001011381fc
- (_Bool)isPreReleaseNetwork;	// IMP=0x0000000101137a1c
- (void)setArrBizDnsUrl:(id)arg1 isForceUpdate:(_Bool)arg2;	// IMP=0x0000000101137708
- (void)updateBizDnsArr:(id)arg1;	// IMP=0x00000001011376f8
- (void)updateCmdPackage:(id)arg1;	// IMP=0x00000001011371d0
- (id)networkTypeViaWWAN;	// IMP=0x0000000101136f3c
- (id)wifiInterface;	// IMP=0x0000000101136db0
- (id)init;	// IMP=0x0000000101136934

@end

