//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "APIPCommandDelegate.h"

@class APIPControlFrame, APIPKVOController, NSArray, NSString;

@interface APIPControl : UIView <APIPCommandDelegate>
{
    long long _hAlign;	// 8 = 0x8
    long long _vAlign;	// 16 = 0x10
    NSString *_name;	// 24 = 0x18
    APIPControlFrame *_contrlFrame;	// 32 = 0x20
    UIView *_contentView;	// 40 = 0x28
    NSArray *_subControlsArr;	// 48 = 0x30
    APIPKVOController *_kvoController;	// 56 = 0x38
}

@property(retain, nonatomic) APIPKVOController *kvoController; // @synthesize kvoController=_kvoController;
@property(retain, nonatomic) NSArray *subControlsArr; // @synthesize subControlsArr=_subControlsArr;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) APIPControlFrame *contrlFrame; // @synthesize contrlFrame=_contrlFrame;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property long long vAlign; // @synthesize vAlign=_vAlign;
@property long long hAlign; // @synthesize hAlign=_hAlign;
- (void).cxx_destruct;	// IMP=0x0000000101114d64
- (void)shouldNotifyRelayout;	// IMP=0x0000000101114b88
- (void)layoutSubviews;	// IMP=0x0000000101114ad0
- (void)kvoAction:(id)arg1 keypath:(id)arg2;	// IMP=0x0000000101114944
- (void)setup;	// IMP=0x00000001011144ec
- (void)dealloc;	// IMP=0x0000000101114490
- (id)initWithContrlFrame:(id)arg1;	// IMP=0x00000001011143a8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

