//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface APIPActionEntity : NSObject
{
    NSString *_allowBack;	// 8 = 0x8
    NSString *_disableBack;	// 16 = 0x10
    NSString *_name;	// 24 = 0x18
    NSString *_backDialog;	// 32 = 0x20
}

@property(copy, nonatomic) NSString *backDialog; // @synthesize backDialog=_backDialog;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *disableBack; // @synthesize disableBack=_disableBack;
@property(copy, nonatomic) NSString *allowBack; // @synthesize allowBack=_allowBack;
- (void).cxx_destruct;	// IMP=0x00000001010ef55c
- (id)initWithDic:(id)arg1;	// IMP=0x00000001010ef488

@end

