//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString, NSURL;

@interface APIPRTLabelButton : UIButton
{
    int _componentIndex;	// 8 = 0x8
    NSURL *_url;	// 16 = 0x10
    NSString *_pageTitle;	// 24 = 0x18
}

@property(copy, nonatomic) NSString *pageTitle; // @synthesize pageTitle=_pageTitle;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) int componentIndex; // @synthesize componentIndex=_componentIndex;
- (void).cxx_destruct;	// IMP=0x00000001011027ec

@end

