//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableDictionary;

@interface AppMonitorConfigMetrics : NSObject
{
    NSMutableDictionary *_extra_dic;	// 8 = 0x8
    NSLock *_lock;	// 16 = 0x10
}

@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableDictionary *extra_dic; // @synthesize extra_dic=_extra_dic;
- (void).cxx_destruct;	// IMP=0x00000001012161f4
- (id)getArgsResultWithKey:(id)arg1 Arg:(id)arg2;	// IMP=0x0000000101215fcc
- (_Bool)compare:(id)arg1 Value:(id)arg2 Include:(int)arg3;	// IMP=0x0000000101215f2c
- (id)getDimensionResultWithKey:(id)arg1 Dimension:(id)arg2;	// IMP=0x0000000101215cbc
- (void)parseExtraInfo:(id)arg1 Key:(id)arg2;	// IMP=0x0000000101215a68
- (id)init;	// IMP=0x00000001012159a8

@end

