//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppMonitorEvent.h"

#import "AppMonitorRawEventProtocol.h"

@class NSString;

@interface AppMonitorRawCountEvent : AppMonitorEvent <AppMonitorRawEventProtocol>
{
    long long _count;	// 8 = 0x8
    double _value;	// 16 = 0x10
}

+ (id)parseRawUTMsg:(id)arg1;	// IMP=0x000000010121205c
@property(nonatomic) double value; // @synthesize value=_value;
@property(nonatomic) long long count; // @synthesize count=_count;
- (id)dumpToUTEvent;	// IMP=0x0000000101211e34
- (id)initWithEventId:(id)arg1 module:(id)arg2 monitorPoint:(id)arg3 value:(double)arg4;	// IMP=0x0000000101211da8
- (id)initWithEventId:(id)arg1 module:(id)arg2 monitorPoint:(id)arg3 value:(double)arg4 extraInfo:(id)arg5;	// IMP=0x0000000101211ca4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

