//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AppMonitorDimensionValueSet.h"

@class NSMutableDictionary;

@interface AppMonitorUTDimensionValueSet : AppMonitorDimensionValueSet
{
    NSMutableDictionary *_rawMessageDict;	// 8 = 0x8
}

@property(retain, nonatomic) NSMutableDictionary *rawMessageDict; // @synthesize rawMessageDict=_rawMessageDict;
- (void).cxx_destruct;	// IMP=0x0000000101211a50
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010121174c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000101211684
- (id)eventId;	// IMP=0x0000000101211618
- (id)initWithDictionary:(id)arg1;	// IMP=0x0000000101210f90
- (id)initWithEvent:(id)arg1;	// IMP=0x0000000101210c3c
- (id)initWithEventId:(id)arg1;	// IMP=0x0000000101210b78

@end

