//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AppMonitorEventConfig : NSObject
{
    _Bool _isOpen;	// 8 = 0x8
    long long _triggerCount;	// 16 = 0x10
    long long _statisticsInterval;	// 24 = 0x18
    NSString *_eventId;	// 32 = 0x20
    NSString *_aggregateEventArgsKey;	// 40 = 0x28
    long long _eventType;	// 48 = 0x30
}

+ (long long)eventType;	// IMP=0x00000001011fd6c0
+ (long long)statisticsInterval;	// IMP=0x00000001011fd668
+ (void)setStatisticsInterval:(long long)arg1;	// IMP=0x00000001011fd614
+ (void)setTriggerCount:(long long)arg1;	// IMP=0x00000001011fd5c0
+ (long long)triggerCount:(id)arg1;	// IMP=0x00000001011fd540
+ (void)setIsOpen:(_Bool)arg1;	// IMP=0x00000001011fd4ec
+ (_Bool)isOpen;	// IMP=0x00000001011fd440
+ (id)eventId;	// IMP=0x00000001011fd3e0
+ (id)sharedInstance;	// IMP=0x00000001011fd348
@property(nonatomic) long long eventType; // @synthesize eventType=_eventType;
@property(retain, nonatomic) NSString *aggregateEventArgsKey; // @synthesize aggregateEventArgsKey=_aggregateEventArgsKey;
@property(retain, nonatomic) NSString *eventId; // @synthesize eventId=_eventId;
@property(nonatomic) long long statisticsInterval; // @synthesize statisticsInterval=_statisticsInterval;
@property(nonatomic) long long triggerCount; // @synthesize triggerCount=_triggerCount;
- (void).cxx_destruct;	// IMP=0x00000001011fde44
@property(nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
- (id)init;	// IMP=0x00000001011fd350

@end

