//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ASSSettingModel : NSObject
{
}

+ (void)clearSetting;	// IMP=0x000000010114a4f4
+ (void)saveSetting;	// IMP=0x000000010114a290
+ (void)initializeSettings;	// IMP=0x0000000101149fbc
+ (void)setLogUploadSwitch:(_Bool)arg1;	// IMP=0x0000000101149fb0
+ (_Bool)getLogUploadSwitch;	// IMP=0x0000000101149fa4
+ (void)setGidSwitch:(_Bool)arg1;	// IMP=0x0000000101149f98
+ (_Bool)getGidSwitch;	// IMP=0x0000000101149f8c
+ (void)setVkeySwitchInDataMode:(_Bool)arg1;	// IMP=0x0000000101149f80
+ (_Bool)getVkeySwitchInDataMode;	// IMP=0x0000000101149f74
+ (void)setVkeySwitchInTokenMode:(_Bool)arg1;	// IMP=0x0000000101149f68
+ (_Bool)getVkeySwitchInTokenMode;	// IMP=0x0000000101149f5c

@end

