//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AVFSMonitorEngine : NSObject
{
}

+ (void)startCronTask;	// IMP=0x00000001011be7a8
+ (void)resolverCommands:(id)arg1;	// IMP=0x00000001011be6e8
+ (void)registerDelegate:(Class)arg1 forProtocol:(id)arg2;	// IMP=0x00000001011be670
+ (void)wakeupMonitorEnable:(_Bool)arg1;	// IMP=0x00000001011be600
+ (void)notifyName:(id)arg1 data:(id)arg2;	// IMP=0x00000001011be494
+ (void)initMonitorEngine;	// IMP=0x00000001011be3e4

@end

