//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BFTask;

@interface BFTaskCompletionSource : NSObject
{
    BFTask *_task;	// 8 = 0x8
}

+ (id)taskCompletionSource;	// IMP=0x00000001008ce35c
@property(readonly, nonatomic) BFTask *task; // @synthesize task=_task;
- (void).cxx_destruct;	// IMP=0x00000001008ce81c
- (_Bool)trySetCancelled;	// IMP=0x00000001008ce7c0
- (_Bool)trySetException:(id)arg1;	// IMP=0x00000001008ce748
- (_Bool)trySetError:(id)arg1;	// IMP=0x00000001008ce6d0
- (_Bool)trySetResult:(id)arg1;	// IMP=0x00000001008ce658
- (void)cancel;	// IMP=0x00000001008ce5e4
- (void)setException:(id)arg1;	// IMP=0x00000001008ce544
- (void)setError:(id)arg1;	// IMP=0x00000001008ce4a4
- (void)setResult:(id)arg1;	// IMP=0x00000001008ce404
- (id)init;	// IMP=0x00000001008ce384

@end

