//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, parentCategoryItemDTO, selectedCategoryItemDTO;

@interface categoryItemDTO : NSObject
{
    NSArray *_categorys;	// 8 = 0x8
    NSString *_categoryDiectoryId;	// 16 = 0x10
    NSArray *_categoryPath;	// 24 = 0x18
    parentCategoryItemDTO *_parentCategory;	// 32 = 0x20
    selectedCategoryItemDTO *_selectedCategory;	// 40 = 0x28
}

@property(retain, nonatomic) selectedCategoryItemDTO *selectedCategory; // @synthesize selectedCategory=_selectedCategory;
@property(retain, nonatomic) parentCategoryItemDTO *parentCategory; // @synthesize parentCategory=_parentCategory;
@property(retain, nonatomic) NSArray *categoryPath; // @synthesize categoryPath=_categoryPath;
@property(copy, nonatomic) NSString *categoryDiectoryId; // @synthesize categoryDiectoryId=_categoryDiectoryId;
@property(retain, nonatomic) NSArray *categorys; // @synthesize categorys=_categorys;
- (void).cxx_destruct;	// IMP=0x0000000100c95888

@end

