//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CipherResultSet : NSObject
{
    struct CipherStatement *_statement;	// 8 = 0x8
    _Bool _threadSafe;	// 16 = 0x10
}

- (int)columnCount;	// IMP=0x00000001011ac3c4
- (id)resultDictionary;	// IMP=0x00000001011ac278
- (id)objectForColumnIndex:(int)arg1 error:(int *)arg2;	// IMP=0x00000001011ac154
- (id)objectForColumnName:(id)arg1 error:(int *)arg2;	// IMP=0x00000001011ac0c4
- (id)columnNameForIndex:(int)arg1 error:(int *)arg2;	// IMP=0x00000001011ac08c
- (int)columnIndexForName:(id)arg1 error:(int *)arg2;	// IMP=0x00000001011ac018
- (int)typeForColumnIndex:(int)arg1 error:(int *)arg2;	// IMP=0x00000001011abfac
- (int)typeForColumn:(id)arg1 error:(int *)arg2;	// IMP=0x00000001011abefc
- (id)dataForColumnIndex:(int)arg1 error:(int *)arg2;	// IMP=0x00000001011abe30
- (id)dataForColumn:(id)arg1 error:(int *)arg2;	// IMP=0x00000001011abd10
- (id)stringForColumnIndex:(int)arg1 error:(int *)arg2;	// IMP=0x00000001011abc7c
- (id)stringForColumn:(id)arg1 error:(int *)arg2;	// IMP=0x00000001011abb98
- (double)doubleForColumnIndex:(int)arg1 error:(int *)arg2;	// IMP=0x00000001011abb24
- (double)doubleForColumn:(id)arg1 error:(int *)arg2;	// IMP=0x00000001011aba6c
- (long long)longLongForColumnIndex:(int)arg1 error:(int *)arg2;	// IMP=0x00000001011aba00
- (long long)longLongForColumn:(id)arg1 error:(int *)arg2;	// IMP=0x00000001011ab950
- (long long)longForColumnIndex:(int)arg1 error:(int *)arg2;	// IMP=0x00000001011ab8e4
- (long long)longForColumn:(id)arg1 error:(int *)arg2;	// IMP=0x00000001011ab834
- (int)intForColumnIndex:(int)arg1 error:(int *)arg2;	// IMP=0x00000001011ab7c8
- (int)intForColumn:(id)arg1 error:(int *)arg2;	// IMP=0x00000001011ab718
- (_Bool)next;	// IMP=0x00000001011ab6e8
- (void)setStatement:(void *)arg1;	// IMP=0x00000001011ab6d8
- (void)close;	// IMP=0x00000001011ab6a0

@end

