//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DisputeEditService : NSObject
{
}

- (void)respondArbitrationWithIssueId:(id)arg1 imageUrls:(id)arg2 text:(id)arg3 complete:(CDUnknownBlockType)arg4;	// IMP=0x00000001002afa9c
- (void)appealSubmitWithDTO:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001002af7b8
- (void)reasonSubmitWithDTO:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001002af464
- (void)reasonQueryModifyWithIssueId:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001002af1d0
- (void)proofDeleteWithIssueId:(id)arg1 proofId:(id)arg2 proofType:(long long)arg3 complete:(CDUnknownBlockType)arg4;	// IMP=0x00000001002aef1c
- (void)proofAddWithIssueId:(id)arg1 imageUrls:(id)arg2 complete:(CDUnknownBlockType)arg3;	// IMP=0x00000001002aec88
- (void)proofAddWithIssueId:(id)arg1 videoIds:(id)arg2 videoCoverUrls:(id)arg3 complete:(CDUnknownBlockType)arg4;	// IMP=0x00000001002ae9d0
- (void)proofQueryWithIssueId:(id)arg1 timezone:(id)arg2 complete:(CDUnknownBlockType)arg3;	// IMP=0x00000001002ae678
- (void)solutionRemoveWithIssueId:(id)arg1 solutionId:(id)arg2 complete:(CDUnknownBlockType)arg3;	// IMP=0x00000001002ae674
- (void)solutionSubmitWithDTO:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001002ae2f0
- (void)solutionQueryModifyWithIssueId:(id)arg1 solutionId:(id)arg2 complete:(CDUnknownBlockType)arg3;	// IMP=0x00000001002adfec
- (void)issueSubmitWithDTO:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001002adb0c
- (void)issueOpenWithSubOrderId:(id)arg1 complete:(CDUnknownBlockType)arg2;	// IMP=0x00000001002ad85c

@end

