//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DTRpcBaseOperation.h"

@class DTRpcMethod, NSArray, NSMutableDictionary;

@interface DTRpcOperation : DTRpcBaseOperation
{
    double _startTime;	// 24 = 0x18
    DTRpcMethod *_method;	// 32 = 0x20
    NSArray *_params;	// 40 = 0x28
    id _resultObject;	// 48 = 0x30
    NSMutableDictionary *_userInfo;	// 56 = 0x38
}

@property(retain, nonatomic) NSMutableDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) id resultObject; // @synthesize resultObject=_resultObject;
@property(retain, nonatomic) NSArray *params; // @synthesize params=_params;
@property(retain, nonatomic) DTRpcMethod *method; // @synthesize method=_method;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;	// IMP=0x000000010117cf6c
- (void)didFinish;	// IMP=0x000000010117c810
- (void)didStart;	// IMP=0x000000010117c7d8
- (id)buildRequestDataWithMethod:(id)arg1 params:(id)arg2;	// IMP=0x000000010117c56c
- (id)copy;	// IMP=0x000000010117c478
- (void)start;	// IMP=0x000000010117c400
- (id)initWithURL:(id)arg1 method:(id)arg2 params:(id)arg3;	// IMP=0x000000010117c384
- (id)initWithURL:(id)arg1 method:(id)arg2 params:(id)arg3 timeout:(double)arg4;	// IMP=0x000000010117c034

@end

