//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface emptyRecommendDTO : NSObject
{
    _Bool _hasRecommend;	// 8 = 0x8
    NSString *_recommendWord;	// 16 = 0x10
}

@property(copy, nonatomic) NSString *recommendWord; // @synthesize recommendWord=_recommendWord;
@property(nonatomic) _Bool hasRecommend; // @synthesize hasRecommend=_hasRecommend;
- (void).cxx_destruct;	// IMP=0x0000000100c95c58

@end

