//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBSDKServerConfigurationManager : NSObject
{
}

+ (CDUnknownBlockType)_wrapperBlockForLoadBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010126a34c
+ (_Bool)_serverConfigurationTimestampIsValid:(id)arg1;	// IMP=0x000000010126a2b8
+ (id)_parseDialogConfigurations:(id)arg1;	// IMP=0x0000000101269f20
+ (void)_didProcessConfigurationFromNetwork:(id)arg1 appID:(id)arg2 error:(id)arg3;	// IMP=0x0000000101269aa4
+ (id)_defaultServerConfigurationForAppID:(id)arg1;	// IMP=0x00000001012697d4
+ (id)requestToLoadServerConfiguration:(id)arg1;	// IMP=0x0000000101269588
+ (void)processLoadRequestResponse:(id)arg1 error:(id)arg2 appID:(id)arg3;	// IMP=0x0000000101268fc8
+ (void)loadServerConfigurationWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000101268ab4
+ (id)cachedServerConfiguration;	// IMP=0x00000001012689e0
+ (void)clearCache;	// IMP=0x00000001012688e0
+ (void)initialize;	// IMP=0x000000010126886c
- (id)init;	// IMP=0x000000010126a4e8

@end

