//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBSDKCopying.h"
#import "NSSecureCoding.h"

@class FBSDKErrorConfiguration, NSDate, NSDictionary, NSString;

@interface FBSDKServerConfiguration : NSObject <FBSDKCopying, NSSecureCoding>
{
    NSDictionary *_dialogConfigurations;	// 8 = 0x8
    NSDictionary *_dialogFlows;	// 16 = 0x10
    _Bool _advertisingIDEnabled;	// 24 = 0x18
    _Bool _defaults;	// 25 = 0x19
    _Bool _implicitLoggingEnabled;	// 26 = 0x1a
    _Bool _implicitPurchaseLoggingEnabled;	// 27 = 0x1b
    _Bool _loginTooltipEnabled;	// 28 = 0x1c
    _Bool _nativeAuthFlowEnabled;	// 29 = 0x1d
    _Bool _systemAuthenticationEnabled;	// 30 = 0x1e
    NSString *_appID;	// 32 = 0x20
    NSString *_appName;	// 40 = 0x28
    NSString *_defaultShareMode;	// 48 = 0x30
    FBSDKErrorConfiguration *_errorConfiguration;	// 56 = 0x38
    NSString *_loginTooltipText;	// 64 = 0x40
    NSDate *_timestamp;	// 72 = 0x48
    double _sessionTimoutInterval;	// 80 = 0x50
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000101268054
@property(nonatomic) double sessionTimoutInterval; // @synthesize sessionTimoutInterval=_sessionTimoutInterval;
@property(readonly, copy, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, copy, nonatomic) NSString *loginTooltipText; // @synthesize loginTooltipText=_loginTooltipText;
@property(readonly, nonatomic, getter=isSystemAuthenticationEnabled) _Bool systemAuthenticationEnabled; // @synthesize systemAuthenticationEnabled=_systemAuthenticationEnabled;
@property(readonly, nonatomic, getter=isNativeAuthFlowEnabled) _Bool nativeAuthFlowEnabled; // @synthesize nativeAuthFlowEnabled=_nativeAuthFlowEnabled;
@property(readonly, nonatomic, getter=isLoginTooltipEnabled) _Bool loginTooltipEnabled; // @synthesize loginTooltipEnabled=_loginTooltipEnabled;
@property(readonly, nonatomic, getter=isImplicitPurchaseLoggingSupported) _Bool implicitPurchaseLoggingEnabled; // @synthesize implicitPurchaseLoggingEnabled=_implicitPurchaseLoggingEnabled;
@property(readonly, nonatomic, getter=isImplicitLoggingSupported) _Bool implicitLoggingEnabled; // @synthesize implicitLoggingEnabled=_implicitLoggingEnabled;
@property(readonly, nonatomic) FBSDKErrorConfiguration *errorConfiguration; // @synthesize errorConfiguration=_errorConfiguration;
@property(readonly, copy, nonatomic) NSString *defaultShareMode; // @synthesize defaultShareMode=_defaultShareMode;
@property(readonly, nonatomic, getter=isDefaults) _Bool defaults; // @synthesize defaults=_defaults;
@property(readonly, copy, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(readonly, copy, nonatomic) NSString *appID; // @synthesize appID=_appID;
@property(readonly, nonatomic, getter=isAdvertisingIDEnabled) _Bool advertisingIDEnabled; // @synthesize advertisingIDEnabled=_advertisingIDEnabled;
- (void).cxx_destruct;	// IMP=0x00000001012687b4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001012686c0
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000101268488
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010126805c
- (_Bool)_useFeatureWithKey:(id)arg1 dialogName:(id)arg2;	// IMP=0x0000000101267e40
- (_Bool)useSafariViewControllerForDialogName:(id)arg1;	// IMP=0x0000000101267e24
- (_Bool)useNativeDialogForDialogName:(id)arg1;	// IMP=0x0000000101267e08
- (id)dialogConfigurationForDialogName:(id)arg1;	// IMP=0x0000000101267df0
- (id)initWithAppID:(id)arg1 appName:(id)arg2 loginTooltipEnabled:(_Bool)arg3 loginTooltipText:(id)arg4 defaultShareMode:(id)arg5 advertisingIDEnabled:(_Bool)arg6 implicitLoggingEnabled:(_Bool)arg7 implicitPurchaseLoggingEnabled:(_Bool)arg8 systemAuthenticationEnabled:(_Bool)arg9 nativeAuthFlowEnabled:(_Bool)arg10 dialogConfigurations:(id)arg11 dialogFlows:(id)arg12 timestamp:(id)arg13 errorConfiguration:(id)arg14 sessionTimeoutInterval:(double)arg15 defaults:(_Bool)arg16;	// IMP=0x0000000101267af4
- (id)init;	// IMP=0x0000000101267acc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

