//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FileHash : NSObject
{
}

+ (id)sha512HashOfFileAtPath:(id)arg1;	// IMP=0x000000010091bb88
+ (id)sha1HashOfFileAtPath:(id)arg1;	// IMP=0x000000010091bb2c
+ (id)md5HashOfFileAtPath:(id)arg1;	// IMP=0x000000010091bad0
+ (id)hashOfFileAtPath:(id)arg1 withComputationContext:(struct _FileHashComputationContext *)arg2;	// IMP=0x000000010091b8d8

@end

