//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class GIDAuthentication, GIDProfileData, NSArray, NSString;

@interface GIDGoogleUser : NSObject <NSCoding>
{
    NSString *_userID;	// 8 = 0x8
    GIDProfileData *_profile;	// 16 = 0x10
    GIDAuthentication *_authentication;	// 24 = 0x18
    NSArray *_accessibleScopes;	// 32 = 0x20
    NSString *_hostedDomain;	// 40 = 0x28
    NSString *_serverAuthCode;	// 48 = 0x30
}

@property(readonly, nonatomic) NSString *serverAuthCode; // @synthesize serverAuthCode=_serverAuthCode;
@property(readonly, nonatomic) NSString *hostedDomain; // @synthesize hostedDomain=_hostedDomain;
@property(readonly, nonatomic) NSArray *accessibleScopes; // @synthesize accessibleScopes=_accessibleScopes;
@property(readonly, nonatomic) GIDAuthentication *authentication; // @synthesize authentication=_authentication;
@property(readonly, nonatomic) GIDProfileData *profile; // @synthesize profile=_profile;
@property(readonly, nonatomic) NSString *userID; // @synthesize userID=_userID;
- (void).cxx_destruct;	// IMP=0x00000001009401d4
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100940068
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010093febc
- (id)initWithAuthentication:(id)arg1 scopes:(id)arg2;	// IMP=0x000000010093fc74

@end

