//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GIDSignInStrings : NSObject
{
}

+ (id)promoActionInstallString;	// IMP=0x000000010094bf64
+ (id)promoActionCancelString;	// IMP=0x000000010094bf48
+ (id)promoMessageString;	// IMP=0x000000010094bf2c
+ (id)promoTitleString;	// IMP=0x000000010094bf10
+ (id)signInWithGoogleString;	// IMP=0x000000010094bef8
+ (id)signInString;	// IMP=0x000000010094bee0
+ (id)localizedStringForKey:(id)arg1 text:(id)arg2;	// IMP=0x000000010094be34

@end

