//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GPBDictionaryInternalsProtocol.h"
#import "NSCopying.h"

@class GPBMessage;

@interface GPBBoolUInt32Dictionary : NSObject <GPBDictionaryInternalsProtocol, NSCopying>
{
    GPBMessage *_autocreator;	// 8 = 0x8
    unsigned int _values[2];	// 16 = 0x10
    _Bool _valueSet[2];	// 24 = 0x18
}

+ (id)dictionaryWithCapacity:(unsigned long long)arg1;	// IMP=0x00000001017b92c4
+ (id)dictionaryWithDictionary:(id)arg1;	// IMP=0x00000001017b9284
+ (id)dictionaryWithValues:(const unsigned int *)arg1 forKeys:(const _Bool *)arg2 count:(unsigned long long)arg3;	// IMP=0x00000001017b922c
+ (id)dictionaryWithValue:(unsigned int)arg1 forKey:(_Bool)arg2;	// IMP=0x00000001017b91dc
+ (id)dictionary;	// IMP=0x00000001017b91a0
- (void)removeAll;	// IMP=0x00000001017b9b4c
- (void)removeValueForKey:(_Bool)arg1;	// IMP=0x00000001017b9b38
- (void)setValue:(unsigned int)arg1 forKey:(_Bool)arg2;	// IMP=0x00000001017b9af4
- (void)addEntriesFromDictionary:(id)arg1;	// IMP=0x00000001017b9a88
- (void)writeToCodedOutputStream:(id)arg1 asField:(id)arg2;	// IMP=0x00000001017b9934
- (unsigned long long)computeSerializedSizeAsField:(id)arg1;	// IMP=0x00000001017b986c
- (void)enumerateKeysAndValuesUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001017b97d0
- (void)enumerateForTextFormat:(CDUnknownBlockType)arg1;	// IMP=0x00000001017b96e4
- (void)setGPBGenericValue:(CDUnion_88782d86 *)arg1 forGPBGenericValueKey:(CDUnion_88782d86 *)arg2;	// IMP=0x00000001017b96b4
- (_Bool)valueForKey:(_Bool)arg1 value:(unsigned int *)arg2;	// IMP=0x00000001017b9678
@property(readonly, nonatomic) unsigned long long count;
- (id)description;	// IMP=0x00000001017b956c
- (unsigned long long)hash;	// IMP=0x00000001017b9550
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001017b9488
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001017b944c
- (id)initWithCapacity:(unsigned long long)arg1;	// IMP=0x00000001017b9434
- (id)initWithDictionary:(id)arg1;	// IMP=0x00000001017b93b0
- (id)initWithValues:(const unsigned int *)arg1 forKeys:(const _Bool *)arg2 count:(unsigned long long)arg3;	// IMP=0x00000001017b931c
- (id)init;	// IMP=0x00000001017b9304

@end

