//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GSDK_OpenInChromeController : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x0000000100934d58
- (id)pasteboardContent;	// IMP=0x00000001009355e4
- (int)openInChromePreference;	// IMP=0x0000000100935504
- (_Bool)openInChrome:(id)arg1 withCallbackURL:(id)arg2 createNewTab:(_Bool)arg3;	// IMP=0x0000000100934f24
- (_Bool)openInChrome:(id)arg1;	// IMP=0x0000000100934f10
- (_Bool)isChromeInstalled;	// IMP=0x0000000100934e0c

@end

