//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GSDK_GTMOAuth2Authentication, GSDK_GTMSessionFetcher, NSDictionary, NSTimer, NSURL;

@interface GSDK_GTMOAuth2SignIn : NSObject
{
    GSDK_GTMOAuth2Authentication *auth_;	// 8 = 0x8
    NSURL *authorizationURL_;	// 16 = 0x10
    NSDictionary *additionalAuthorizationParameters_;	// 24 = 0x18
    id delegate_;	// 32 = 0x20
    SEL webRequestSelector_;	// 40 = 0x28
    SEL finishedSelector_;	// 48 = 0x30
    _Bool hasHandledCallback_;	// 56 = 0x38
    GSDK_GTMSessionFetcher *pendingFetcher_;	// 64 = 0x40
    _Bool shouldFetchGoogleUserEmail_;	// 72 = 0x48
    _Bool shouldFetchGoogleUserProfile_;	// 73 = 0x49
    NSDictionary *userProfile_;	// 80 = 0x50
    struct __SCNetworkReachability *reachabilityRef_;	// 88 = 0x58
    NSTimer *networkLossTimer_;	// 96 = 0x60
    double networkLossTimeoutInterval_;	// 104 = 0x68
    _Bool hasNotifiedNetworkLoss_;	// 112 = 0x70
    id userData_;	// 120 = 0x78
}

+ (id)decodeWebSafeBase64:(id)arg1;	// IMP=0x0000000100922cf0
+ (void)revokeTokenForGoogleAuthentication:(id)arg1;	// IMP=0x0000000100922aa4
+ (id)userInfoFetcherWithAuth:(id)arg1;	// IMP=0x0000000100921f50
+ (id)mutableURLRequestWithURL:(id)arg1 paramString:(id)arg2;	// IMP=0x00000001009214e8
+ (id)standardGoogleAuthenticationForScope:(id)arg1 clientID:(id)arg2 clientSecret:(id)arg3;	// IMP=0x0000000100920ce0
+ (id)nativeClientRedirectURI;	// IMP=0x0000000100920cd4
+ (id)googleUserInfoURL;	// IMP=0x0000000100920cb4
+ (id)googleRevocationURL;	// IMP=0x0000000100920c94
+ (id)googleTokenURL;	// IMP=0x0000000100920c74
+ (id)googleAuthorizationURL;	// IMP=0x0000000100920c54
@property(nonatomic) double networkLossTimeoutInterval; // @synthesize networkLossTimeoutInterval=networkLossTimeoutInterval_;
@property(retain, nonatomic) NSDictionary *userProfile; // @synthesize userProfile=userProfile_;
@property(nonatomic) _Bool shouldFetchGoogleUserProfile; // @synthesize shouldFetchGoogleUserProfile=shouldFetchGoogleUserProfile_;
@property(nonatomic) _Bool shouldFetchGoogleUserEmail; // @synthesize shouldFetchGoogleUserEmail=shouldFetchGoogleUserEmail_;
@property(retain, nonatomic) id userData; // @synthesize userData=userData_;
@property(retain) GSDK_GTMSessionFetcher *pendingFetcher; // @synthesize pendingFetcher=pendingFetcher_;
@property _Bool hasHandledCallback; // @synthesize hasHandledCallback=hasHandledCallback_;
@property(nonatomic) SEL finishedSelector; // @synthesize finishedSelector=finishedSelector_;
@property(nonatomic) SEL webRequestSelector; // @synthesize webRequestSelector=webRequestSelector_;
@property(retain, nonatomic) id delegate; // @synthesize delegate=delegate_;
@property(retain, nonatomic) NSDictionary *additionalAuthorizationParameters; // @synthesize additionalAuthorizationParameters=additionalAuthorizationParameters_;
@property(retain, nonatomic) NSURL *authorizationURL; // @synthesize authorizationURL=authorizationURL_;
@property(retain, nonatomic) GSDK_GTMOAuth2Authentication *authentication; // @synthesize authentication=auth_;
- (void)stopReachabilityCheck;	// IMP=0x0000000100922a28
- (void)reachabilityTimerFired:(id)arg1;	// IMP=0x00000001009229a8
- (void)reachabilityTarget:(struct __SCNetworkReachability *)arg1 changedFlags:(unsigned int)arg2;	// IMP=0x00000001009228a0
- (void)destroyUnreachabilityTimer;	// IMP=0x0000000100922850
- (void)startReachabilityCheck;	// IMP=0x0000000100922738
- (void)invokeFinalCallbackWithError:(id)arg1;	// IMP=0x00000001009225dc
- (void)finishSignInWithError:(id)arg1;	// IMP=0x00000001009225cc
- (void)updateGoogleUserInfoWithData:(id)arg1;	// IMP=0x0000000100922428
- (void)infoFetcher:(id)arg1 finishedWithData:(id)arg2 error:(id)arg3;	// IMP=0x0000000100922384
- (void)fetchGoogleUserInfo;	// IMP=0x000000010092213c
- (void)auth:(id)arg1 finishedWithFetcher:(id)arg2 error:(id)arg3;	// IMP=0x0000000100921e74
- (void)authCodeObtained;	// IMP=0x0000000100921c5c
- (_Bool)loadFailedWithError:(id)arg1;	// IMP=0x0000000100921b30
- (_Bool)cookiesChanged:(id)arg1;	// IMP=0x0000000100921b28
- (_Bool)titleChanged:(id)arg1;	// IMP=0x00000001009219d0
- (_Bool)requestRedirectedToRequest:(id)arg1;	// IMP=0x00000001009217a0
- (void)closeTheWindow;	// IMP=0x0000000100921738
- (void)windowWasClosed;	// IMP=0x00000001009216cc
- (_Bool)startWebRequest;	// IMP=0x00000001009213bc
- (id)parametersForWebRequest;	// IMP=0x0000000100921244
- (_Bool)startSigningIn;	// IMP=0x0000000100921208
- (void)cancelSigningIn;	// IMP=0x000000010092115c
- (void)dealloc;	// IMP=0x000000010092106c
- (id)initWithAuthentication:(id)arg1 authorizationURL:(id)arg2 delegate:(id)arg3 webRequestSelector:(SEL)arg4 finishedSelector:(SEL)arg5;	// IMP=0x0000000100920f00
- (void)addScopeForGoogleUserInfo;	// IMP=0x0000000100920d90

@end

