//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface internal_DeviceInfo : NSObject
{
}

+ (id)getContactInfo;	// IMP=0x000000010114db24
+ (id)getAvailableSensors;	// IMP=0x000000010114da30
+ (void)getPhotoInfo:(CDUnknownBlockType)arg1;	// IMP=0x000000010114d000
+ (id)getSDKUpTimeInterval;	// IMP=0x000000010114cf80
+ (id)getSysUpTimeInterval;	// IMP=0x000000010114cee0
+ (id)getLanguage;	// IMP=0x000000010114ce34
+ (id)getTimeZone;	// IMP=0x000000010114cdd8
+ (id)getAppList:(id)arg1;	// IMP=0x000000010114cc2c
+ (unsigned long long)getMemorySize;	// IMP=0x000000010114cbd8
+ (id)getNetworkInfo;	// IMP=0x000000010114caac
+ (id)getAppVersion;	// IMP=0x000000010114ca1c
+ (id)getAppName;	// IMP=0x000000010114c9c0
+ (id)getScreenHeight;	// IMP=0x000000010114c940
+ (id)getScreenWidth;	// IMP=0x000000010114c8c0
+ (id)getHWModel;	// IMP=0x000000010114c8ac
+ (id)getKernHostName;	// IMP=0x000000010114c898
+ (id)getSSIDInfo;	// IMP=0x000000010114c708
+ (id)getDiskSpace;	// IMP=0x000000010114c650
+ (long long)getCpuCount;	// IMP=0x000000010114c640
+ (long long)getCpuFreq;	// IMP=0x000000010114c630
+ (id)getModelName;	// IMP=0x000000010114c61c
+ (id)internal_getAdvIdEnabled;	// IMP=0x000000010114c4a8
+ (id)internal_getAdvIdDisabled;	// IMP=0x000000010114c294
+ (id)getAdvId;	// IMP=0x000000010114c288
+ (id)getIdForVendor;	// IMP=0x000000010114c1e0
+ (id)getUniqueIdentifier;	// IMP=0x000000010114c17c
+ (id)getDeviceName;	// IMP=0x000000010114c120
+ (id)getOSName;	// IMP=0x000000010114c0c4
+ (id)getOSVersion;	// IMP=0x000000010114c068
+ (id)screenResolution;	// IMP=0x000000010114bfe4
+ (_Bool)isEmulator;	// IMP=0x000000010114bf60
+ (unsigned short)isJailBreak;	// IMP=0x000000010114bee0
+ (id)getMCC;	// IMP=0x000000010114be4c
+ (id)getMNC;	// IMP=0x000000010114bdb8
+ (id)carrierName;	// IMP=0x000000010114bd18
+ (unsigned long long)getSysInfo:(unsigned int)arg1;	// IMP=0x000000010114bc98
+ (id)getSysInfoByName:(char *)arg1;	// IMP=0x000000010114bbec
+ (id)getMacAddress;	// IMP=0x000000010114ba7c
+ (id)getBundleId;	// IMP=0x000000010114ba20

@end

