//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JDYThreadTracerConfig : NSObject
{
    NSString *appVersion;	// 8 = 0x8
}

+ (id)defaultInstance;	// IMP=0x0000000101315cc0
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion;
- (void).cxx_destruct;	// IMP=0x0000000101315d9c

@end

