//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JekyllCache, JekyllDownloader, NSMutableArray;

@interface JekyllManager : NSObject
{
    JekyllCache *_jekyllCache;	// 8 = 0x8
    JekyllDownloader *_jekyllDownloader;	// 16 = 0x10
    NSMutableArray *_runningOperations;	// 24 = 0x18
}

+ (id)shareManager;	// IMP=0x0000000101322b78
@property(retain, nonatomic) NSMutableArray *runningOperations; // @synthesize runningOperations=_runningOperations;
@property(readonly, nonatomic) JekyllDownloader *jekyllDownloader; // @synthesize jekyllDownloader=_jekyllDownloader;
@property(readonly, nonatomic) JekyllCache *jekyllCache; // @synthesize jekyllCache=_jekyllCache;
- (void).cxx_destruct;	// IMP=0x0000000101323990
- (void)removeOperationFromRunningOperations:(id)arg1;	// IMP=0x000000010132387c
- (void)addOperaiton2RunningOperations:(id)arg1;	// IMP=0x00000001013237d0
- (id)downloadWithURL:(id)arg1 options:(unsigned long long)arg2 progress:(CDUnknownBlockType)arg3 completed:(CDUnknownBlockType)arg4;	// IMP=0x0000000101322d10
- (id)init;	// IMP=0x0000000101322c2c

@end

