//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JSONModelClassProperty : NSObject
{
    _Bool _isOptional;	// 8 = 0x8
    _Bool _isStandardJSONType;	// 9 = 0x9
    _Bool _isMutable;	// 10 = 0xa
    _Bool _convertsOnDemand;	// 11 = 0xb
    _Bool _isIndex;	// 12 = 0xc
    int _getterType;	// 16 = 0x10
    int _setterType;	// 20 = 0x14
    NSString *_name;	// 24 = 0x18
    Class _type;	// 32 = 0x20
    NSString *_structName;	// 40 = 0x28
    NSString *_protocol;	// 48 = 0x30
    SEL _customGetter;	// 56 = 0x38
    SEL _customSetter;	// 64 = 0x40
}

@property(nonatomic) SEL customSetter; // @synthesize customSetter=_customSetter;
@property(nonatomic) int setterType; // @synthesize setterType=_setterType;
@property(nonatomic) SEL customGetter; // @synthesize customGetter=_customGetter;
@property(nonatomic) int getterType; // @synthesize getterType=_getterType;
@property(nonatomic) _Bool isIndex; // @synthesize isIndex=_isIndex;
@property(nonatomic) _Bool convertsOnDemand; // @synthesize convertsOnDemand=_convertsOnDemand;
@property(nonatomic) _Bool isMutable; // @synthesize isMutable=_isMutable;
@property(nonatomic) _Bool isStandardJSONType; // @synthesize isStandardJSONType=_isStandardJSONType;
@property(nonatomic) _Bool isOptional; // @synthesize isOptional=_isOptional;
@property(copy, nonatomic) NSString *protocol; // @synthesize protocol=_protocol;
@property(retain, nonatomic) NSString *structName; // @synthesize structName=_structName;
@property(nonatomic) Class type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;	// IMP=0x0000000101321820
- (id)description;	// IMP=0x0000000101321154

@end

