//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LOTLayerGroup, NSBundle, NSNumber, NSString;

@interface LOTAsset : NSObject
{
    NSString *_referenceID;	// 8 = 0x8
    NSNumber *_assetWidth;	// 16 = 0x10
    NSNumber *_assetHeight;	// 24 = 0x18
    NSString *_imageName;	// 32 = 0x20
    NSString *_imageDirectory;	// 40 = 0x28
    LOTLayerGroup *_layerGroup;	// 48 = 0x30
    NSString *_rootDirectory;	// 56 = 0x38
    NSBundle *_assetBundle;	// 64 = 0x40
}

@property(readonly, nonatomic) NSBundle *assetBundle; // @synthesize assetBundle=_assetBundle;
@property(retain, nonatomic) NSString *rootDirectory; // @synthesize rootDirectory=_rootDirectory;
@property(readonly, nonatomic) LOTLayerGroup *layerGroup; // @synthesize layerGroup=_layerGroup;
@property(readonly, nonatomic) NSString *imageDirectory; // @synthesize imageDirectory=_imageDirectory;
@property(readonly, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
@property(readonly, nonatomic) NSNumber *assetHeight; // @synthesize assetHeight=_assetHeight;
@property(readonly, nonatomic) NSNumber *assetWidth; // @synthesize assetWidth=_assetWidth;
@property(readonly, nonatomic) NSString *referenceID; // @synthesize referenceID=_referenceID;
- (void).cxx_destruct;	// IMP=0x0000000101cf1150
- (void)_mapFromJSON:(id)arg1 withAssetGroup:(id)arg2;	// IMP=0x0000000101cf0dc0
- (id)initWithJSON:(id)arg1 withAssetGroup:(id)arg2 withAssetBundle:(id)arg3;	// IMP=0x0000000101cf0ce4

@end

