//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LOTRenderNode.h"

@class CALayer, CAReplicatorLayer, LOTNumberInterpolator, LOTTransformInterpolator;

@interface LOTRepeaterRenderer : LOTRenderNode
{
    LOTTransformInterpolator *_transformInterpolator;	// 8 = 0x8
    LOTNumberInterpolator *_copiesInterpolator;	// 16 = 0x10
    LOTNumberInterpolator *_offsetInterpolator;	// 24 = 0x18
    LOTNumberInterpolator *_startOpacityInterpolator;	// 32 = 0x20
    LOTNumberInterpolator *_endOpacityInterpolator;	// 40 = 0x28
    CALayer *_instanceLayer;	// 48 = 0x30
    CAReplicatorLayer *_replicatorLayer;	// 56 = 0x38
    CALayer *centerPoint_DEBUG;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000101d01b10
- (void)performLocalUpdate;	// IMP=0x0000000101d0184c
- (_Bool)needsUpdateForFrame:(id)arg1;	// IMP=0x0000000101d01790
- (void)recursivelyAddChildLayers:(id)arg1;	// IMP=0x0000000101d0165c
- (id)valueInterpolators;	// IMP=0x0000000101d01488
- (id)initWithInputNode:(id)arg1 shapeRepeater:(id)arg2;	// IMP=0x0000000101d00e48

@end

