//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActivity.h"

#import "MFMailComposeViewControllerDelegate.h"

@class MFMailComposeViewController, NSString, NSURL, UIImage;

@interface MailActivity : UIActivity <MFMailComposeViewControllerDelegate>
{
    NSString *_title;	// 8 = 0x8
    NSString *_content;	// 16 = 0x10
    NSURL *_url;	// 24 = 0x18
    UIImage *_image;	// 32 = 0x20
    MFMailComposeViewController *_mailComposeViewController;	// 40 = 0x28
    NSString *_videoURL;	// 48 = 0x30
}

+ (id)topVCWithRootVC:(id)arg1;	// IMP=0x0000000100b9b53c
+ (id)topViewController;	// IMP=0x0000000100b9b460
+ (long long)activityCategory;	// IMP=0x0000000100b9a784
@property(retain, nonatomic) NSString *videoURL; // @synthesize videoURL=_videoURL;
@property(retain, nonatomic) MFMailComposeViewController *mailComposeViewController; // @synthesize mailComposeViewController=_mailComposeViewController;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;	// IMP=0x0000000100b9b904
- (void)activityDidFinish:(_Bool)arg1;	// IMP=0x0000000100b9b730
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;	// IMP=0x0000000100b9b6c4
- (id)dataStringFromImage:(id)arg1;	// IMP=0x0000000100b9b40c
- (void)performActivity;	// IMP=0x0000000100b9b14c
- (void)prepareWithActivityItems:(id)arg1;	// IMP=0x0000000100b9abe0
- (_Bool)canPerformWithActivityItems:(id)arg1;	// IMP=0x0000000100b9a874
- (id)_activityImage;	// IMP=0x0000000100b9a7e4
- (id)activityTitle;	// IMP=0x0000000100b9a7b8
- (id)activityType;	// IMP=0x0000000100b9a78c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

