//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface MailingAddressDTO : NSObject <NSCopying>
{
    _Bool _needUpdate;	// 8 = 0x8
    _Bool _hasPassportInfo;	// 9 = 0x9
    _Bool _needPassportInfo;	// 10 = 0xa
    _Bool _defaultAddress;	// 11 = 0xb
    _Bool _hasSelfPickUpPoint;	// 12 = 0xc
    NSString *_addressId;	// 16 = 0x10
    NSString *_address;	// 24 = 0x18
    NSString *_city;	// 32 = 0x20
    NSString *_province;	// 40 = 0x28
    NSString *_country;	// 48 = 0x30
    NSString *_displayCountry;	// 56 = 0x38
    NSString *_zipCode;	// 64 = 0x40
    NSString *_contactPerson;	// 72 = 0x48
    NSString *_address2;	// 80 = 0x50
    NSString *_phoneCountry;	// 88 = 0x58
    NSString *_mobileNo;	// 96 = 0x60
    NSString *_cpfNumber;	// 104 = 0x68
    NSString *_encryptCpf;	// 112 = 0x70
    NSString *_emailAddress;	// 120 = 0x78
    NSString *_updateHint;	// 128 = 0x80
    NSString *_errorField;	// 136 = 0x88
    NSString *_passportName;	// 144 = 0x90
    NSString *_passportNo;	// 152 = 0x98
    NSString *_passportIssueDate;	// 160 = 0xa0
    NSString *_passportOrganization;	// 168 = 0xa8
    NSString *_addressLocale;	// 176 = 0xb0
    NSString *_googlePlaceId;	// 184 = 0xb8
    NSString *_selfFetchingAddressID;	// 192 = 0xc0
    NSString *_houseAddressId;	// 200 = 0xc8
    double _latitude;	// 208 = 0xd0
    double _longitude;	// 216 = 0xd8
    double _distance;	// 224 = 0xe0
    NSString *_distanceString;	// 232 = 0xe8
    NSString *_selfPickupPointName;	// 240 = 0xf0
    NSString *_selfPickupPointOfficeTime;	// 248 = 0xf8
    unsigned long long _addressType;	// 256 = 0x100
    NSString *_selfPickUpPointHint;	// 264 = 0x108
}

+ (id)replacedKeyFromPropertyName;	// IMP=0x000000010062b448
@property(retain, nonatomic) NSString *selfPickUpPointHint; // @synthesize selfPickUpPointHint=_selfPickUpPointHint;
@property(nonatomic) _Bool hasSelfPickUpPoint; // @synthesize hasSelfPickUpPoint=_hasSelfPickUpPoint;
@property(nonatomic) unsigned long long addressType; // @synthesize addressType=_addressType;
@property(retain, nonatomic) NSString *selfPickupPointOfficeTime; // @synthesize selfPickupPointOfficeTime=_selfPickupPointOfficeTime;
@property(retain, nonatomic) NSString *selfPickupPointName; // @synthesize selfPickupPointName=_selfPickupPointName;
@property(retain, nonatomic) NSString *distanceString; // @synthesize distanceString=_distanceString;
@property(nonatomic) double distance; // @synthesize distance=_distance;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *houseAddressId; // @synthesize houseAddressId=_houseAddressId;
@property(retain, nonatomic) NSString *selfFetchingAddressID; // @synthesize selfFetchingAddressID=_selfFetchingAddressID;
@property(nonatomic) _Bool defaultAddress; // @synthesize defaultAddress=_defaultAddress;
@property(retain, nonatomic) NSString *googlePlaceId; // @synthesize googlePlaceId=_googlePlaceId;
@property(retain, nonatomic) NSString *addressLocale; // @synthesize addressLocale=_addressLocale;
@property(nonatomic) _Bool needPassportInfo; // @synthesize needPassportInfo=_needPassportInfo;
@property(nonatomic) _Bool hasPassportInfo; // @synthesize hasPassportInfo=_hasPassportInfo;
@property(retain, nonatomic) NSString *passportOrganization; // @synthesize passportOrganization=_passportOrganization;
@property(retain, nonatomic) NSString *passportIssueDate; // @synthesize passportIssueDate=_passportIssueDate;
@property(retain, nonatomic) NSString *passportNo; // @synthesize passportNo=_passportNo;
@property(retain, nonatomic) NSString *passportName; // @synthesize passportName=_passportName;
@property(retain, nonatomic) NSString *errorField; // @synthesize errorField=_errorField;
@property(retain, nonatomic) NSString *updateHint; // @synthesize updateHint=_updateHint;
@property(nonatomic) _Bool needUpdate; // @synthesize needUpdate=_needUpdate;
@property(retain, nonatomic) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
@property(retain, nonatomic) NSString *encryptCpf; // @synthesize encryptCpf=_encryptCpf;
@property(retain, nonatomic) NSString *cpfNumber; // @synthesize cpfNumber=_cpfNumber;
@property(retain, nonatomic) NSString *mobileNo; // @synthesize mobileNo=_mobileNo;
@property(retain, nonatomic) NSString *phoneCountry; // @synthesize phoneCountry=_phoneCountry;
@property(retain, nonatomic) NSString *address2; // @synthesize address2=_address2;
@property(retain, nonatomic) NSString *contactPerson; // @synthesize contactPerson=_contactPerson;
@property(retain, nonatomic) NSString *zipCode; // @synthesize zipCode=_zipCode;
@property(retain, nonatomic) NSString *displayCountry; // @synthesize displayCountry=_displayCountry;
@property(retain, nonatomic) NSString *country; // @synthesize country=_country;
@property(retain, nonatomic) NSString *province; // @synthesize province=_province;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSString *address; // @synthesize address=_address;
@property(retain, nonatomic) NSString *addressId; // @synthesize addressId=_addressId;
- (void).cxx_destruct;	// IMP=0x000000010062c1a4
- (void)keyValuesDidFinishConvertingToObject;	// IMP=0x000000010062b81c
- (id)newValueFromOldValue:(id)arg1 property:(id)arg2;	// IMP=0x000000010062b5d4
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;	// IMP=0x000000010062b444
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010062ada8
- (id)cellModel;	// IMP=0x000000010062c878
- (id)viewModel;	// IMP=0x000000010062c3ec

@end

