//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (MASAdditions)
- (id)mas_commonSuperviewOfViews;	// IMP=0x0000000101340c9c
- (void)mas_distributeViewsAlongAxis:(unsigned long long)arg1 withFixedItemLength:(double)arg2 leadSpacing:(double)arg3 tailSpacing:(double)arg4;	// IMP=0x000000010134003c
- (void)mas_distributeViewsAlongAxis:(unsigned long long)arg1 withFixedSpacing:(double)arg2 leadSpacing:(double)arg3 tailSpacing:(double)arg4;	// IMP=0x000000010133f68c
- (id)mas_remakeConstraints:(CDUnknownBlockType)arg1;	// IMP=0x000000010133f4f4
- (id)mas_updateConstraints:(CDUnknownBlockType)arg1;	// IMP=0x000000010133f35c
- (id)mas_makeConstraints:(CDUnknownBlockType)arg1;	// IMP=0x000000010133f1c4
@end

