//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (TBJSONModel)
- (id)toJSONArray;	// IMP=0x00000001016b6890
- (id)modelArrayWithClass:(Class)arg1;	// IMP=0x00000001016b665c
@end

