//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (Property)
+ (id)totalObjectWithSelector:(SEL)arg1 key:(const char *)arg2;	// IMP=0x0000000101337b50
+ (void)setupObjectWithBlock:(CDUnknownBlockType)arg1 key:(const char *)arg2;	// IMP=0x0000000101337ae0
+ (id)totalAllowedCodingPropertyNames;	// IMP=0x0000000101337ac4
+ (void)setupAllowedCodingPropertyNames:(CDUnknownBlockType)arg1;	// IMP=0x0000000101337ab0
+ (id)totalAllowedPropertyNames;	// IMP=0x0000000101337a94
+ (void)setupAllowedPropertyNames:(CDUnknownBlockType)arg1;	// IMP=0x0000000101337a80
+ (id)totalIgnoredCodingPropertyNames;	// IMP=0x0000000101337a64
+ (void)setupIgnoredCodingPropertyNames:(CDUnknownBlockType)arg1;	// IMP=0x0000000101337a50
+ (id)totalIgnoredPropertyNames;	// IMP=0x0000000101337a34
+ (void)setupIgnoredPropertyNames:(CDUnknownBlockType)arg1;	// IMP=0x0000000101337a20
+ (void)setupReplacedKeyFromPropertyName121:(CDUnknownBlockType)arg1;	// IMP=0x0000000101337864
+ (void)setupReplacedKeyFromPropertyName:(CDUnknownBlockType)arg1;	// IMP=0x00000001013376c0
+ (void)setupObjectClassInArray:(CDUnknownBlockType)arg1;	// IMP=0x000000010133752c
+ (id)getNewValueFormOldValue:(id)arg1 object:(id)arg2 property:(id)arg3;	// IMP=0x0000000101337228
+ (void)setupNewValueFormOldValue:(CDUnknownBlockType)arg1;	// IMP=0x00000001013371e4
+ (id)properties;	// IMP=0x0000000101336f34
+ (void)enumerateAllClasses:(CDUnknownBlockType)arg1;	// IMP=0x0000000101336ec4
+ (void)enumerateClasses:(CDUnknownBlockType)arg1;	// IMP=0x0000000101336e24
+ (void)enumerateProperties:(CDUnknownBlockType)arg1;	// IMP=0x0000000101336cdc
+ (Class)propertyObjectClassInArray:(id)arg1;	// IMP=0x00000001013369f4
+ (id)propertyKey:(id)arg1;	// IMP=0x0000000101336558
@end

