//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (TBIvarAccess)
- (void)setIvar:(id)arg1 withCGRect:(struct CGRect)arg2;	// IMP=0x0000000101cc21b8
- (void)setIvar:(id)arg1 withCGSize:(struct CGSize)arg2;	// IMP=0x0000000101cc20ec
- (void)setIvar:(id)arg1 withCGPoint:(struct CGPoint)arg2;	// IMP=0x0000000101cc2014
- (void)setIvar:(id)arg1 withPointer:(void *)arg2;	// IMP=0x0000000101cc1f64
- (void)setIvar:(id)arg1 withBool:(_Bool)arg2;	// IMP=0x0000000101cc1eb4
- (void)setIvar:(id)arg1 withCGFloat:(double)arg2;	// IMP=0x0000000101cc1df0
- (void)setIvar:(id)arg1 withDouble:(double)arg2;	// IMP=0x0000000101cc1d24
- (void)setIvar:(id)arg1 withFloat:(float)arg2;	// IMP=0x0000000101cc1c70
- (void)setIvar:(id)arg1 withUnsignedLongLong:(unsigned long long)arg2;	// IMP=0x0000000101cc1ba4
- (void)setIvar:(id)arg1 withUnsignedLong:(unsigned long long)arg2;	// IMP=0x0000000101cc1ac8
- (void)setIvar:(id)arg1 withUnsignedInt:(unsigned int)arg2;	// IMP=0x0000000101cc19e4
- (void)setIvar:(id)arg1 withUnsignedShort:(unsigned short)arg2;	// IMP=0x0000000101cc190c
- (void)setIvar:(id)arg1 withUnsignedChar:(unsigned char)arg2;	// IMP=0x0000000101cc185c
- (void)setIvar:(id)arg1 withLongLong:(long long)arg2;	// IMP=0x0000000101cc17a0
- (void)setIvar:(id)arg1 withInteger:(long long)arg2;	// IMP=0x0000000101cc16d4
- (void)setIvar:(id)arg1 withLong:(long long)arg2;	// IMP=0x0000000101cc1610
- (void)setIvar:(id)arg1 withInt:(int)arg2;	// IMP=0x0000000101cc1564
- (void)setIvar:(id)arg1 withShort:(short)arg2;	// IMP=0x0000000101cc14a0
- (void)setIvar:(id)arg1 withChar:(BOOL)arg2;	// IMP=0x0000000101cc13dc
- (void)setIvar:(id)arg1 withObject:(id)arg2;	// IMP=0x0000000101cc12f0
- (struct CGRect)getIvarCGRect:(id)arg1;	// IMP=0x0000000101cc1220
- (struct CGSize)getIvarCGSize:(id)arg1;	// IMP=0x0000000101cc114c
- (struct CGPoint)getIvarCGPoint:(id)arg1;	// IMP=0x0000000101cc108c
- (void *)getIvarPointer:(id)arg1;	// IMP=0x0000000101cc0fd8
- (_Bool)getIvarBool:(id)arg1;	// IMP=0x0000000101cc0f00
- (double)getIvarCGFloat:(id)arg1;	// IMP=0x0000000101cc0e58
- (double)getIvarDouble:(id)arg1;	// IMP=0x0000000101cc0da8
- (float)getIvarFloat:(id)arg1;	// IMP=0x0000000101cc0cf8
- (unsigned long long)getIvarUnsignedLongLong:(id)arg1;	// IMP=0x0000000101cc0c38
- (unsigned long long)getIvarUnsignedLong:(id)arg1;	// IMP=0x0000000101cc0b68
- (unsigned int)getIvarUnsignedInt:(id)arg1;	// IMP=0x0000000101cc0ac4
- (unsigned short)getIvarUnsignedShort:(id)arg1;	// IMP=0x0000000101cc0a00
- (unsigned char)getIvarUnsignedChar:(id)arg1;	// IMP=0x0000000101cc0944
- (long long)getIvarLongLong:(id)arg1;	// IMP=0x0000000101cc0868
- (long long)getIvarInteger:(id)arg1;	// IMP=0x0000000101cc079c
- (long long)getIvarLong:(id)arg1;	// IMP=0x0000000101cc06e8
- (int)getIvarInt:(id)arg1;	// IMP=0x0000000101cc0634
- (short)getIvarShort:(id)arg1;	// IMP=0x0000000101cc0580
- (BOOL)getIvarChar:(id)arg1;	// IMP=0x0000000101cc04c8
- (id)getIvarObject:(id)arg1;	// IMP=0x0000000101cc0410
- (struct objc_ivar *)getIvar:(id)arg1;	// IMP=0x0000000101cc01e8
- (id)getIvars;	// IMP=0x0000000101cbfba8
@end

