//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NWConnectionOption : NSObject
{
    _Bool _isForceLocalDNS;	// 8 = 0x8
    int _connectionType;	// 12 = 0xc
    int _httpFrameworkType;	// 16 = 0x10
    id _userInfo;	// 24 = 0x18
}

@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) _Bool isForceLocalDNS; // @synthesize isForceLocalDNS=_isForceLocalDNS;
@property(nonatomic) int httpFrameworkType; // @synthesize httpFrameworkType=_httpFrameworkType;
@property(nonatomic) int connectionType; // @synthesize connectionType=_connectionType;
- (void).cxx_destruct;	// IMP=0x0000000101399e04
- (id)init;	// IMP=0x0000000101399cf4

@end

