//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "TTTAttributedLabelDelegate.h"

@class NSString, TTTAttributedLabel, UILabel;

@interface PackageInfoView : UIView <TTTAttributedLabelDelegate>
{
    UILabel *_partialShipmentL;	// 8 = 0x8
    TTTAttributedLabel *_carrierL;	// 16 = 0x10
    UILabel *_trackingNumberL;	// 24 = 0x18
    UILabel *_sendTimeL;	// 32 = 0x20
    UIView *_sepratorLine;	// 40 = 0x28
    long long _packageIndex;	// 48 = 0x30
    NSString *_currentCopyString;	// 56 = 0x38
}

@property(copy, nonatomic) NSString *currentCopyString; // @synthesize currentCopyString=_currentCopyString;
@property(nonatomic) long long packageIndex; // @synthesize packageIndex=_packageIndex;
@property(retain) UIView *sepratorLine; // @synthesize sepratorLine=_sepratorLine;
@property(retain, nonatomic) UILabel *sendTimeL; // @synthesize sendTimeL=_sendTimeL;
@property(retain, nonatomic) UILabel *trackingNumberL; // @synthesize trackingNumberL=_trackingNumberL;
@property(retain, nonatomic) TTTAttributedLabel *carrierL; // @synthesize carrierL=_carrierL;
@property(retain, nonatomic) UILabel *partialShipmentL; // @synthesize partialShipmentL=_partialShipmentL;
- (void).cxx_destruct;	// IMP=0x000000010012b494
- (void)copy:(id)arg1;	// IMP=0x000000010012b2c4
- (_Bool)canBecomeFirstResponder;	// IMP=0x000000010012b2bc
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;	// IMP=0x000000010012b2a8
- (void)longPressTrackingNumber:(id)arg1;	// IMP=0x000000010012b174
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;	// IMP=0x000000010012b104
- (void)resizeFrame;	// IMP=0x000000010012a2b0
- (void)bindData:(id)arg1;	// IMP=0x0000000100129a0c
- (void)setupUI;	// IMP=0x0000000100129460
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100129408

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

