//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PMInfoMessage.h"

@class NSData;

@interface PMDataMessage : PMInfoMessage
{
    NSData *_data;	// 104 = 0x68
}

@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;	// IMP=0x00000001013fd98c
- (void)fromDictionary:(id)arg1;	// IMP=0x00000001013fd860
- (id)toDictionary;	// IMP=0x00000001013fd77c
- (void)fromMKTP2PMessage:(id)arg1;	// IMP=0x00000001013fd6d8
- (void)fromMKTInfoMessage:(id)arg1;	// IMP=0x00000001013fd634

@end

