//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface PMStatusTopic : NSObject
{
    NSString *_topic;	// 8 = 0x8
    NSMutableDictionary *_tags;	// 16 = 0x10
}

@property(retain, nonatomic) NSMutableDictionary *tags; // @synthesize tags=_tags;
@property(retain, nonatomic) NSString *topic; // @synthesize topic=_topic;
- (void).cxx_destruct;	// IMP=0x0000000101403538

@end

