//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface PMStatusCenter : NSObject
{
    NSMutableDictionary *_topics;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x0000000101403760
@property(retain, nonatomic) NSMutableDictionary *topics; // @synthesize topics=_topics;
- (void).cxx_destruct;	// IMP=0x0000000101405b74
- (id)getBizKey:(id)arg1;	// IMP=0x0000000101405ac4
- (id)getBizTag:(id)arg1;	// IMP=0x0000000101405a98
- (long long)unbindCallback:(id)arg1 param:(id)arg2;	// IMP=0x00000001014058f4
- (long long)bindCallback:(id)arg1 param:(id)arg2;	// IMP=0x000000010140565c
- (id)createTagStatus:(id)arg1;	// IMP=0x00000001014054d8
- (id)getTagStatus:(id)arg1 bizTag:(id)arg2;	// IMP=0x0000000101405428
- (id)createTopicStatus:(id)arg1;	// IMP=0x0000000101405260
- (long long)checkStatusTopic:(id)arg1 param:(id)arg2;	// IMP=0x00000001014050f0
- (id)getStatusTopic:(id)arg1;	// IMP=0x0000000101405068
- (id)getTagStatusByTopic:(id)arg1 bizTag:(id)arg2;	// IMP=0x0000000101404fb8
- (_Bool)getMsgArrive:(id)arg1 bizTag:(id)arg2;	// IMP=0x0000000101404e98
- (void)pullMsgDone:(id)arg1 bizTag:(id)arg2;	// IMP=0x0000000101404d94
- (void)msgArrive:(id)arg1 bizTag:(id)arg2;	// IMP=0x0000000101404c7c
- (id)getPullOffset:(id)arg1 bizTag:(id)arg2;	// IMP=0x0000000101404b74
- (void)updatePull:(id)arg1 bizTag:(id)arg2 offset:(id)arg3;	// IMP=0x0000000101404a64
- (id)getPullInfo:(id)arg1 bizTag:(id)arg2;	// IMP=0x00000001014048b4
- (void)setPullInfo:(id)arg1 bizTag:(id)arg2 pullInfo:(id)arg3;	// IMP=0x000000010140473c
- (_Bool)needPullMsg:(id)arg1 bizTag:(id)arg2;	// IMP=0x0000000101404624
- (_Bool)haveListener:(id)arg1 bizTag:(id)arg2;	// IMP=0x000000010140453c
- (id)getCallback:(id)arg1;	// IMP=0x00000001014042e8
- (long long)getStatus:(id)arg1 bizTag:(id)arg2;	// IMP=0x00000001014041e8
- (void)setStatus:(id)arg1 bizTag:(id)arg2 status:(long long)arg3;	// IMP=0x00000001014040ec
- (long long)unbind:(id)arg1;	// IMP=0x0000000101403cb0
- (long long)bind:(id)arg1;	// IMP=0x000000010140385c

@end

