//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString;

@interface PMSubscribeProcessor : NSObject
{
    NSString *_topic;	// 8 = 0x8
    NSString *_bizTag;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    NSMutableArray *_subArray;	// 32 = 0x20
    NSMutableArray *_unsubArray;	// 40 = 0x28
}

@property(retain, nonatomic) NSMutableArray *unsubArray; // @synthesize unsubArray=_unsubArray;
@property(retain, nonatomic) NSMutableArray *subArray; // @synthesize subArray=_subArray;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSString *bizTag; // @synthesize bizTag=_bizTag;
@property(retain, nonatomic) NSString *topic; // @synthesize topic=_topic;
- (void).cxx_destruct;	// IMP=0x00000001013fb79c
- (void)unsubscribeCallback:(id)arg1 result:(id)arg2;	// IMP=0x00000001013fb5b0
- (void)subscribeCallback:(id)arg1 result:(id)arg2;	// IMP=0x00000001013fb52c
- (void)unsubCallbackProc:(id)arg1;	// IMP=0x00000001013fb290
- (void)subCallbackProc:(id)arg1;	// IMP=0x00000001013fb00c
- (void)unSubscribeSend:(id)arg1;	// IMP=0x00000001013fa990
- (void)procUnSubscribeStatus:(id)arg1;	// IMP=0x00000001013fa1e8
- (void)subscribeSend:(id)arg1;	// IMP=0x00000001013f9b54
- (void)procSubscribeStatus:(id)arg1;	// IMP=0x00000001013f932c
- (void)unsubscribe:(id)arg1 withCallback:(CDUnknownBlockType)arg2;	// IMP=0x00000001013f9020
- (void)subscribe:(id)arg1 withCallback:(CDUnknownBlockType)arg2;	// IMP=0x00000001013f8e64
- (id)init;	// IMP=0x00000001013f8d70

@end

