//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PMSystem : NSObject
{
    _Bool _isAllAck;	// 8 = 0x8
}

+ (void)allAck:(id)arg1;	// IMP=0x0000000101418470
+ (id)parse:(id)arg1;	// IMP=0x00000001014183a4
+ (_Bool)isAllAck;	// IMP=0x0000000101418320
+ (id)sharedInstance;	// IMP=0x0000000101418284
@property(nonatomic) _Bool isAllAck; // @synthesize isAllAck=_isAllAck;

@end

