//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ProductService : NSObject
{
    id <ProductDetailDelegate> delegate;	// 8 = 0x8
}

+ (void)checkPresaleCoinsWithProductID:(id)arg1 skuAttr:(id)arg2 callback:(CDUnknownBlockType)arg3;	// IMP=0x00000001006386d8
+ (void)getProductCoinsEnoughToBookWithProductID:(id)arg1 skuAttr:(id)arg2 callback:(CDUnknownBlockType)arg3;	// IMP=0x00000001006383fc
- (void).cxx_destruct;	// IMP=0x0000000100638c64
- (void)getProductDetailRecommendItems:(id)arg1 scene:(id)arg2 recommendInfo:(id)arg3;	// IMP=0x0000000100637ec8
- (void)getProductVouchersWithProductID:(id)arg1 page:(id)arg2;	// IMP=0x0000000100637b10
- (void)getProductDetailStoreInfoWithSellerAdminSeq:(id)arg1 sellerCompanyId:(id)arg2 productId:(id)arg3;	// IMP=0x00000001006377b0
- (void)getProductSKUListByProductId:(id)arg1 promotionId:(id)arg2;	// IMP=0x000000010063747c
- (void)getProductSKUPriceByProductId:(id)arg1 andSkuAttr:(id)arg2 promotionId:(id)arg3 promotionType:(id)arg4;	// IMP=0x00000001006370e0
- (void)getProductSKUPriceByProductId:(id)arg1 andSkuAttr:(id)arg2;	// IMP=0x0000000100636da0
- (void)requestProductDescriptionByProductId:(id)arg1;	// IMP=0x0000000100636afc
- (void)requestGroupProductDetailByProductId:(id)arg1 promotionId:(id)arg2;	// IMP=0x0000000100636790
- (void)requestProductDetailByProductId:(id)arg1 timeZone:(id)arg2;	// IMP=0x0000000100636478
- (void)requestProductDetailByProductId:(id)arg1;	// IMP=0x000000010063635c
- (id)initWithProductDetailDelegate:(id)arg1;	// IMP=0x00000001006362e4

@end

