//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RACSubject.h"

@interface RACBehaviorSubject : RACSubject
{
    id _currentValue;	// 8 = 0x8
}

+ (id)behaviorSubjectWithDefaultValue:(id)arg1;	// IMP=0x00000001014306f8
@property(retain, nonatomic) id currentValue; // @synthesize currentValue=_currentValue;
- (void).cxx_destruct;	// IMP=0x0000000101430b3c
- (void)sendNext:(id)arg1;	// IMP=0x0000000101430a74
- (id)subscribe:(id)arg1;	// IMP=0x0000000101430764

@end

