//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSError;

@interface RACEvent : NSObject <NSCopying>
{
    unsigned long long _eventType;	// 8 = 0x8
    id _object;	// 16 = 0x10
}

+ (id)eventWithValue:(id)arg1;	// IMP=0x0000000101436d04
+ (id)eventWithError:(id)arg1;	// IMP=0x0000000101436c98
+ (id)completedEvent;	// IMP=0x0000000101436bdc
@property(readonly, nonatomic) id object; // @synthesize object=_object;
@property(readonly, nonatomic) unsigned long long eventType; // @synthesize eventType=_eventType;
- (void).cxx_destruct;	// IMP=0x0000000101437158
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000101436fd4
- (unsigned long long)hash;	// IMP=0x0000000101436f70
- (id)description;	// IMP=0x0000000101436e20
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000101436e1c
- (id)initWithEventType:(unsigned long long)arg1 object:(id)arg2;	// IMP=0x0000000101436d6c
@property(readonly, nonatomic) id value;
@property(readonly, nonatomic) NSError *error;
@property(readonly, nonatomic, getter=isFinished) _Bool finished;

@end

