//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RACSequence.h"

@class NSData;

@interface RACIndexSetSequence : RACSequence
{
    NSData *_data;	// 8 = 0x8
    const unsigned long long *_indexes;	// 16 = 0x10
    unsigned long long _count;	// 24 = 0x18
}

+ (id)sequenceWithIndexSetSequence:(id)arg1 offset:(unsigned long long)arg2;	// IMP=0x0000000101437b70
+ (id)sequenceWithIndexSet:(id)arg1;	// IMP=0x0000000101437a20
@property(readonly, nonatomic) unsigned long long count; // @synthesize count=_count;
@property(readonly, nonatomic) const unsigned long long *indexes; // @synthesize indexes=_indexes;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;	// IMP=0x0000000101437fd4
- (id)description;	// IMP=0x0000000101437e28
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;	// IMP=0x0000000101437d08
- (id)tail;	// IMP=0x0000000101437c90
- (id)head;	// IMP=0x0000000101437c54

@end

