//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISecurityGuardAVMPSoftCert.h"

@class NSString;

@interface SecurityGuardAVMPSoftCert : NSObject <ISecurityGuardAVMPSoftCert>
{
}

- (Class)getMetaClass;	// IMP=0x000000010149b3a4
- (id)getCert:(id)arg1;	// IMP=0x000000010149b2c4
- (_Bool)installCert:(id)arg1 certInfo:(id)arg2;	// IMP=0x000000010149b18c
- (_Bool)verifyWithCert:(id)arg1 signature:(id)arg2 plainData:(id)arg3 type:(int)arg4;	// IMP=0x000000010149b03c
- (id)signWithCert:(id)arg1 data:(id)arg2 type:(int)arg3;	// IMP=0x000000010149af1c
- (id)generateCSR:(id)arg1 info:(id)arg2 type:(int)arg3;	// IMP=0x000000010149ae04

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

