//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISecurityGuardOpenStaticKeyEncrypt.h"

@class NSString;

@interface SecurityGuardOpenStaticKeyEncrypt : NSObject <ISecurityGuardOpenStaticKeyEncrypt>
{
}

- (Class)getMetaClass;	// IMP=0x000000010153b380
- (id)getSeedValue:(id)arg1;	// IMP=0x000000010153a6b4
- (CDStruct_f8bc7150 *)cryptorServiceWithKey:(id)arg1 value:(id)arg2 mode:(long long)arg3 option:(long long)arg4 keyOption:(long long)arg5;	// IMP=0x0000000101539d98
- (id)encryptSecretData:(long long)arg1 key:(id)arg2 dataKey:(id)arg3;	// IMP=0x0000000101539260
- (id)decrypt:(long long)arg1 key:(id)arg2 data:(id)arg3;	// IMP=0x0000000101538cf8
- (id)encrypt:(long long)arg1 key:(id)arg2 data:(id)arg3;	// IMP=0x0000000101538308
- (int)removeSecret:(id)arg1;	// IMP=0x0000000101537de4
- (_Bool)isSecretExist:(id)arg1;	// IMP=0x0000000101537914
- (int)saveSecret:(id)arg1 value:(id)arg2;	// IMP=0x000000010153713c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

