//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISecurityGuardRootDetect.h"

@class NSString;

@interface SecurityGuardRootDetect : NSObject <ISecurityGuardRootDetect>
{
}

- (Class)getMetaClass;	// IMP=0x00000001015b2370
- (_Bool)isRoot;	// IMP=0x00000001015b22ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

