//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISecurityGuardUATrace.h"

@class NSString;

@interface SecurityGuardUATrace : NSObject <ISecurityGuardUATrace>
{
}

- (id)getTraceData;	// IMP=0x00000001015e3204
- (void)onSensorChanged:(id)arg1 xCoordinate:(float)arg2 yCoordinate:(float)arg3 zCoordinate:(float)arg4;	// IMP=0x00000001015e319c
- (void)onTouchScreen:(id)arg1 ctrl:(id)arg2 touchEventPoint:(struct CGPoint *)arg3;	// IMP=0x00000001015e3020
- (void)onFocusChange:(id)arg1 ctrl:(id)arg2 GetorLost:(_Bool)arg3;	// IMP=0x00000001015e2f7c
- (void)onPwdKeyDown:(id)arg1 ctrl:(id)arg2;	// IMP=0x00000001015e2ed0
- (void)onKeyDown:(id)arg1 ctrl:(id)arg2 KeyCode:(id)arg3;	// IMP=0x00000001015e2d2c
- (void)onControlClick:(id)arg1 ctrl:(id)arg2;	// IMP=0x00000001015e2ca4
- (void)onNewPage:(id)arg1;	// IMP=0x00000001015e2c44
- (unsigned char)setUAParam:(id)arg1 ctrl:(id)arg2 event:(int)arg3 data:(void *)arg4;	// IMP=0x00000001015e29d8
- (Class)getMetaClass;	// IMP=0x00000001015e2974

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

