//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SharkfoodMuteSwitchDetector : NSObject
{
    _Bool _isMute;	// 8 = 0x8
    _Bool _forceEmit;	// 9 = 0x9
    _Bool _isPaused;	// 10 = 0xa
    _Bool _isPlaying;	// 11 = 0xb
    unsigned int _soundId;	// 12 = 0xc
    CDUnknownBlockType _silentNotify;	// 16 = 0x10
    double _interval;	// 24 = 0x18
}

+ (id)shared;	// IMP=0x00000001017f639c
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(nonatomic) _Bool isPaused; // @synthesize isPaused=_isPaused;
@property(nonatomic) _Bool forceEmit; // @synthesize forceEmit=_forceEmit;
@property(nonatomic) unsigned int soundId; // @synthesize soundId=_soundId;
@property(nonatomic) double interval; // @synthesize interval=_interval;
@property(copy, nonatomic) CDUnknownBlockType silentNotify; // @synthesize silentNotify=_silentNotify;
@property(readonly, nonatomic) _Bool isMute; // @synthesize isMute=_isMute;
- (void).cxx_destruct;	// IMP=0x00000001017f6770
- (void)dealloc;	// IMP=0x00000001017f65fc
- (void)loopCheck;	// IMP=0x00000001017f657c
- (void)complete;	// IMP=0x00000001017f6448
- (void)scheduleCall;	// IMP=0x00000001017f63e8
- (void)willReturnToForeground;	// IMP=0x00000001017f6338
- (void)didEnterBackground;	// IMP=0x00000001017f6328
- (id)init;	// IMP=0x00000001017f6104

@end

