//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "StackTile.h"

@interface StickStackTile : StackTile
{
    long long _stickBorder;	// 8 = 0x8
}

@property(nonatomic) long long stickBorder; // @synthesize stickBorder=_stickBorder;

@end

