//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface storeInfoItemDTO : NSObject
{
    NSString *_adminMemberId;	// 8 = 0x8
    NSString *_home;	// 16 = 0x10
    NSString *_storeInfoid;	// 24 = 0x18
    NSString *_name;	// 32 = 0x20
}

@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *storeInfoid; // @synthesize storeInfoid=_storeInfoid;
@property(copy, nonatomic) NSString *home; // @synthesize home=_home;
@property(copy, nonatomic) NSString *adminMemberId; // @synthesize adminMemberId=_adminMemberId;
- (void).cxx_destruct;	// IMP=0x0000000100c94940

@end

