//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface storeTxtInfo : NSObject
{
    NSString *_viewProducts;	// 8 = 0x8
    NSString *_positiveFeedback;	// 16 = 0x10
}

@property(retain) NSString *positiveFeedback; // @synthesize positiveFeedback=_positiveFeedback;
@property(retain) NSString *viewProducts; // @synthesize viewProducts=_viewProducts;
- (void).cxx_destruct;	// IMP=0x00000001006256c8

@end

