//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UIActivityIndicatorView, UIScrollView;

@interface SVInfiniteScrollingView : UIView
{
    _Bool _enabled;	// 8 = 0x8
    _Bool _wasTriggeredByUser;	// 9 = 0x9
    _Bool _isObserving;	// 10 = 0xa
    CDUnknownBlockType infiniteScrollingHandler;	// 16 = 0x10
    long long activityIndicatorViewStyle;	// 24 = 0x18
    unsigned long long _state;	// 32 = 0x20
    UIScrollView *_scrollView;	// 40 = 0x28
    UIActivityIndicatorView *_activityIndicatorView;	// 48 = 0x30
    NSMutableArray *_viewForState;	// 56 = 0x38
    double _originalBottomInset;	// 64 = 0x40
}

@property(nonatomic) _Bool isObserving; // @synthesize isObserving=_isObserving;
@property(nonatomic) _Bool wasTriggeredByUser; // @synthesize wasTriggeredByUser=_wasTriggeredByUser;
@property(nonatomic) double originalBottomInset; // @synthesize originalBottomInset=_originalBottomInset;
@property(retain, nonatomic) NSMutableArray *viewForState; // @synthesize viewForState=_viewForState;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(copy, nonatomic) CDUnknownBlockType infiniteScrollingHandler; // @synthesize infiniteScrollingHandler;
- (void).cxx_destruct;	// IMP=0x00000001015ef034
- (void)stopAnimating;	// IMP=0x00000001015eea64
- (void)startAnimating;	// IMP=0x00000001015eea54
- (void)triggerRefresh;	// IMP=0x00000001015eea18
@property(nonatomic) long long activityIndicatorViewStyle; // @synthesize activityIndicatorViewStyle;
- (void)setCustomView:(id)arg1 forState:(unsigned long long)arg2;	// IMP=0x00000001015ee878
- (void)scrollViewDidScroll:(struct CGPoint)arg1;	// IMP=0x00000001015ee5c4
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001015ee47c
- (void)setScrollViewContentInset:(struct UIEdgeInsets)arg1;	// IMP=0x00000001015ee368
- (void)setScrollViewContentInsetForInfiniteScrolling;	// IMP=0x00000001015ee2d0
- (void)resetScrollViewContentInset;	// IMP=0x00000001015ee240
- (void)layoutSubviews;	// IMP=0x00000001015ee1b8
- (void)willMoveToSuperview:(id)arg1;	// IMP=0x00000001015ee0cc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001015edfe4

@end

