//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBAccsUtil : NSObject
{
}

+ (void)flowAnalysisWithBizid:(id)arg1 upSize:(id)arg2 downSize:(id)arg3;	// IMP=0x000000010160d224
+ (id)base64EncodedStringFrom:(id)arg1;	// IMP=0x000000010160d014
+ (id)dataWithBase64EncodedString:(id)arg1;	// IMP=0x000000010160cd90
+ (id)getShortDateString:(id)arg1;	// IMP=0x000000010160cc88
+ (id)dataToString:(id)arg1;	// IMP=0x000000010160cbd4
+ (id)getDocPath;	// IMP=0x000000010160cb78
+ (id)appVersion;	// IMP=0x000000010160caf0
+ (id)sdkVersion;	// IMP=0x000000010160cab8
+ (id)getStringDateByDate:(id)arg1 formate:(id)arg2;	// IMP=0x000000010160c9a8
+ (id)getStringDateByDate:(id)arg1;	// IMP=0x000000010160c854
+ (id)makeCallBackDictByRequest:(id)arg1 entity:(id)arg2;	// IMP=0x000000010160c51c
+ (id)getDataID;	// IMP=0x000000010160c494
+ (id)currentDate;	// IMP=0x000000010160c390
+ (id)getDeviceModel;	// IMP=0x000000010160bf38
+ (id)appStatus;	// IMP=0x000000010160bec4
+ (id)getAppVersion;	// IMP=0x000000010160be3c

@end

