//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBDecoder : NSObject
{
}

+ (int)computeInitialSampleSize:(struct CGSize)arg1 minSideLength:(int)arg2 maxNumOfPixels:(int)arg3;	// IMP=0x0000000101671590
+ (int)computeSampleSize:(struct CGSize)arg1 minSideLength:(int)arg2 maxNumOfPixels:(int)arg3;	// IMP=0x000000010167153c
+ (id)decodeUIImage:(id)arg1 type:(int)arg2;	// IMP=0x00000001016711ac
+ (id)decodeUIImage:(id)arg1;	// IMP=0x000000010167119c
+ (id)decodeCVPixelBuffer:(struct __CVBuffer *)arg1 rectOfInterest:(struct CGRect)arg2 resample:(_Bool)arg3 type:(int)arg4;	// IMP=0x0000000101670b64

@end

