//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSMutableArray, NSString, NSURLRequest, TBDownloadResult;

@interface TBDownloadTask : NSObject <NSCopying>
{
    unsigned long long _retryTimes;	// 8 = 0x8
    unsigned long long _maxRetryTimes;	// 16 = 0x10
    _Bool _haveStarted;	// 24 = 0x18
    NSString *_relativeDestination;	// 32 = 0x20
    _Bool _forceDownload;	// 40 = 0x28
    _Bool _isBackgroundTask;	// 41 = 0x29
    _Bool _needCallBackWhenConditionNotSatisfied;	// 42 = 0x2a
    int _condition;	// 44 = 0x2c
    int _state;	// 48 = 0x30
    long long _priority;	// 56 = 0x38
    NSURLRequest *_request;	// 64 = 0x40
    NSString *_destination;	// 72 = 0x48
    NSString *_MD5;	// 80 = 0x50
    unsigned long long _size;	// 88 = 0x58
    double _downloadProgress;	// 96 = 0x60
    CDUnknownBlockType _completionHandler;	// 104 = 0x68
    CDUnknownBlockType _progressHandler;	// 112 = 0x70
    TBDownloadResult *_result;	// 120 = 0x78
    double _timestamp;	// 128 = 0x80
    NSMutableArray *_duplicateTaskArray;	// 136 = 0x88
    TBDownloadTask *_masterTask;	// 144 = 0x90
}

@property(nonatomic) __weak TBDownloadTask *masterTask; // @synthesize masterTask=_masterTask;
@property(retain, nonatomic) NSMutableArray *duplicateTaskArray; // @synthesize duplicateTaskArray=_duplicateTaskArray;
@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) TBDownloadResult *result; // @synthesize result=_result;
@property(copy, nonatomic) CDUnknownBlockType progressHandler; // @synthesize progressHandler=_progressHandler;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) _Bool needCallBackWhenConditionNotSatisfied; // @synthesize needCallBackWhenConditionNotSatisfied=_needCallBackWhenConditionNotSatisfied;
@property(nonatomic) _Bool isBackgroundTask; // @synthesize isBackgroundTask=_isBackgroundTask;
@property(nonatomic) _Bool forceDownload; // @synthesize forceDownload=_forceDownload;
@property(nonatomic) double downloadProgress; // @synthesize downloadProgress=_downloadProgress;
@property(readonly, nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *MD5; // @synthesize MD5=_MD5;
@property(retain, nonatomic) NSString *destination; // @synthesize destination=_destination;
@property(readonly, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(nonatomic) int condition; // @synthesize condition=_condition;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
- (void).cxx_destruct;	// IMP=0x000000010164ed34
- (id)toJSONString;	// IMP=0x000000010164e570
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010164e450
- (id)description;	// IMP=0x000000010164e388
- (id)conditionString;	// IMP=0x000000010164e33c
- (id)stateString;	// IMP=0x000000010164e288
- (id)priorityString;	// IMP=0x000000010164e218
@property(nonatomic) unsigned long long maxRetryTimes;
@property(nonatomic) unsigned long long retryTimes;
- (long long)compareWith:(id)arg1;	// IMP=0x000000010164e0e8
- (void)completeWithResponse:(id)arg1 error:(id)arg2;	// IMP=0x000000010164dc4c
- (void)finishLoadingToURL:(id)arg1;	// IMP=0x000000010164d468
- (void)totalBytesWritten:(long long)arg1 totalBytesExpectedToWrite:(long long)arg2;	// IMP=0x000000010164d158
- (void)conditionNotSatisfied;	// IMP=0x000000010164cd74
- (id)conditionNotSatisfiedError;	// IMP=0x000000010164cd50
- (void)setMaterTask:(id)arg1;	// IMP=0x000000010164cd3c
- (id)duplicateTasks;	// IMP=0x000000010164cd0c
- (void)addDuplicateTask:(id)arg1;	// IMP=0x000000010164cbb4
- (_Bool)duplicateWithTask:(id)arg1;	// IMP=0x000000010164ca8c
@property(readonly, nonatomic) NSString *relativeDestination;
- (void)setState:(int)arg1;	// IMP=0x000000010164c660
- (void)resume;	// IMP=0x000000010164c610
- (void)cancel;	// IMP=0x000000010164c5c0
- (void)start;	// IMP=0x000000010164c234
- (_Bool)haveValidFile;	// IMP=0x000000010164bd9c
- (void)suspend;	// IMP=0x000000010164bd4c
- (void)dealloc;	// IMP=0x000000010164bd14
- (id)initWithURL:(id)arg1 progressHandler:(CDUnknownBlockType)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010164bb04
- (id)initWithRequest:(id)arg1 destination:(id)arg2 priority:(long long)arg3 progressHandler:(CDUnknownBlockType)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x000000010164ba44
- (id)initWithJSON:(id)arg1;	// IMP=0x000000010164b23c
- (id)initWithRequest:(id)arg1 destination:(id)arg2 priority:(long long)arg3 condition:(int)arg4 MD5:(id)arg5 size:(unsigned long long)arg6 needCallBackWhenConditionNotSatisfied:(_Bool)arg7 forceDownload:(_Bool)arg8 isBackgroundTask:(_Bool)arg9 progressHandler:(CDUnknownBlockType)arg10 completionHandler:(CDUnknownBlockType)arg11;	// IMP=0x000000010164b02c

@end

