//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBDTPathHelper : NSObject
{
}

+ (id)fullPathForTaskConfig:(id)arg1;	// IMP=0x0000000101653ea0
+ (id)fullPathForRelativePath:(id)arg1;	// IMP=0x0000000101653e04
+ (id)defaultFullDownloadPathForURL:(id)arg1;	// IMP=0x0000000101653da4
+ (id)tbUrlEncoded:(id)arg1;	// IMP=0x0000000101653d38
+ (id)defaultRelativeDownloadPathForURL:(id)arg1;	// IMP=0x0000000101653b2c

@end

