//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBMKT : NSObject
{
}

+ (void)activeService;	// IMP=0x0000000101050f30
+ (void)registerService;	// IMP=0x0000000101050e24
+ (void)startService;	// IMP=0x0000000101050db0

@end

