//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBPopLayerBaseView.h"

@class UIView;

@interface TBPopLayerTrackingView : TBPopLayerBaseView
{
    UIView *_trackedView;	// 8 = 0x8
}

@property(retain, nonatomic) UIView *trackedView; // @synthesize trackedView=_trackedView;
- (void).cxx_destruct;	// IMP=0x000000010175593c
- (_Bool)isTrackingToView:(id)arg1;	// IMP=0x0000000101755888

@end

