//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBSDKPushCenterModel.h"

@class NSString;

@interface TBSDKPushCenterUploadDeviceTokenModel : TBSDKPushCenterModel
{
    NSString *_deviceToken;	// 24 = 0x18
}

+ (_Bool)deviceSystemIsLargeIOS8;	// IMP=0x0000000101421b40
@property(retain, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
- (void).cxx_destruct;	// IMP=0x0000000101422054
- (void)main;	// IMP=0x0000000101421f2c
- (_Bool)isNotificationEnabled;	// IMP=0x0000000101421e6c
- (id)uploadDeviceToken:(id)arg1;	// IMP=0x0000000101421bac

@end

