//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBSDKCacheFile : NSObject
{
}

+ (void)clearAllCache;	// IMP=0x0000000101d13c54
+ (id)fileNameByKey:(id)arg1;	// IMP=0x0000000101d13c1c
+ (id)cacheFilePath:(id)arg1;	// IMP=0x0000000101d13b28
+ (_Bool)cacheFileDelete:(id)arg1;	// IMP=0x0000000101d13a44
+ (_Bool)cacheFileExists:(id)arg1;	// IMP=0x0000000101d13990
+ (_Bool)cacheFileExpired:(id)arg1 expiredSecond:(long long)arg2;	// IMP=0x0000000101d137ec
+ (id)cacheFileGetNSdata:(id)arg1;	// IMP=0x0000000101d13710
+ (id)cacheFileGet:(id)arg1;	// IMP=0x0000000101d135e4
+ (_Bool)cacheFileSetNsdata:(id)arg1 contents:(id)arg2;	// IMP=0x0000000101d13494
+ (_Bool)cacheFileSet:(id)arg1 contents:(id)arg2;	// IMP=0x0000000101d132a8

@end

