//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, NSOperationQueue, NSURL, NSURLCredential, TFEHTTPRequestSerializer<TFEURLRequestSerialization>, TFEHTTPResponseSerializer<TFEURLResponseSerialization>, TFENetworkReachabilityManager, TFESecurityPolicy;

@interface TFEHTTPRequestOperationManager : NSObject <NSSecureCoding, NSCopying>
{
    _Bool _shouldUseCredentialStorage;	// 8 = 0x8
    NSURL *_baseURL;	// 16 = 0x10
    TFEHTTPRequestSerializer<TFEURLRequestSerialization> *_requestSerializer;	// 24 = 0x18
    TFEHTTPResponseSerializer<TFEURLResponseSerialization> *_responseSerializer;	// 32 = 0x20
    NSOperationQueue *_operationQueue;	// 40 = 0x28
    NSURLCredential *_credential;	// 48 = 0x30
    TFESecurityPolicy *_securityPolicy;	// 56 = 0x38
    TFENetworkReachabilityManager *_reachabilityManager;	// 64 = 0x40
    NSObject<OS_dispatch_queue> *_completionQueue;	// 72 = 0x48
    NSObject<OS_dispatch_group> *_completionGroup;	// 80 = 0x50
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00000001010c1a70
+ (id)manager;	// IMP=0x00000001010c0670
@property(retain, nonatomic) NSObject<OS_dispatch_group> *completionGroup; // @synthesize completionGroup=_completionGroup;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *completionQueue; // @synthesize completionQueue=_completionQueue;
@property(retain, nonatomic) TFENetworkReachabilityManager *reachabilityManager; // @synthesize reachabilityManager=_reachabilityManager;
@property(retain, nonatomic) TFESecurityPolicy *securityPolicy; // @synthesize securityPolicy=_securityPolicy;
@property(retain, nonatomic) NSURLCredential *credential; // @synthesize credential=_credential;
@property(nonatomic) _Bool shouldUseCredentialStorage; // @synthesize shouldUseCredentialStorage=_shouldUseCredentialStorage;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) TFEHTTPResponseSerializer<TFEURLResponseSerialization> *responseSerializer; // @synthesize responseSerializer=_responseSerializer;
@property(retain, nonatomic) TFEHTTPRequestSerializer<TFEURLRequestSerialization> *requestSerializer; // @synthesize requestSerializer=_requestSerializer;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (void).cxx_destruct;	// IMP=0x00000001010c20f4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001010c1d84
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001010c1c34
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001010c1a78
- (id)description;	// IMP=0x00000001010c1978
- (id)DELETE:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001010c179c
- (id)PATCH:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001010c15c0
- (id)PUT:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001010c13e4
- (id)POST:(id)arg1 parameters:(id)arg2 constructingBodyWithBlock:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;	// IMP=0x00000001010c11ec
- (id)POST:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001010c1010
- (id)HEAD:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001010c0d90
- (id)GET:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;	// IMP=0x00000001010c0bb4
- (id)HTTPRequestOperationWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;	// IMP=0x00000001010c09b4
- (id)initWithBaseURL:(id)arg1;	// IMP=0x00000001010c06ac
- (id)init;	// IMP=0x00000001010c069c

@end

