//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFEAbstractNetMonitor.h"

@interface TFENetMonitorServiceIOS7AndPlus : TFEAbstractNetMonitor
{
    Class _networkInfo;	// 40 = 0x28
    id _ctTelephonyNetworkInfoInstance;	// 48 = 0x30
}

@property(retain, nonatomic) id ctTelephonyNetworkInfoInstance; // @synthesize ctTelephonyNetworkInfoInstance=_ctTelephonyNetworkInfoInstance;
@property(retain, nonatomic) Class networkInfo; // @synthesize networkInfo=_networkInfo;
- (void).cxx_destruct;	// IMP=0x000000010109da68
- (void)dealloc;	// IMP=0x000000010109d908
- (unsigned long long)getCurrentNetworkTypeFromCTFramework;	// IMP=0x000000010109d5d0
- (unsigned long long)currentNetwork;	// IMP=0x000000010109d51c
- (void)networkChangeInternal;	// IMP=0x000000010109d498
- (void)reachabilityChanged:(id)arg1;	// IMP=0x000000010109d3ec
- (void)radioAccessChange;	// IMP=0x000000010109d35c
- (void)systemForeground;	// IMP=0x000000010109d2cc
- (id)init;	// IMP=0x000000010109cffc

@end

