//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFEHTTPResponseSerializer.h"

@interface TFEXMLParserResponseSerializer : TFEHTTPResponseSerializer
{
}

+ (id)serializer;	// IMP=0x000000010106afb4
- (id)responseObjectForResponse:(id)arg1 data:(id)arg2 error:(id *)arg3;	// IMP=0x000000010106b098
- (id)init;	// IMP=0x000000010106afdc

@end

