//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TileElementProtocol.h"
#import "TileLayoutProtocol.h"

@class AEFloorLayoutAttributesOptions, AETileAdapterFloor, AETileTrackAttributes, NSString, TileEvent, TileStyle;

@interface TileElement : NSObject <TileElementProtocol, TileLayoutProtocol>
{
    _Bool _staticInMemory;	// 8 = 0x8
    TileStyle *_style;	// 16 = 0x10
    TileEvent *_event;	// 24 = 0x18
}

+ (Class)layoutSpecClass;	// IMP=0x0000000101a4de28
+ (id)nib;	// IMP=0x0000000101a4dda4
+ (Class)cellClass;	// IMP=0x0000000101a4dd90
@property(nonatomic) _Bool staticInMemory; // @synthesize staticInMemory=_staticInMemory;
@property(retain, nonatomic) TileEvent *event; // @synthesize event=_event;
@property(retain, nonatomic) TileStyle *style; // @synthesize style=_style;
- (void).cxx_destruct;	// IMP=0x0000000101a4deb0
- (id)reuseIdentifier;	// IMP=0x0000000101a4de3c
- (struct CGSize)fittingSizeWithReferenceSize:(struct CGSize)arg1;	// IMP=0x0000000101a4de24
- (double)estimatedHeightForReferenceWidth:(double)arg1;	// IMP=0x0000000101a4de18
- (double)heightForReferenceWidth:(double)arg1;	// IMP=0x0000000101a4de0c
- (id)generateAdapterFloorIfCanBeFound;	// IMP=0x00000001009feb50
@property(nonatomic) __weak AETileAdapterFloor *component;
@property(retain, nonatomic) AETileTrackAttributes *trackAttributes; // @dynamic trackAttributes;
@property(retain, nonatomic) AEFloorLayoutAttributesOptions *layoutAttributesOptions; // @dynamic layoutAttributesOptions;
- (void)tl_invalidHeightCache;	// IMP=0x0000000101a52760
- (double)tl_cachedHeightForReferenceWidth:(double)arg1;	// IMP=0x0000000101a52638
- (void)tl_cacheHeight:(double)arg1 forReferenceWidth:(double)arg2;	// IMP=0x0000000101a52534
- (id)tl_sizeCache;	// IMP=0x0000000101a524c4
- (void)setTl_sizeCache:(id)arg1;	// IMP=0x0000000101a524b4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

