//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IJKFFPlayerHUDDelegate.h"

@class IJKFFMoviePlayerController, NSString, NSURL;

@interface TMBasicLivePlayer : UIView <IJKFFPlayerHUDDelegate>
{
    _Bool _autoPlay;	// 8 = 0x8
    _Bool _showHUDView;	// 9 = 0x9
    _Bool _backgroundPause;	// 10 = 0xa
    _Bool _videoLoop;	// 11 = 0xb
    _Bool _openCleanVCacheModel;	// 12 = 0xc
    id <TMPlayerDelegate> _delegate;	// 16 = 0x10
    NSURL *_videoURL;	// 24 = 0x18
    unsigned long long _playState;	// 32 = 0x20
    UIView *_videoContent;	// 40 = 0x28
    double _vCacheSecThresholdValue;	// 48 = 0x30
    double _playRate;	// 56 = 0x38
    long long _errorCode;	// 64 = 0x40
    IJKFFMoviePlayerController *_ffPlayer;	// 72 = 0x48
    CDUnknownBlockType _firstVideoFrameRenderedBlock;	// 80 = 0x50
    long long _currentScaleMode;	// 88 = 0x58
}

@property(nonatomic) long long currentScaleMode; // @synthesize currentScaleMode=_currentScaleMode;
@property(copy, nonatomic) CDUnknownBlockType firstVideoFrameRenderedBlock; // @synthesize firstVideoFrameRenderedBlock=_firstVideoFrameRenderedBlock;
@property(retain, nonatomic) IJKFFMoviePlayerController *ffPlayer; // @synthesize ffPlayer=_ffPlayer;
@property(nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
@property(nonatomic) double playRate; // @synthesize playRate=_playRate;
@property(nonatomic) double vCacheSecThresholdValue; // @synthesize vCacheSecThresholdValue=_vCacheSecThresholdValue;
@property(nonatomic) _Bool openCleanVCacheModel; // @synthesize openCleanVCacheModel=_openCleanVCacheModel;
@property(nonatomic) _Bool videoLoop; // @synthesize videoLoop=_videoLoop;
@property(nonatomic) _Bool backgroundPause; // @synthesize backgroundPause=_backgroundPause;
@property(nonatomic) _Bool showHUDView; // @synthesize showHUDView=_showHUDView;
@property(nonatomic) _Bool autoPlay; // @synthesize autoPlay=_autoPlay;
@property(retain, nonatomic) UIView *videoContent; // @synthesize videoContent=_videoContent;
@property(nonatomic) unsigned long long playState; // @synthesize playState=_playState;
@property(retain, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(nonatomic) __weak id <TMPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;	// IMP=0x00000001017f6078
- (void)removeMovieNotificationObservers;	// IMP=0x00000001017f5ce0
- (void)installMovieNotificationObservers;	// IMP=0x00000001017f5b48
- (void)firstVideoFrameRendered:(id)arg1;	// IMP=0x00000001017f5acc
- (void)moviePlayBackDidFinish:(id)arg1;	// IMP=0x00000001017f58fc
- (void)loadStateDidChange:(id)arg1;	// IMP=0x00000001017f5870
- (void)mediaIsPreparedToPlayDidChange:(id)arg1;	// IMP=0x00000001017f5860
- (void)moviePlayBackStateDidChange:(id)arg1;	// IMP=0x00000001017f5768
- (void)currentPlayerHUDInfo:(id)arg1;	// IMP=0x00000001017f540c
- (void)destoryFFPlayer;	// IMP=0x00000001017f52d0
- (id)setupFFPlayerOptions;	// IMP=0x00000001017f52bc
- (void)setupFFPlayer;	// IMP=0x00000001017f4c6c
- (void)layoutViews;	// IMP=0x00000001017f4a88
- (void)playerSoundOff;	// IMP=0x00000001017f4a44
- (void)playerSoundOn;	// IMP=0x00000001017f4a00
- (void)updateVideoURL:(id)arg1;	// IMP=0x00000001017f4918
- (void)updateScaleMode:(long long)arg1;	// IMP=0x00000001017f48c4
- (_Bool)isPlaying;	// IMP=0x00000001017f4878
- (void)replay;	// IMP=0x00000001017f47b8
- (void)shutdown;	// IMP=0x00000001017f4764
- (void)stop;	// IMP=0x00000001017f4724
- (void)pause;	// IMP=0x00000001017f46e4
- (void)play;	// IMP=0x00000001017f46a4
- (void)prepareToPlay;	// IMP=0x00000001017f4664
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001017f45e4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

