//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (APIPUtil)
+ (id)colorWithCustom:(id)arg1;	// IMP=0x00000001010dc840
+ (id)colorWithRGB:(id)arg1;	// IMP=0x00000001010dc614
+ (id)colorWithHex:(id)arg1;	// IMP=0x00000001010dc4e8
@end

