//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (AETileComponentRender)
+ (id)tl_defaultProductImageWithCornerRadius:(float)arg1;	// IMP=0x00000001009fe2ac
+ (id)tl_defaultProductImage;	// IMP=0x00000001009fe228
- (void)tl_prepareForReuse;	// IMP=0x00000001009fea4c
- (_Bool)loadImageFromLocalBundleIfNeededWithUrl:(id)arg1;	// IMP=0x00000001009fe874
- (void)tl_renderWithTile:(id)arg1;	// IMP=0x00000001009fe488
@end

