//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (APIPUtil)
+ (id)imagesWithName:(id)arg1;	// IMP=0x00000001010f0c8c
+ (id)customImageWithName:(id)arg1;	// IMP=0x00000001010f0c10
+ (void)netImageWithName:(id)arg1 callback:(CDUnknownBlockType)arg2;	// IMP=0x00000001010f0870
+ (id)localImageWithName:(id)arg1;	// IMP=0x00000001010f075c
+ (id)imageWithColor:(id)arg1 inRect:(struct CGRect)arg2;	// IMP=0x00000001010f069c
+ (id)imageWithColor:(id)arg1;	// IMP=0x00000001010f0680
+ (id)imageFromDefaultBundlewithName:(id)arg1;	// IMP=0x00000001010f0664
+ (id)imageFromBundle:(id)arg1 withName:(id)arg2;	// IMP=0x00000001010f053c
- (id)imageWithTintColor:(id)arg1 blendMode:(int)arg2;	// IMP=0x00000001010f0e80
- (id)imageWithGradientTintColor:(id)arg1;	// IMP=0x00000001010f0e70
- (id)imageWithTintColor:(id)arg1;	// IMP=0x00000001010f0e60
@end

