//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (AE_SDWebImageSetURL)
- (void)ae_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 progress:(CDUnknownBlockType)arg4 completed:(CDUnknownBlockType)arg5;	// IMP=0x000000010000d324
- (void)setUrlSetFlag:(long long)arg1;	// IMP=0x000000010000d2cc
- (long long)urlSetFlag;	// IMP=0x000000010000d280
@end

