//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface UILabel (NKRRTheme)
- (void)nkrr_setStyle:(unsigned long long)arg1;	// IMP=0x000000010138bd10
- (void)nkrr_setFontSizeToken:(id)arg1 fontWeightToken:(id)arg2;	// IMP=0x000000010138bc90
- (void)nkrr_setColorToken:(id)arg1;	// IMP=0x000000010138bc38
@end

