//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (AFEasyTable)
+ (id)viewControllerWithEasyTable:(CDUnknownBlockType)arg1;	// IMP=0x000000010089cbcc
- (void)setupEasyTable:(CDUnknownBlockType)arg1;	// IMP=0x000000010089cd28
@end

