//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UTHitBuilder.h"

@interface UTPageHitBuilder : UTHitBuilder
{
}

- (id)build;	// IMP=0x0000000101a8bb74
- (void)setDurationOnPage:(long long)arg1;	// IMP=0x0000000101a8bae8
- (void)setReferPage:(id)arg1;	// IMP=0x0000000101a8ba6c
- (void)setPageName:(id)arg1;	// IMP=0x0000000101a8b9c4
- (id)init;	// IMP=0x0000000101a8b8e8

@end

