//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VKApiBase.h"

@interface VKApiPhotos : VKApiBase
{
}

- (id)save:(id)arg1;	// IMP=0x00000001009566f8
- (id)saveWallPhoto:(id)arg1;	// IMP=0x0000000100956678
- (id)getWallUploadServer:(long long)arg1;	// IMP=0x0000000100956590
- (id)getWallUploadServer;	// IMP=0x0000000100956578
- (id)getUploadServer:(long long)arg1 andGroupId:(long long)arg2;	// IMP=0x0000000100956448
- (id)getUploadServer:(long long)arg1;	// IMP=0x0000000100956360

@end

