//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VSImageFilter.h"

@class VSImageFramebuffer;

@interface VSImageYuvToRgbFilter : VSImageFilter
{
    VSImageFramebuffer *secondInputFramebuffer;	// 176 = 0xb0
    int yuvConversionLuminanceTextureUniform;	// 184 = 0xb8
    int yuvConversionChrominanceTextureUniform;	// 188 = 0xbc
    int yuvConversionMatrixUniform;	// 192 = 0xc0
    unsigned int firstTexture;	// 196 = 0xc4
    unsigned int secondTexture;	// 200 = 0xc8
}

- (void).cxx_destruct;	// IMP=0x0000000101abf83c
- (void)processMovieFrame:(struct __CVBuffer *)arg1 curTime:(CDStruct_1b6d18a9)arg2;	// IMP=0x0000000101abf690
- (void)setInputFramebuffer:(id)arg1 atIndex:(long long)arg2;	// IMP=0x0000000101abf614
- (void)renderToTextureWithVertices:(const float *)arg1 textureCoordinates:(const float *)arg2;	// IMP=0x0000000101abf208
- (id)init;	// IMP=0x0000000101abf0f8

@end

