//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WebViewImpl : NSObject
{
}

+ (void)stopLoading:(struct UIWebView *)arg1 from:(id)arg2;	// IMP=0x0000000101150528
+ (struct UIWebView *)webViewInit;	// IMP=0x000000010115047c

@end

