//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WVConfigBase.h"

@interface WVMonitorConfig : WVConfigBase
{
}

+ (id)sharedConfig;	// IMP=0x0000000101b93e1c
- (void)configUpdated:(_Bool)arg1;	// IMP=0x0000000101b9404c
- (id)getConfigUrl:(id)arg1;	// IMP=0x0000000101b93f90
- (_Bool)lock;	// IMP=0x0000000101b93f38
- (id)init;	// IMP=0x0000000101b93ed0

@end

