//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "WVURLInterceptorCallbackProtocol.h"
#import "WVWebViewDelegate.h"

@class NSString, UIView<WVWebViewProtocol>, WVUserContentController;

@interface WVRuleWebViewController : UIViewController <WVWebViewDelegate, WVURLInterceptorCallbackProtocol>
{
    _Bool _bounces;	// 8 = 0x8
    _Bool _openWebKitLongPress;	// 9 = 0x9
    _Bool _openLongPressSaveImage;	// 10 = 0xa
    _Bool _autoPlayAudio;	// 11 = 0xb
    _Bool _openLocalService;	// 12 = 0xc
    UIView<WVWebViewProtocol> *_webView;	// 16 = 0x10
    long long _useWKWebView;	// 24 = 0x18
    CDUnknownBlockType _souldStartLoadAction;	// 32 = 0x20
    CDUnknownBlockType _didStartLoadAction;	// 40 = 0x28
    CDUnknownBlockType _didFinishLoadAction;	// 48 = 0x30
    CDUnknownBlockType _didFailLoadAction;	// 56 = 0x38
}

@property(copy, nonatomic) CDUnknownBlockType didFailLoadAction; // @synthesize didFailLoadAction=_didFailLoadAction;
@property(copy, nonatomic) CDUnknownBlockType didFinishLoadAction; // @synthesize didFinishLoadAction=_didFinishLoadAction;
@property(copy, nonatomic) CDUnknownBlockType didStartLoadAction; // @synthesize didStartLoadAction=_didStartLoadAction;
@property(copy, nonatomic) CDUnknownBlockType souldStartLoadAction; // @synthesize souldStartLoadAction=_souldStartLoadAction;
@property(nonatomic, getter=isUseWKWebView) long long useWKWebView; // @synthesize useWKWebView=_useWKWebView;
- (void).cxx_destruct;	// IMP=0x0000000101b37794
- (CDUnknownBlockType)callBackResponeseForJSWithHandlerName:(id)arg1 className:(id)arg2;	// IMP=0x0000000101b37664
- (id)currentJSBContext;	// IMP=0x0000000101b37658
- (id)getWebView;	// IMP=0x0000000101b3764c
- (void)autoWiredJSBridgeWithTargetJSFile:(id)arg1;	// IMP=0x0000000101b375d0
@property(nonatomic) _Bool isForbiddenBroswerViewPull;
- (void)closeLongPressSaveImage;	// IMP=0x0000000101b375a8
- (void)openLongPressSaveImage;	// IMP=0x0000000101b37598
- (void)permiteLongPressEvent;	// IMP=0x0000000101b37588
- (void)forbiddenLongPressEvent;	// IMP=0x0000000101b37578
- (void)setIsUseWKWebView:(long long)arg1;	// IMP=0x0000000101b37568
- (_Bool)isWebViewReleased;	// IMP=0x0000000101b37550
- (void)releaseWebView;	// IMP=0x0000000101b37538
@property(nonatomic, getter=isForbiddenPullScroll) _Bool forbiddenPullScroll;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000101b372f8
- (_Bool)interruptJumpToLocalPage:(long long)arg1 withParam:(id)arg2 withRequest:(id)arg3;	// IMP=0x0000000101b372f0
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;	// IMP=0x0000000101b37298
- (void)webViewDidFinishLoad:(id)arg1;	// IMP=0x0000000101b37278
- (void)webViewDidStartLoad:(id)arg1;	// IMP=0x0000000101b37258
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;	// IMP=0x0000000101b371e4
- (id)webviewJSBContext;	// IMP=0x0000000101b37190
- (void)callRegistedHandler:(id)arg1 withMethod:(id)arg2 withData:(id)arg3 withFatherClass:(id)arg4 withFatherMethod:(id)arg5 withResultCallback:(CDUnknownBlockType)arg6;	// IMP=0x0000000101b37088
- (void)callRegistedHandler:(id)arg1 withMethod:(id)arg2 withData:(id)arg3 withFatherClass:(id)arg4 withFatherMethod:(id)arg5;	// IMP=0x0000000101b36f9c
- (void)registeHandler:(id)arg1 withClassName:(id)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x0000000101b36ef0
- (void)registerHandler:(id)arg1 withClassName:(id)arg2 withHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000101b36e44
- (void)registerHandler:(id)arg1 withBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000101b36dbc
- (void)closeLocalService;	// IMP=0x0000000101b36dac
- (void)openLocalService;	// IMP=0x0000000101b36d9c
- (void)setIsOpenLocalService:(_Bool)arg1;	// IMP=0x0000000101b36d90
@property(nonatomic, getter=isOpenLocalService) _Bool openLocalService;
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000101b36c98
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000101b36c18
- (void)dealloc;	// IMP=0x0000000101b36b74
- (id)getCurrentUrl;	// IMP=0x0000000101b36b14
- (void)loadPageByUrl:(id)arg1 postBody:(id)arg2;	// IMP=0x0000000101b368e4
- (void)loadPageByUrl:(id)arg1;	// IMP=0x0000000101b36874
- (void)loadPageByRequest:(id)arg1;	// IMP=0x0000000101b36804
- (_Bool)decideIsUseWKWebView;	// IMP=0x0000000101b367fc
@property(readonly, nonatomic) _Bool webViewCanGoForward;
@property(readonly, nonatomic) _Bool webViewCanGoBack;
@property(nonatomic, getter=isAutoPlayAudio) _Bool autoPlayAudio;
@property(nonatomic, getter=isOpenLongPressSaveImage) _Bool openLongPressSaveImage;
@property(nonatomic, getter=isOpenWebKitLongPress) _Bool openWebKitLongPress;
@property(nonatomic) _Bool bounces;
@property(readonly, nonatomic) WVUserContentController *userContentController;
@property(readonly, nonatomic, getter=isLoading) _Bool loading;
- (void)initWebView;	// IMP=0x0000000101b3630c
@property(readonly, nonatomic) UIView<WVWebViewProtocol> *internalWebView;
- (void)setWebView:(id)arg1;	// IMP=0x0000000101b362c4
@property(readonly, nonatomic) UIView<WVWebViewProtocol> *webView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000101b36194

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

