//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WVDynamicHandler.h"

@interface WVScrollWidget : WVDynamicHandler
{
}

+ (void)hiddenInfinitScroll:(id)arg1 withCallback:(CDUnknownBlockType)arg2 withWebView:(id)arg3 withViewController:(id)arg4;	// IMP=0x0000000101b44e54
+ (void)hideInfiniteScroll:(id)arg1 withCallback:(CDUnknownBlockType)arg2 withWebView:(id)arg3 withViewController:(id)arg4;	// IMP=0x0000000101b44d34

@end

