//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface WVUILoadingBox : UIView
{
    UILabel *_loadingBoxTitle;	// 8 = 0x8
}

@property(retain, nonatomic) UILabel *loadingBoxTitle; // @synthesize loadingBoxTitle=_loadingBoxTitle;
- (void).cxx_destruct;	// IMP=0x0000000101b408cc
- (void)resize:(struct CGRect)arg1;	// IMP=0x0000000101b4080c
- (void)setTitle:(id)arg1;	// IMP=0x0000000101b407f4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000101b40478

@end

